components/checkbox/CheckboxItem.tsx

fix rn-checkbox no active when disable

fix rn-checkbox no active when disable

---

components/popup/index.web.tsx

没有 `Popup` 的时候，调用 `Popup.hide()` 会报错

fix popup when call hide before show

---

components/popup/index.web.tsx

调用 `Popup.show()` 多次的话，会出现多个 Popup。
多个 Popup 应该用 `Popup.newInstance()`。`Popup.show()` 只应该有一个 Popup。
所以应该先隐藏之前的实例，再创建新的。

Fix popup: hide previous instance before creating a new one

---

components/grid/index.tsx

issues: https://github.com/ant-design/ant-design-mobile/issues/755
问题：Grid onClick点击失效
原因：Grid 由FlexItem 与Flex组件包裹着，onClick事件绑定在外层的FlexItem组件上，所以点击时调用的内层的Flex组件的默认onPress函数。
已通过DEMO证明，两个TouchableWithoutFeedback，分别加上onPress函数，点击时只有最里面的那个TouchableWithoutFeedback的onPress函数会被调用。
**但是不清楚之前的RN会不会也是这样，所以保留了原有的操作**
DEMO RN版本：0.40.0
DEMO代码：https://gist.github.com/Lxxyx/3043b1120943c6abe93914727d4323a7
点击时输出：Inner TouchableWithoutFeedback

fix(RN-Grid) 修复Grid onClick点击失效的BUG

---

components/button/PropsType.tsx
components/button/index.md

`prefixCls `,`className `都是class前缀
但prefixCls特殊一点，文档可以补充得详细点，我不太会表达就没动
```
const wrapCls = {
[className as string]: className,
[prefixCls as string]: true,
[`${prefixCls}-primary`]: type === 'primary',
[`${prefixCls}-ghost`]: type === 'ghost',
[`${prefixCls}-warning`]: type === 'warning',
[`${prefixCls}-small`]: size === 'small',
[`${prefixCls}-inline`]: inline,
[`${prefixCls}-across`]: across,
[`${prefixCls}-disabled`]: disabled,
[`${prefixCls}-loading`]: loading,
};
```

Button缺少className声明

---

components/input-item/index.web.tsx

ref: #830 
- `onTouchStart`在PC上无效
- 时间增大到200是因为，100ms, 会先blur -> rerender -> clear icon 消失 --> 等不到 clear 的 onClick执行 （这个方案还是不够好 @pigcan ）

fix(input-item): clear bug on pc. close #830

---

components/picker/PropsType.tsx

不好意思，自己挖的坑自己填
`IPopupCascaderProps`里`cascader`是必填项，`Picker`里内置了cascader，一般不需要传进去，不是必填项
又因为不确定你们typescript用的版本，就手动写了`IPartialPopupCascaderProps`
`2.1`支持`Partial`，声明可以写成
```
type IPartialPopupCascaderProps = Partial<IPopupCascaderProps>
```

Picker tsx error

---

package.json

. ref ant-design/ant-design#4941

refactor: lint flow

---

components/date-picker/__tests__/__snapshots__/demo.test.web.js.snap
components/date-picker/demo/basic.md
components/date-picker/index.tsx
components/date-picker/index.web.tsx
components/date-picker/utils.tsx

fix(DatePicker): defaultDate should consider maxDate & minDate

---

components/search-bar/index.web.tsx

修复Android 上无法clear的bug：
- onBlur 先 focus = false
- rerender, clear icon 被 hidden
- 由于移动端click 300 ms 延迟，click 得不到触发

fix(SearchBar): onBlur before onClick, cause android can not clear.

---

README.md
README.zh-CN.md

中文说明里有一句英文，English readme link `.github/CONTRIBUTING.en-US.md` is not exists.

fix readme typo

---

components/modal/PromptContainer.tsx
components/modal/__tests__/__snapshots__/demo.test.js.snap
components/modal/demo/basic.tsx
components/modal/index.tsx
components/modal/index.zh-CN.md
components/modal/prompt.tsx
components/modal/style/prompt.tsx

feature: rn modal.prompt, ref #1011

---

components/input-item/__tests__/__snapshots__/demo.test.web.js.snap
components/input-item/demo/basic.md
components/input-item/index.web.tsx
components/search-bar/__tests__/__snapshots__/demo.test.web.js.snap
components/search-bar/demo/basic.md
components/search-bar/index.web.tsx
components/textarea-item/__tests__/__snapshots__/demo.test.web.js.snap
components/textarea-item/demo/basic.md
components/textarea-item/index.web.tsx

fix input textarea search autofocus bug

---

components/carousel/index.web.tsx
components/date-picker/index.tsx
components/date-picker/index.web.tsx
components/locale-provider/index.tsx
components/menu/index.tsx
components/nav-bar/index.tsx
components/notice-bar/Marquee.tsx
components/pagination/index.tsx
components/pagination/index.web.tsx
components/range/index.tsx
components/refresh-control/demo/basic.tsx
components/search-bar/demo/basic.tsx
components/table/index.tsx
package.json
site/desktop/src/template/Content/ComponentDoc.jsx
site/desktop/src/template/Content/Demo.jsx
site/desktop/src/template/Content/MainContent.jsx
site/desktop/src/template/Layout/Header.jsx
site/desktop/src/template/Layout/index.jsx

React v15.5.0 extracted `React.PropTypes` and `React.createClass` into their own packages. Usage of these two modules will result in console errors.
See: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html
This PR migrates components to new styles according to official guide above.

Fix React v15.5.0 new deprecation warnings

---

components/tab-bar/PropsType.tsx

This prop pass through to Tab. It's documented but missing here.

add dot to interface TabBarItemProps

---

components/input-item/Input.web.tsx
components/input-item/index.web.tsx

improve: split input from input-item

---

components/input-item/index.web.tsx

Support decimal number

---

components/radio/__tests__/__snapshots__/demo.test.js.snap
components/radio/__tests__/__snapshots__/demo.test.web.js.snap
components/radio/demo/basic.md
components/radio/demo/basic.tsx
components/radio/index.en-US.md

Translation Radio

---

components/notice-bar/__tests__/__snapshots__/demo.test.js.snap
components/notice-bar/__tests__/__snapshots__/demo.test.web.js.snap
components/notice-bar/demo/basic.md
components/notice-bar/demo/basic.tsx
components/notice-bar/index.en-US.md

translation of NoticeBar

---

components/input-item/style/index.tsx

修复InputItem -> input_font_size
issue #1174
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1181)

Fix fontSize font_size_heading -> input_font_size

---

components/accordion/__tests__/__snapshots__/demo.test.web.js.snap
components/badge/__tests__/__snapshots__/demo.test.web.js.snap
components/button/__tests__/__snapshots__/demo.test.web.js.snap
components/checkbox/__tests__/__snapshots__/demo.test.web.js.snap
components/date-picker/__tests__/__snapshots__/demo.test.web.js.snap
components/drawer/__tests__/__snapshots__/demo.test.web.js.snap
components/input-item/__tests__/__snapshots__/demo.test.web.js.snap
components/list-view/__tests__/__snapshots__/demo.test.web.js.snap
components/list/ListItem.web.tsx
components/list/__tests__/__snapshots__/demo.test.web.js.snap
components/list/style/index.less
components/locale-provider/__tests__/__snapshots__/demo.test.web.js.snap
components/menu/__tests__/__snapshots__/index.test.web.js.snap
components/picker/__tests__/__snapshots__/demo.test.web.js.snap
components/radio/__tests__/__snapshots__/demo.test.web.js.snap
components/stepper/__tests__/__snapshots__/demo.test.web.js.snap
components/swipe-action/__tests__/__snapshots__/demo.test.web.js.snap
components/switch/__tests__/__snapshots__/demo.test.web.js.snap
components/textarea-item/__tests__/__snapshots__/demo.test.web.js.snap

Remove platform detect code from List.Item#render()
This pr make List.Item render riple div on all device. But still show ripple effect on android only.
close #1200 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1219)

Make List.Item ssr friendly

---

components/accordion/PropsType.tsx
components/accordion/__tests__/__snapshots__/demo.test.js.snap
components/accordion/__tests__/__snapshots__/index.test.js.snap
components/accordion/index.tsx
components/badge/PropsType.tsx
components/flex/PropsType.tsx
components/grid/PropsType.tsx
components/input-item/PropsType.tsx
components/list-view/PropsType.tsx
components/list/PropsType.tsx
components/pagination/PropsType.tsx
components/progress/PropsType.tsx
components/radio/PropsType.tsx
components/result/PropsType.tsx
components/result/index.web.tsx
components/search-bar/PropsType.tsx
components/search-bar/index.web.tsx
components/textarea-item/PropsType.tsx
components/white-space/PropsType.tsx
components/wing-blank/PropsType.tsx

<del>大致看了下所有组件样式字段的定义</del>
<del>web: `style: React.CSSProperties`</del>
<del>native: `styles: any`</del>
<del>目前有部分不是按照这个规则来的，web，native都用了style字段，导致用rn开发，tsc报错</del>
<del>* Flex</del>
<del>* WhiteSpace</del>
<del>* wing-blank</del>
<del>所以为了不造成break change，先改成style: any，在2.0里再把两个字段分开来</del>
<del>另外为什么不是`styles?: StyleSheet.Style`</del>
临时修复组件的style type
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1262)

fix style tsx (temporary)

---

components/list/ListItem.web.tsx

omit platform prop before pass to div
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1276)

fix platform prop warning list item div

---

components/locale-provider/__tests__/__snapshots__/demo.test.web.js.snap
components/locale-provider/demo/basic.md
components/locale-provider/index.en-US.md

tranlate locale-provider
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1282)

tranlate locale-provider ref #329

---

components/stepper/__tests__/__snapshots__/demo.test.js.snap
components/stepper/__tests__/__snapshots__/demo.test.web.js.snap
components/stepper/demo/basic.md
components/stepper/demo/basic.tsx
components/stepper/index.en-US.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1286)

stepper translation, ref #329

---

components/switch/PropsType.tsx
components/switch/__tests__/__snapshots__/demo.test.web.js.snap
components/switch/demo/basic.md
components/switch/index.web.tsx
components/switch/index.zh-CN.md
components/switch/style/index.less

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1293)

fix #1290 switch support onClick

---

components/baseType.tsx
components/list-view/handleProps.tsx
components/list/ListItem.tsx
components/list/ListItem.web.tsx
components/list/PropsType.tsx
components/list/index.tsx
components/list/index.web.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1280)
#1212

Refactor list tsx

---

components/button/PropsType.tsx
components/button/index.tsx
components/button/index.web.tsx

#1212 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1327)

refactor Button tsx

---

components/switch/index.web.tsx

This pr resolve Switch SSR issue but not perfect. If user render Switch without platform prop. React will complain about checksum. That's means platform prop is required in SSR mode.
fix #1308 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1338)

[SSR] check navigator before use it in switch

---

components/input-item/Input.web.tsx
components/input-item/index.web.tsx

- tiny 里只用到了 Input.web， 发现加了 scrollintoview 后反而导致键盘遮挡住输入框了
讨论： 要不把 scrollintoview 的这个逻辑交给用户自己来搞，不在组件里实现？
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1401)

move scrollintoview from input to index

---

components/flex/PropsType.tsx
components/list/PropsType.tsx

If set children type. We need allow element array.
```jsx
<Flex>
<Flex.Item />
<Flex.Item />
</Flex>
```
```bash
Type '{ children: Element[]; }' is not assignable to type 'Readonly<FlexWebProps>'.
Types of property 'children' are incompatible.
Type 'Element[]' is not assignable to type 'Element | undefined'.
Type 'Element[]' is not assignable to type 'Element'.
Property 'type' is missing in type 'Element[]'.'
at: '241,13'
source: 'ts'
```
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

allow multi element in children

---

components/flex/PropsType.tsx
components/list/PropsType.tsx

ReactNode is a more loose type that allow string number boolean array and so on
ReactNode 是官方定义文件里用于 children 的类型，它包含了 Element | string | number | boolean | null | undefined 以及上述类型的数组形式，所有 JSX 语法允许的类型这里都有。除非有特殊理由要求 children 必须传入一个组件，否则都应该统一指定为 ReactNode。
另：`Flex.Item` 目前不生效，因为类型并没有导出，目前 `baseType.tsx` 里定义的 `WebProps` 不合理，如果现在导出这个类型的话，其他用到 `Flex` 的组件都无法通过 lint。
改动前：
```tsx
<List>
<List.Item>
<span>abc</span>
</List.Item>
</List>
```
改动后：
```tsx
<List>
<List.Item>
Now: {Date.now()}
<List.Item.Brief>
123
</List.Item.Brief>
</List.Item>
</List>
```
---
This change is [<img …

[TS] loose children type

---

components/menu/PropsType.tsx
components/menu/SubMenu.web.tsx
components/menu/__tests__/__snapshots__/index.test.web.js.snap
components/menu/demo/basic.md
components/menu/index.web.tsx
components/menu/index.zh-CN.md
components/menu/style/index.less

related to issue #1427
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1438)

fix menu mutli active item

---

docs/react/introduce.en-US.md
docs/react/introduce.zh-CN.md

close #1375
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1503)

doc: update begining doc

---

components/segmented-control/__tests__/__snapshots__/index.test.js.snap
components/segmented-control/__tests__/__snapshots__/index.test.web.js.snap
components/segmented-control/__tests__/index.test.js
components/segmented-control/__tests__/index.test.web.js

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1511)

add segmented-control test, ref #1274

---

components/list/__tests__/__snapshots__/demo.test.web.js.snap
components/switch/__tests__/__snapshots__/demo.test.web.js.snap
components/switch/__tests__/__snapshots__/index.test.js.snap
components/switch/__tests__/__snapshots__/index.test.web.js.snap
components/switch/__tests__/index.test.js
components/switch/__tests__/index.test.web.js
components/switch/index.web.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1513)

add test for switch, ref #1274

---

components/toast/style/index.less

`span` 不能去掉，`component=""` 时会导致子节点无法正确渲染。
---
close #1389
Ralevent issues:
- https://github.com/ant-design/ant-design/issues/5869#issuecomment-313400042
- https://github.com/react-component/notification/issues/17
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1541)

Fix toast position bug

---

CHANGELOG.en-US.md
CHANGELOG.zh-CN.md
components/button/__tests__/__snapshots__/demo.test.web.js.snap
components/checkbox/__tests__/__snapshots__/demo.test.web.js.snap
components/flex/Flex.web.tsx
components/flex/__tests__/__snapshots__/demo.test.web.js.snap
components/flex/style/index.less
components/image-picker/__tests__/__snapshots__/demo.test.web.js.snap
components/locale-provider/__tests__/__snapshots__/demo.test.web.js.snap
components/menu/__tests__/__snapshots__/index.test.web.js.snap
components/menu/index.web.tsx
components/pagination/__tests__/__snapshots__/demo.test.web.js.snap
components/pagination/__tests__/__snapshots__/index.test.web.js.snap
components/radio/__tests__/__snapshots__/demo.test.web.js.snap

close #1532 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1549)

fix flex #1532

---

components/style/themes/default.less
components/tabs/style/index.less

重现条件：
1、使用Tabs组件；
2、使用Popup组件（向上）；
3、Popup弹出时暗色遮罩层z-index为999，Tabs翻页白色遮罩层z-index为1000。
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1512)

修改Tabs组件翻页z-index为999(from 1000)

---

components/list/ListItem.tsx
components/list/PropsType.tsx

Added functionality for listening for long press on a ListItem.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1533)

Adding onLongPress to ListItem

---

components/input-item/style/index.less
components/modal/AlertContainer.tsx
components/modal/Modal.tsx
components/modal/Modal.web.tsx
components/modal/PromptContainer.tsx
components/modal/__tests__/__snapshots__/demo.test.js.snap
components/modal/alert.tsx
components/modal/alert.web.tsx
components/modal/demo/alert.md
components/modal/demo/basic.tsx
components/modal/demo/prompt.md
components/modal/index.en-US.md
components/modal/index.tsx
components/modal/index.zh-CN.md
components/modal/prompt.tsx
components/modal/prompt.web.tsx
components/modal/style/Dialog.less
components/modal/style/index.less
components/modal/style/index.tsx
components/modal/style/prompt.tsx
components/search-bar/style/index.less
components/style/themes/default.less
components/style/themes/default.tsx
components/textarea-item/style/index.less

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1603)

feat(Modal): support placeholder & add theme

---

.gitignore
components/view/index.web.tsx

I coding a h5 web using antd mobile, thinking to use in both h5 and app. so I choice antd-mobile's View component for layout.But there is a warning like this:
```
Warning: Unknown prop `Component` on <div> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
in div (created by View)
in View (at Root.js:15)
in Provider (at Root.js:14)
in Root (at index.js:20)
in AppContainer (at index.js:19)
```
I add one line to fix it.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1594)

View component from web, modify the warning:Unknown prop `Component` on <div> tag. 

---

components/search-bar/index.en-US.md
components/search-bar/index.web.tsx
components/search-bar/index.zh-CN.md

ref #1609 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1621)

Fix search bar

---

site/desktop/src/template/Layout/Header.jsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1622)

fix(site): navigate to correct site for current language when searching component

---

CHANGELOG.en-US.md
CHANGELOG.zh-CN.md
components/search-bar/index.web.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1731)

fix searchBar onClear #1721

---

components/search-bar/index.web.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1756)

fix(SearchBar): cancel should blur. close #1721

---

CHANGELOG.en-US.md
CHANGELOG.zh-CN.md
components/_util/touchFeedback.tsx
components/action-sheet/index.tsx
components/button/index.tsx
components/checkbox/demo/basic.md
components/grid/index.tsx
components/grid/style/index.less
components/image-picker/index.tsx
components/input-item/CustomKeyboard.tsx
components/input-item/index.tsx
components/input-item/style/index.less
components/list/ListItem.tsx
components/list/demo/basic.md
components/list/index.en-US.md
components/list/index.zh-CN.md
components/modal/Modal.tsx
components/popover/Item.tsx
components/search-bar/index.tsx
components/search-bar/style/index.less
components/segmented-control/index.tsx
components/slider/style/index.less
components/tag/index.tsx
components/tag/style/index.less
components/textarea-item/index.tsx
components/textarea-item/style/index.less
package.json

考虑到有些组件（:active）替换成  rc-touchable 会增加单个组件的体积，现方案为下：
移除 rc-touchable，增加 TouchFeedback util 组件，废弃 list 用到的 onlongpress
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1772)

refactor: use touchFeedback to replace :active pseudo-class, ref #1717

---

package.json
webpack.config.js

更新内容见： https://github.com/ant-design/antd-tools/pull/60
更新后构建大小比较：
启用 Tree shaking 后 antd-mobile.min.js 的构建结果小了 55k，css 大了一点是因为 autoprefix 更新后，`box-sizing` 也会被 prefix。
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1960)

Upgrade to antd-tools@4.0.0

---

package.json

Update in react-native-collapsible handles issue with crash due to `View.propTypes` as of 0.9.0. See [fix](https://github.com/oblador/react-native-collapsible/commit/960fd76ab8317b78ce72fe4767273738fec38f5f).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1969)

Update Collapsible. Fixes crash with React 0.49

---

components/stepper/__tests__/__snapshots__/demo.test.native.js.snap
components/stepper/index.native.tsx

Hi,
A keyboardType of stepper on Native environment should be numeric only. It can prevent the unexpected problem that happens because the value is not numeric.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2020)

set 'keyboardType' of stepper to be a numeric type

---

components/grid/PropsType.tsx
components/grid/__tests__/__snapshots__/demo.test.js.snap
components/grid/__tests__/__snapshots__/demo.test.native.js.snap
components/grid/demo/basic.md
components/grid/demo/basic.native.tsx
components/grid/index.en-US.md
components/grid/index.native.tsx
components/grid/index.tsx
components/grid/index.zh-CN.md
components/icon/__tests__/__snapshots__/demo.test.native.js.snap

feat(Grid): grid cell add custom style
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2046)

 feat(Grid): grid cell add custom style

---

components/style/index.less

- rem 高清方案的用户，引入高清方案脚本来设置 html font size
- 非高清方案的用户，antd-mobile 设计规范应该对全局的 font-size 没要求
@peter0011 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2106)

fix: remove body font-size

---

components/steps/StepsItem.native.tsx
components/steps/__tests__/__snapshots__/demo.test.native.js.snap
components/steps/demo/basic.native.tsx
components/steps/index.native.tsx
components/steps/style/index.native.tsx

Add support horizontal support for steps.
* I have not found the related doc
* The css I write may be not suitable for all circumstances.
* not tested in most devices.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2090)

[RN] add horizontal support for steps

---

components/activity-indicator/__tests__/__snapshots__/demo.test.native.js.snap
components/flex/Flex.native.tsx
components/flex/FlexItem.native.tsx
components/flex/__tests__/__snapshots__/demo.test.native.js.snap
components/flex/demo/basic.native.tsx
components/grid/__tests__/__snapshots__/demo.test.native.js.snap
components/icon/__tests__/__snapshots__/demo.test.native.js.snap
components/locale-provider/__tests__/__snapshots__/demo.test.native.js.snap
components/pagination/__tests__/__snapshots__/demo.test.native.js.snap
components/pagination/__tests__/__snapshots__/index.test.native.js.snap

relate issues: #1108, #769
`Flex` and `FlexItem` now have capability to switch that `TouchableWithoutFeedback` wrap or not.
When developer pass one of `onPress` `onLongPress` `onPressIn` `onPressOut` parameter, the `Flex` component will be wrapped by `TouchableWithoutFeedback`.
This solution avoid make a break change to developer.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2095)

[RN] Optional use TouchableWithoutFeedback component in Flex/FlexItem component

---

components/date-picker-view/locale/sv_SE.tsx
components/date-picker/locale/sv_SE.tsx
components/input-item/locale/sv_SE.tsx
components/locale-provider/sv_SE.tsx
components/pagination/locale/sv_SE.tsx
components/picker/locale/sv_SE.tsx
components/search-bar/locale/sv_SE.tsx

i can add sv_SE to rmc-date-picker later but basically it will be plain copy of en US because its empty.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2132)

add swedish locale 🇸🇪

---

components/modal/prompt.tsx

Fix https://github.com/ant-design/ant-design-mobile/issues/2164
Fix https://github.com/ant-design/ant-design-mobile/issues/2204
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2221)

fix(Modal): prompt should handle defaultValue correctly

---

docs/react/customize-theme.en-US.md

Right now the documentation is redirecting to less variables of *ant design* project no *ant mobile design* project
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2290)

Update documentation links to ant mobile

---

components/image-picker/PropsType.tsx
components/image-picker/__tests__/__snapshots__/demo.test.js.snap
components/image-picker/demo/accept.md
components/image-picker/demo/custom.md
components/image-picker/index.en-US.md
components/image-picker/index.tsx
components/image-picker/index.zh-CN.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2269)

Image picker feature, add file accept

---

components/modal/OperationContainer.native.tsx
components/modal/PromptContainer.native.tsx

Fix https://github.com/ant-design/ant-design-mobile/issues/2214
Modal.prompt的onClose重复调用引发的bug，在prompt中不能通过点击mask触发onClose，建议移除
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2243)

issues#2214：Modal.prompt中onPress返回promise仍会导致modal关闭

---

components/input-item/CustomInput.tsx
components/input-item/index.tsx

`onChange: (value: any) => void` 变成了 `onChange: (e: object) => void`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2403)

fix: input type money

---

components/button/index.native.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2404)

revert(button): rest props

---

components/textarea-item/index.tsx

This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2506)

fix(textarea-item)

---

components/search-bar/style/index.less

This commit force ".am-search-synthetic-ph" and ".am-search-clear"
to use "content-box" to prevent external style such as ".am-tabs" breaking
its box-sizing.
Refs: #2447 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2510)

fix: style of <SearchBar/>

---

components/input-item/CustomInput.tsx
components/input-item/__tests__/__snapshots__/demo.test.js.snap
components/input-item/demo/basic.md
components/input-item/demo/money.md
components/input-item/index.tsx

This commit applies a fault tolerance when user performs "delete" on a
number "value" passed to \<InputItem/>, error occurred because Number
doesn't have .substring().
Refs: #2493 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2508)

fix(input-item): value.substring is not a function

---

components/input-item/index.tsx

This commit put onChange() to the next tick of event loop,
to prevent cursor from dislocation.
close: #2441 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2532)

fix(input-item): cursor dislocation in UC browser

---

components/input-item/index.tsx

PR #2532 会引起一个问题：在输入的内容中间插入或删除字符的时候，光标会被重置到末尾，体验很差。
该PR将区分对待 onChange 过程中**可能会**改变原始值的场景（bankCard、phone、number），对其他类型不做延迟 `onChange`。
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2537)

fix(input-item): user experience regression on non-mutate control

---

components/date-picker/locale/ru_RU.tsx
components/input-item/locale/ru_RU.tsx
components/locale-provider/ru_RU.tsx
components/picker/locale/ru_RU.tsx
components/search-bar/locale/ru_RU.tsx

Added by Russian locale for all components
And i remove 'Пожалуйста, выберите' because, the inscription was cut off and it was visible only  'Пожалуйста ...' It is read as if the component asks for help :). in English 'Please ...'
If leave "выберите" in English "select", it will look like an order and still does not convey thoughts. I did a small test, and people said that it's better not to write anything at all
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2400)

Full locale components in russian language

---

components/locale-provider/__tests__/__snapshots__/demo.test.js.snap
components/picker/index.tsx
components/search-bar/index.tsx

Refs: https://github.com/ant-design/ant-design-mobile/issues/2502
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2511)

fix: Picker && SearchBar LocalProvider Context

---

components/input-item/CustomInput.tsx
components/input-item/CustomKeyboard.tsx
components/input-item/Portal.tsx
components/input-item/__tests__/__snapshots__/demo.test.js.snap
components/input-item/index.tsx
components/input-item/locale/en_US.tsx
components/input-item/locale/ru_RU.tsx
components/input-item/locale/sv_SE.tsx
components/input-item/locale/zh_CN.tsx
components/locale-provider/__tests__/__snapshots__/demo.test.js.snap
components/modal/style/Dialog.less

This PR fix these problems：
+ Fix(inputitem): add wai-aria support for the money type InputItem  
The money type InputItem is simulated with the div tag, rather than the origin
input tag. To support wai-aria needs a little more work, for the div tag, by adding
role of `textbox` make div perform like input in aria mode
For the CustomKeyboard, it will lead to wrong focus when not adding aria
supoort for backspace and keyboard canceling
Fixed: #2419, #2418
+ Fix(inputitem): remove extra useless custom keyboard instance
In the money type of InputItem, the CustomKeyboard will be created as many times as the InputItem is used. The inner variable `customNumberKeyboard` will point to the latest custom keyboard instance
which can avoid the repeat appearing animation. But when the InputItem is …

Fix(inputitem): add wai-aria suppport for the money type InputItem

---

components/input-item/CustomInput.tsx
components/input-item/CustomKeyboard.tsx
components/input-item/PropsType.tsx
components/input-item/demo/money.md
components/input-item/index.en-US.md
components/input-item/index.tsx
components/input-item/index.zh-CN.md

This commit add a new property to InputItem. Allow user to add
customized props to virtual money keyboard.
Fixed: #2247 
*isNewFeature* **:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2550)

feat(input-item): add "moneyKeyboardWrapProps"

---

components/input-item/CustomInput.tsx
components/input-item/PropsType.tsx
components/input-item/demo/money.md
components/input-item/index.en-US.md
components/input-item/index.tsx
components/input-item/index.zh-CN.md

This commit add a new property that allow user to handle virtual
keyboard confirm event.
Closes: #2192, #2249
*isNewFeature* **:**
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2551)

feat(input-item): add "onVirtualKeyboardConfirm" callback

---

components/modal/prompt.tsx

Issues: Hard to focus. #2177  #2285 
Solution: Auto focus when clicking input.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2560)

hotfix: hard to focus ref#2177

---

components/input-item/CustomKeyboard.tsx
components/input-item/style/index.less

The cancel key and del key of custom keyboard has no text but only icon. In aria mode, the content
behind the keyboard will lead wrong focus
Add the `sr-class` for iOS, and `role`、`aria-label` for others
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2568)

Fix(InputItem): avoid error focus in aria mode

---

package.json
tests/shared/demoTest.js

Issue: https://github.com/facebook/jest/issues/5401
Ref: https://github.com/ant-design/ant-design/blob/master/tests/shared/demoTest.js#L16
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2657)

test: fix jest test error

---

README.md
README.zh-CN.md
components/locale-provider/en_US.tsx
components/locale-provider/ru_RU.tsx
components/locale-provider/sv_SE.tsx
components/menu/index.tsx
components/menu/locale/en_US.tsx
components/menu/locale/ru_RU.tsx
components/menu/locale/sv_SE.tsx
components/menu/locale/zh_CN.tsx
components/pull-to-refresh/index.tsx
components/pull-to-refresh/locale/en_US.tsx
components/pull-to-refresh/locale/ru_RU.tsx
components/pull-to-refresh/locale/sv_SE.tsx
components/pull-to-refresh/locale/zh_CN.tsx

+ Menu && PullToRefresh suport locale，ref: https://github.com/ant-design/ant-design-mobile/issues/2629
+ Remove some RN description
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2669)

Support locale

---

components/tabs/style/index.less

fix https://github.com/ant-design/ant-design-mobile/issues/2672
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2674)

fix: tabs underline render error on some webview

---

components/tab-bar/PropsType.tsx
components/tab-bar/__tests__/__snapshots__/demo.test.js.snap
components/tab-bar/demo/listview-tabbar.md
components/tab-bar/demo/top-tabbar.md
components/tab-bar/index.en-US.md
components/tab-bar/index.tsx
components/tab-bar/index.zh-CN.md
components/tab-bar/style/index.less

fix https://github.com/ant-design/ant-design-mobile/issues/2526
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2564)

feat: add tabBarPosition on TabBar

---

components/button/__tests__/__snapshots__/demo.test.js.snap
components/button/demo/basic.md
components/button/style/index.less

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2822)

fix: button with icon and inline (#2742)

---

components/textarea-item/index.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2825)

fix: line break cause textareaItem word count corrupt for iOS （#1265)

---

site/desktop/src/static/demo.less

fix #2869
fix #2841
* 优化代码拷贝的图标样式
* 优化代码操作按钮样式，防止被遮挡
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2894)

feat: 优化代码片段操作区

---

site/desktop/src/static/home.less
site/desktop/src/template/Home/index.jsx

add angular link

---

components/carousel/index.tsx

---
`<Carousel />` Component missing three property-declaration.
`frameOverflow`, `cellSpacing` and `slideWidth`
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2848)

fix: add Carousel missing property-declaration

---

components/action-sheet/__tests__/__snapshots__/demo.test.js.snap
components/action-sheet/demo/basic.md
components/action-sheet/index.en-US.md
components/action-sheet/index.tsx
components/action-sheet/index.zh-CN.md
components/action-sheet/style/index.less
components/action-sheet/style/index.tsx

*isBugFix*
*isNewFeature*
demo：
```
const BUTTONS = ['Operation1', 'Operation2', 'Operation3', 'Operation4', 'Operation5', 'Delete', 'Cancel'];
const BADGES = [{
// 对应options配置的下标，从0开始
index: 1,
dot: true,
}, {
index: 2,
text: 3100,
}, {
index: 3,
text: '推荐',
}, {
index: 4,
text: '···',
}];
ActionSheet.showActionSheetWithOptions({
options: BUTTONS,
cancelButtonIndex: BUTTONS.length - 1,
destructiveButtonIndex: BUTTONS.length - 2,
// 徽标数组
badges: BADGES,
// title: 'title',
message: 'I am description, description, description',
maskClosable: true,
'data-seed': 'logId',
wrapProps,
},
(buttonIndex) => {
this.setState({ clicked: BUTTONS[buttonIndex] });
});
```
demo image:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" …

action-sheet support badge  动作面板支持徽标

---

components/textarea-item/style/index.less

当我使用TextareaItem组件时，在多行文本框中输入长标点符号...............................或者。。。。。。。。。。。,组件并不能自动换行。原因是textarea css样式中的word-break:break-all和word-wrap:break-word共同使用的时候，长标点符号并不能换行
* 问题在华为荣耀honor 7c以及chrome浏览器上都经过测试，都出现了一样的问题
* 去掉word-break属性或者设置word-break: break-word;都可以解决这个问题
可在 https://mobile.ant.design/components/textarea-item-cn/ 中输入............进行测试
如图出现滚动条，我想这应该是个常见的bug，毕竟不是所有人都像我这么无聊去乱输入。
When I use the TextareaItem component, enter a long punctuation in the multiline text box............................... or. . . . . . . . . . . The component does not automatically wrap. The reason is that when the word-break:break-all and word-wrap:break-word are used together in the textarea css style, the long punctuation does not wrap.
* The problem has been tested on Huawei  honor 7c and chrome browser, …

fix: Enter long punctuation mark texarea-item without wrap

---

components/input-item/index.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3044)

Fix(InputItem): this.state.value undefined error

---

components/image-picker/index.en-US.md
components/image-picker/index.tsx
components/image-picker/index.zh-CN.md

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3115)

image-picker添加了对批量添加图片的支持，一次性把所有添加的图片都返回，只触发一次onChange

---

components/flex/style/index.less

fix  align-content css problem
The api documentation and the implementation of typescript is correct , but the css has some typo result in wrong effect .
#2462
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3106)

Fix Flex component's  css definition

---

components/input-item/index.tsx
components/search-bar/index.tsx
components/textarea-item/index.tsx

#3000 fix it;
repo: https://codesandbox.io/s/j2j44wxj95
device: ios12.1,iphoneXr/iphone 8p/iphone 6s
software: wechat 7.0.0
zh:
修复IOS12.1下微信6.7.4~7.0.0版本网页中：
当小键盘弹出收缩时，会导致body重新渲染，并且致使触摸层错位。
已提交repo：https://codesandbox.io/s/j2j44wxj95
重现步骤为（PS：Safari正常）：
1. 选中最下方input-item，输入任意字符；
2. 在小键盘没有缩下去情况下点击picker组件；
3. 点击Picker确认发现点击无效。
4. 长按界面当出现选择光标时发现确认键与实际渲染位置不符。
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3017)

Fix#3000 and Fix inputItem make Picker unable to click in Wechat with IOS12;

---

components/input-item/index.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3124)

Fix(InputItem): add try catch to setSelection (#3120)

---

components/modal/PropsType.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3136)

修复使用TypeScript时Modal onPresss方法缺乏参数定义

---

components/date-picker/index.tsx
components/list/PropsType.tsx
components/picker/AbstractPicker.tsx
package.json

@types/react 的版本太低了，新的某些 types api 没有，比如 hoist-non-react-statics 里用到的 MemoExoticComponent
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3186)

fix: react types error with React.MemoExoticComponent and others

---

components/image-picker/PropsType.tsx
components/image-picker/__tests__/__snapshots__/demo.test.js.snap
components/image-picker/__tests__/index.test.js
components/image-picker/demo/length.md
components/image-picker/index.en-US.md
components/image-picker/index.tsx
components/image-picker/index.zh-CN.md

close #2150
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3185)

feat:(imagePicker) add config disableDelete

---

components/input-item/index.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3189)

修复Input格式化类型删除时，光标定位问题

---

components/action-sheet/style/index.less
components/calendar/style/index.less
components/input-item/style/custom-keyboard.less
components/modal/style/Dialog.less

* [x Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3180)

Fix(inputItem): add safe-area

---

components/icon/loadSprite.tsx
components/modal/__tests__/__snapshots__/demo.test.js.snap
components/modal/demo/basic.md

业务线反馈在iOS 9.2的真机上Modal无法正常展示，初步排查后发现是由于同时使用了Icon组件，经过详细定位后发现是引入Svg的时机问题，如果Svg延后引入就没问题，和 https://github.com/ant-design/ant-design-mobile/blob/caeff3da09935a70814cc7979d604310b7e3522f/components/icon/loadSprite.tsx#L3 描述的问题有点类似，经测试发现把Svg的样式`position: absolute`删除即可解决问题，实测在iOS8、iOS9以及最新的iOS版本均可正常展示
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3229)

fix: iOS9以下svg引起的Modal展示问题

---

components/input-item/index.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3237)

Fix(InputItem): add try catch to getSelection (#3236)

---

components/calendar/style/index.less

link issue
Fixes #3173
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3252)

[fix] 修正chrome下，flexbox被子元素撑开无法滚动的问题

---

components/input-item/CustomInput.tsx
components/input-item/__tests__/index.test.js
components/input-item/index.en-US.md
components/input-item/index.tsx
components/input-item/index.zh-CN.md

close https://github.com/ant-design/ant-design-mobile/issues/2737
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3246)

fix: 修复数字键盘遮挡输入框的问题

---

components/flex/Flex.tsx

---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3220)

fix: wrong type definition in flex props.

---

package.json
site/desktop/src/template/Content/Demo.jsx

Ref: https://github.com/warmhug/antd-mobile-demo-data/pull/4
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3292)

fix: 升级antd-mobile-demo-data修复部分Demo在iOS9下白屏的问题

---

components/toast/index.en-US.md
components/toast/index.tsx
components/toast/index.zh-CN.md

refer relative issues #3257
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3304)

Toast add global config.

---

components/modal/prompt.tsx

close #3137
Thanks for https://github.com/ant-design/ant-design-mobile/pull/3280
* [x ] Make sure that you add at least one unit test for the bug which you had fixed.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3346)

fix: fix prompt can not focus in Wechat

---

components/input-item/style/custom-keyboard.less

修复ios数字键盘after + animation: infinte 导致before元素重复创建问题
修复ios数字键盘左对齐光标不居中问题
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3385)

fix: ios上数字输入框光标闪烁问题，数字输入框左对齐时光标不居中问题

---

components/image-picker/PropsType.tsx

好久不见!
files 数组中的文件要指定类型, 使用 `{}` 会造成不便.
onAddImageClick 是有参数的, 示例 "自定义选择图片的方法" 中有用到.
更好的实现是泛型组件:
```tsx
type MyFile = { url: string; id: number }
<ImagePicker<MyFile> />
```
不知道我们能否接受.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3491)

fix: ImagePicker types

---

src/components/text-area/index.tsx

Fix: React does not recognize the `showCount` prop on a DOM element.

fix: text-area showCount warning

---

src/components/space/index.tsx

看文档应该只支持直接配置，不支持 'small' 之类的配置。
上面判断了 props.size 下面取的是 size ，虽然都一样，但我还是忍不住调整一下

chore: space code style & supports number as size prop

---

src/components/dialog/demos/index.tsx

**问题**：在 [v5 alpha (Poplar)](https://next.mobile.ant.design/components/dialog) 网站上，组件列表 -> Dialog -> **等待 confirm 完成** 的Demo 中，点击 **等待 confirm 完成** 按钮就会立即弹出 toast 提示。
**原因：是因为执行代码中缺少了 await 关键字。**
目前已经将 await 添加完成。在点击 **等待 confirm 完成** 按钮时不会弹出提示，在点击 *确定* 或者 *取消* 按钮后，才会弹出对应的 toast 提示。

Fix missing await in dialog demo

---

src/components/picker/picker.less

`overflow: hidden` 本身已经是 `overflow-y: hidden; overflow-x: hidden;的简写方式` 
截图为`Edge` 浏览器示意图

style: 删除多余的 CSS 代码

---

src/components/index-bar/index-bar.tsx

fix: IndexBar children type

---

src/components/stepper/stepper.less
src/components/stepper/stepper.tsx

#3969 
增强：Stepper 调整为复用现有的 Input 和 Button 组件

enhance: Stepper use self Input and Button Component

---

src/components/checkbox/checkbox.tsx

#3989 
特性：当 Checkbox 与 Checkbox.Group 一起使用时，如果 Checkbox 出现了 checked 或 defaultChecked 属性，添加一些警告告诉用户，该用法是错误的。

enhance: When used with Checkbox.Group add some warnings

---

src/components/nav-bar/nav-bar.less
src/components/nav-bar/nav-bar.tsx

fix the problem of custom Navbar back icon

fix: custom Navbar back icon failure

---

src/components/form/demos/demo1.tsx
src/components/stepper/stepper.tsx

之前的 Stepper 存在一个问题：对于受控的 Stepper，如果外部直接改变 value，Stepper 的 state 可以正常改变但 input 上显示的值还是旧的，这也是 #4018 的原因。
这个 pr 略微改进了 Stepper 内部对 inputValue 的渲染逻辑，可以解决上述问题。

From Stepper demo and a bug fix

---

src/components/image-uploader/image-uploader.tsx

当task上传失败status为fail时，onDelete回调不能正确删除该图片

fix: ImageUploader delete task failed

---

.husky/pre-commit

修复window bash执行husky pre-commit 异常
```
error: cannot spawn .husky/pre-commit: No such file or directory
```

chore: pre-commit add shebang

---

src/utils/merge-locale.ts
src/utils/use-lazy-memo.tsx

Modify the way of dependency loading to avoid excessive package size.

fix: (lodash) Modify the way of dependency loading to avoid excessive package size.

---

src/components/space/index.en.md
src/components/space/index.zh.md
src/components/space/space.less
src/components/space/space.tsx
src/components/space/tests/space.test.tsx

CSS `justify-content` 并不支持 `baseline`，所以在 Space 组件中进行了移除。
https://developer.mozilla.org/en-US/docs/Web/CSS/justify-content

fix: (Space) remove value of `baseline` from `justify` prop

---

src/components/image-viewer/slides.tsx
src/components/picker-view/column.tsx
src/components/slider/thumb.tsx
src/components/swipe-action/swipe-action.tsx

将 `useDrag` 的 `pointer` 参数设置为 `{ touch: true }`，解决部分机械无法拖动的 bug。 #4303

fix: set pointer.touch to true to fix drag gesture on some mobile devices

---

src/components/dropdown/demos/demo1.tsx
src/components/dropdown/dropdown.tsx
src/components/dropdown/index.en.md
src/components/dropdown/index.zh.md

issue：https://github.com/ant-design/ant-design-mobile/issues/4310
为 `Dropdown` 组件新增 `closeOnMaskClick` 属性，默认为 `true`，表示是否开启「点击遮罩关闭下拉菜单」。

feat: (Dropdown) add `closeOnMaskClick` prop

---

src/components/picker/demos/index.tsx
src/components/picker/picker.tsx
src/utils/use-lazy-memo.tsx

Picker 的 `onSelect` 和 `onConfirm` 都拥有第二个参数：`context`，但它现在存在以下两个问题：
点开一个 Picker，直接输出 `onSelect` 的 `value` 和 `context`，可以看到：
confirm 一个选项之后（示例中 confirm 了['C', '1']），输出会是：
可见 `context` 中的值好像和 `value` 相比「慢了一步」，这是因为代码实现中，计算 `context` 的函数 `getItems` 中的依赖项 `value` 是组件内 confirmed 后的 `value` 值，也就是说，只有进行 confirmed 后才能改变 `value` ，从而触发 `getItems` 的重新计算。
而作为一个受控组件，在 `onConfirm` 的回调触发时，该组件的新 `value` 还没有被 set。如下图， `onConfirm` 触发了 `setValue`，之后该组件的 `value` 值才会改变。也就是说，`onConfirm` 触发时组件内的 `value` 还是上一次触发 set 的值
这是导致当前 `onSelect` 和 `onConfirm` 的参数中 `value` 值与 `context` 值不同步的原因。
</br>
依旧是获取 `context` 的 `getItems` 函数的问题，这里的依赖 `value` 是组件 confirmed 后的值，也就是说当前 `onSelect` 的参数 `context` 中只会出现 `onConfirm` 的值。
于是会导致下图的问题：
当我在 confirm 一个选项之后（示例中 confirm 了['C', '1']），`onSelect` 的 `context` 始终会返回 ['C', '1'] 的数据
</br> …

fix: (Picker) `context` param in `onSelect` and `onConfirm` return outdated data

---

src/components/picker-view/demos/basic.tsx
src/components/picker-view/index.en.md
src/components/picker-view/index.ts
src/components/picker-view/index.zh.md
src/components/picker-view/picker-view.tsx
src/components/picker-view/use-picker-context.tsx
src/components/picker-view/use-picker-value-extend.tsx
src/components/picker/demos/index.tsx
src/components/picker/index.en.md
src/components/picker/index.ts
src/components/picker/index.zh.md
src/components/picker/picker.tsx
src/components/selector/demos/demo1.tsx
src/components/selector/index.en.md
src/components/selector/index.zh.md
src/components/selector/selector.tsx
src/components/tree-select/index.en.md
src/components/tree-select/index.zh.md
src/components/tree-select/tree-select.tsx

为了代码复用（优雅），将之前获取 `context` 部分的逻辑整合成了 `usePickerContext` hook，在 Picker 和 PickerView 中都通过 `usePickerContext` 来获取 `context`

feat: (PickerView) onChange add context param

---

src/components/switch/switch.tsx

修复在 Switch 中的 beforeChange 的判断范围影响 checked 值无法正确更新的问题
#4420

fix: (Switch) `checked` cannot be changed when `beforeChange` is not set

---

src/components/tabs/tabs.tsx

修复：https://github.com/ant-design/ant-design-mobile/issues/4448
这里不是很清楚为啥要监听根节点的resize，Tabs.Tab的children宽高变化应该不会影响上面的tab吧，所以这里我把监听根节点调整到`tabListContainerRef`。

fix: (Tabs) tab line animation fail when resize

---

src/components/list/demos/index.tsx
src/components/list/index.en.md
src/components/list/index.zh.md
src/components/list/list-item.tsx
src/components/list/list.less
src/components/list/list.tsx

Ability to custom the style of the List and List.Item border
Like this:
```js
style={{
'--item-border-bottom': 'none',
'--border-top': '1px solid red',
'--border-bottom': '1px solid blue',
}}
```

feat: (List) custom border style

---

src/components/image-uploader/image-uploader.tsx

fix [#4328](https://github.com/ant-design/ant-design-mobile/issues/4328) 
我发现删除图片是通过url，相同url图片就会出现BUG。
现在通过index删除。

fix: (ImageUploader) change the deleted logic to delete images by index

---

src/components/input/index.en.md
src/components/input/index.zh.md
src/components/input/input.tsx

用于指定输入框弹出键盘类型，MDN文档如下：
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Global_attributes/inputmode

feat: (Input) add `inputMode` prop

---

src/components/modal/index.en.md
src/components/modal/index.zh.md

the `Action` props of the `Modal `component supports the `primary` field, but the document is not displayed

doc: (Modal) add primary for Action

---

src/components/form/form-item.tsx

之前的写法是
```typescript
const hasFeedback = props.hasFeedback || context.hasFeedback
```
`hasFeedback` 是一个 `boolean`，这会导致 `props.hasFeedBack` 设置无效
现在改成了
```typescript
const hasFeedback = props.hasFeedback !== undefined ? props.hasFeedback : context.hasFeedback
```
只要 `props.hasFeedback` 存在，则以它的值为准。
close #4620

fix: 修复在 FormItem 中 hasFeedback 属性无效的问题

---

src/utils/use-tab-list-scroll.ts

When manually setting activeKey to the first item, it cannot automatically scroll to the first item

fix: (utils)  useTabListScroll not work when activeIndex value is  0

---

src/components/floating-bubble/floating-bubble.less

修复floating-bubble的容器缺少css `box-sizing:border-box`导致无法控制浮动边界的问题。

fix: (FloatingBubble) `--edge-distance` not working properly

---

docs/components/icon/demo-all.tsx

doc: (Icon) selector of copy type must have state

---

src/components/form/form-item.less
src/components/form/form-item.tsx
src/components/form/form.less
src/components/form/form.tsx

**问题：`Form` layout 为 vertical ，`Form.Item` layout 为 horizontal 时，label 的位置会发生变化**
**解决：这里给`Form.Item` 添加了 `${classPrefix}-${layout}`，同时将 layout 样式迁移到 `Form.Item`**
<hr />
另外有几个问题：
1. 目前 `help` 属性有点鸡肋，跟 `label` 展示效果一样，后续会加新的样式吗
2. 这些手动添加`className` `style` 的地方，是否可以用 `withNativeProps` 替代

refactor: (Form) move layout style to `Form.Item`

---

src/components/image/image.tsx
src/utils/use-isomorphic-update-layout-effect.tsx

[#4804](https://github.com/ant-design/ant-design-mobile/issues/4804)
看了下 `useUpdateLayoutEffect` 的实现 
我把传入的`useLayoutEffect` 改成了 `useIsomorphicLayoutEffect`

enchance: replace useUpdateLayoutEffect with useIsomorphicUpdateLayoutEffect

---

package.json
src/components/collapse/collapse.tsx
src/components/tabs/tabs.tsx
src/utils/use-isomorphic-update-layout-effect.tsx
src/utils/use-tab-list-scroll.ts
yarn.lock

1. 给 ahooks 提了个 pr，createUpdateEffect 可以直接 import 了
2.  把所有的 useUpdateLayoutEffect 替换成了 useIsomorphicUpdateLayouEffect

enhance: replace useUpdateLayoutEffect with useIsomorphicUpdateLayouEffect

---

src/components/input/input.tsx

如果未输入任何内容，失去焦点，value会变成''，parseFloat(nextValue)返回NaN，这里做了一次判断，只有在value有值才进行后面的处理
close https://github.com/ant-design/ant-design-mobile/issues/4857

fix: (Input) fix value NaN when element blur

---

src/components/pull-to-refresh/pull-to-refresh.tsx

refactor: (PullToRefresh) replace `pageYOffset` with `scrollY`

---

src/components/ellipsis/ellipsis.tsx
src/components/ellipsis/index.en.md
src/components/ellipsis/index.zh.md

feat: (Ellipsis) add `stopPropagationForActionButtons` props

---

src/components/form/demos/demo2.tsx
src/components/form/form-item.less
src/components/form/form-item.tsx
src/components/form/index.en.md
src/components/form/index.zh.md
src/components/form/tests/form.test.tsx

这个issues #4838  rc-field-form 是支持的，所以在文档里加了 rule 属性 和 warningOnly demo
Rule 定义从 https://ant.design/components/form-cn/#Rule 搬运过来，做了略微修改
其中的 `fileds` 字段试了下好像不能用？(或者是我用法问题)，就先删了

feat: (Form) supports `warningOnly` rule and add doc for rule definitions

---

jest.config.js

chore: update coverage config to exclude `.umi`

---

src/components/dialog/show.tsx
src/components/modal/demos/demo3.tsx
src/components/modal/show.tsx

#4896 
问题原因是先执行了 close ，再执行了 useEffect，导致 visible 又变成了 true
这里我把 `() => setVisible(false)` 变成了异步

fix: (Modal & Dialog) doesn't close when trigger too fast

---

src/components/action-sheet/action-sheet.tsx
src/components/dialog/show.tsx
src/components/image-viewer/methods.tsx
src/components/modal/show.tsx

- fix: 修复 `Modal`、`Dialog`、`ImageViewer`、`ActionSheet` 在显示时立即关闭无效。
- feat: 调整上述组件瞬间关闭时，也能触发`props.onClose`、`props.afterClose`与销毁
- feat: 调整 `ImageViewer`的关闭，与`Modal`、`Dialog`、`ActionSheet`的关闭行为保持一致。 
#4897 的方式采用定时器，有闪烁问题，我个人觉得两种方案都可。

fix: (Modal & Dialog & ImageViewer & ActionSheet) doesn't close when trigger too fast

---

src/components/modal/index.en.md
src/components/modal/index.zh.md
src/components/modal/modal.tsx

Modal组件使用了Mask组件，里面useLockScroll有事件监听,qiankun子应用下，shadowDOM隔离，手机上内容不能滚动,我在Modal组件加了disableBodyScroll属性给里面的Mask组件，先保证能正常使用。

enhance: (Modal) support disableBodyScroll prop for Mask

---

src/components/number-keyboard/number-keyboard.tsx
src/components/number-keyboard/tests/numberic-keyboard.test.tsx

fix #4988 
在 iphone 上点击虚拟键盘时会触发 `onTouchEnd` 和 `onMouseUp`，导致两次 `onInput`
`onTouchEnd` 和 `onMouseUp` 的问题，见 #4995

refactor: (NumberKeyboard) remove onMouseUp

---

src/locales/ko-KR.ts

Create ko-KR file.
This file is a Korean translation file.

feat: add ko-KR locale

---

src/components/date-picker-view/date-picker-view.tsx
src/components/date-picker/date-picker.tsx
src/components/picker-view/demos/demo1.tsx
src/components/picker-view/index.en.md
src/components/picker-view/index.zh.md
src/components/picker-view/picker-view.tsx
src/components/picker-view/wheel.tsx
src/components/picker/index.en.md
src/components/picker/index.zh.md
src/components/picker/picker.tsx
src/utils/use-lock-scroll.ts

1. Picker和PickerView组件增加mouseWheel属性
2. 暴露useLockScroll中的lock&unlock方法
3. 中英文文档跟进

feat: Picker和PickerView组件增加mouseWheel事件支持

---

src/components/form/form-item.less

#5091 
[兼容性](https://developer.mozilla.org/zh-CN/docs/Web/CSS/justify-content#browser_compatibility) 
`justify-content: right`, chrome 93 才支持...

refactor: (Form) replace justify-content `right` with `flex-end`

---

src/components/capsule-tabs/capsule-tabs.less
src/components/jumbo-tabs/jumbo-tabs.less
src/components/tabs/tabs.less

fix: (Tabs & JumboTabs & CapsuleTabs) auto scroll fail when the parent element is a flex layout

---

src/components/dropdown/dropdown.less

fix: (Dropdown) icon display is not centered

---

src/components/notice-bar/index.en.md
src/components/notice-bar/index.zh.md

默认shu'xing'zhi属性值单词拼写错误，应为SoundOutline

doc: (NoticeBar) update props icon default

---

src/components/badge/badge.tsx
src/components/badge/index.ts

- content 为 `Badge.dot` 的时，会有 ts 错误
- 优化了下 `as any` 的 ts

enhance: (Badge) adjust ts definition

---

jest.config.js
src/tests/excludeWarning.ts
src/tests/setup.ts

参考了下 ant-design 的 [excludeWarning.tsx](https://github.com/ant-design/ant-design/blob/master/tests/shared/excludeWarning.tsx)
实际用的时候发现 px tester 的 error 比 beforeAll 调用要早，所以加在了 setup 里
- - -
ps: 这个 exclude 只对当前项目有效

test: add setup and exclude warning

---

src/components/ellipsis/ellipsis.tsx

fix(Ellipsis): middle mode has more characters on right than on left

---

src/components/ellipsis/ellipsis.tsx

refactor(Ellipsis): remove deprecated style property `webkitBoxOrient`

---

src/components/picker/picker.less

fix(Picker): fix Picker body height over-exceeds in iOS 11.4 Safari

---

src/components/badge/badge.tsx
src/components/badge/index.en.md
src/components/badge/index.zh.md
src/components/badge/tests/badge.test.tsx

#5290 
调整了下结构、即使没有children、多一层 wrap 应该也没啥关系！这样className & style 可以放在外层！

feat(badge): add `wrapperClassName` and `wrapperStyle` props

---

.github/workflows/codeql-analysis.yml

发现提示 `CodeQL Action v1 will be deprecated on December 7th, 2022. Please upgrade to v2. `
根据文档说明
https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/
项目中在使用的有
`github/codeql-action/init`
`github/codeql-action/autobuild`
`github/codeql-action/analyze`
更改版本到 v2

chore(github workflows): codeql-action v1 to v2

---

src/components/steps/steps.less

steps 在暗黑模式下 .adm-step-icon-container 类中  background 为白色
```css
.adm-step .adm-step-indicator .adm-step-icon-container {
position: absolute;
z-index: 1;
background: var(--adm-color-white);
color: var(--icon-color);
}
```

fix(Steps): icon background should be black in dark mode

---

src/components/cascade-picker-view/tests/cascade-picker-view.test.tsx
src/components/config-provider/tests/__snapshots__/config-provider.test.tsx.snap
src/components/picker-view/picker-view.less
src/components/picker-view/tests/picker-view.test.tsx
src/components/picker-view/wheel.tsx
src/components/picker/picker.tsx

无障碍
1. Picker弹窗上的确定/取消按钮在Android和ios上的无障碍焦点定位问题
2. android上选择器选中某个项时跳动问题
3. android无法选中项问题
4. 当选中某一项后，该项后面没有可选了，导致焦点不在弹窗上

fix(Picker): picker component accessibility issues on android

---

src/components/cascader/cascader.tsx
src/components/cascader/demos/demo1.tsx
src/components/cascader/index.en.md
src/components/cascader/index.ts
src/components/cascader/index.zh.md

与 picker 相同，增加 `children render actions` 和 `ref`

feat(Cascader): add a new actions param to children render function

---

src/components/switch/demos/demo2.tsx
src/components/switch/index.en.md
src/components/switch/index.zh.md
src/components/switch/switch.tsx
src/components/switch/tests/switch.test.tsx
src/utils/use-props-value.ts

Switch 弃用了 `beforeChange` 属性，而直接把异步处理的能力合并到 `onChange` 里了
这样，如果用户需要拦截和处理报错的话，就可以手动在 `onChange` 里 `try/catch` 了

feat(Switch): deprecate `beforeChange` prop and `onChange` supports promise

---

src/components/action-sheet/action-sheet.tsx
src/components/dialog/show.tsx
src/components/modal/show.tsx

在以下指令式打开对话框时`Modal.show()`、`Dialog.show()`、`ActionSheet.show()`，
排除掉 `destroyOnClose` 、`forceRender` 两个类型。因为，指令式模式下，对话框关闭时总是卸载组件

feat(Modal & Dialog & ActionSheet): omit `destroyOnClose` and `forceRender` types in imperatively show mode

---

docs/guide/migration.en.md

Added a grammar correction to make the "not all package managers support npm aliases" make sense in English

doc: Grammar fixes to make it make sense in English

---

src/components/swipe-action/swipe-action.tsx

1. fix #5490
2. 解决bug（1），可以通过 SwipeAction 组件 demo 复现，步骤如下：
2.1 右滑列表项C，展示”置顶“按钮
2.2 点击列表项B，来恢复列表项C的默认效果，点击一次无法关闭，再次点击时才关闭（不符合预期）
3. 解决bug（2），可以通过 SwipeAction 组件 demo 复现，步骤如下：
3.1 右滑列表项C，展示”置顶“按钮
3.2 点击列表项B，来恢复列表项C的默认效果
3.3 再次左滑列表项C，列表项B也会出现滑动（不符合预期）

fix(SwipeAction): fix close on touch outside and interaction between SwipeActions

---

src/components/picker-view/wheel.tsx

fix #5512
bug产生原因：因为 memo 的关系，renderLabel 的改变不会刷新 Wheel 组件

fix(Picker): wheel is not updated when `renderLabel` or `mouseWheel` is updated

---

src/components/rate/rate.less
src/components/rate/rate.tsx
src/components/rate/tests/rate.test.tsx

在PC上拖动的时候有个不太符合预期的行为= =，单个Star的`onClick`会后于`drag`事件执行，导致value在拖动结束时会变成开始点击时对应的value，这里全部改到`drag`事件中用拖动的逻辑计算了= =。
用`Math.round`点击触发的体验不是很棒= =，点左半边的话会被省略= =。改成`Math.ceil`的话拖动的时候就又有点灵敏= =。
加了一个test，把对应test中的click改成了`mockDrag`的原地拖动。

fix(Rate): rate value will reset when drag stop on PC

---

src/components/slider/demos/demo2.tsx
src/components/slider/slider.tsx

修复 `Slider` 组件使用时 `range` 属性时，崩溃的问题。复现如下：
```tsx
<Slider value={40} range />
```

fix(Slider): fix crash when `range` and `value` don't match

---

src/components/stepper/stepper.tsx

enhance(Stepper): default `decimal` input mode

---

jest.config.js
src/components/swipe-action/tests/swipe-action.test.tsx

看了一下主要挂在几个测试用例，剩下的偶偶发：
```
src/components/swipe-action/tests/swipe-action.test.tsx
SwipeAction › manual return to the position
TestingLibraryElementError: Unable to find an element with the text: 确定. This could be because the text is broken up by multiple elements. In this case, you can provide a function for your text matcher to make your matcher more flexible.
src/components/dialog/tests/dialog.test.tsx
Dialog › wait for confirm to complete
Timed out in waitForElementToBeRemoved.
src/components/passcode-input/tests/passcode-input.test.tsx
PasscodeInput › native keyboard should be work
TypeError: _a.scrollIntoView is not a function
PasscodeInput › event callbacks should be called
TypeError: _a.scrollIntoView is not a function
```
动画相关由于 `react-spring` 是通过 `applyAnimatedValues` 方法在 React …

chore: Update test related config

---

src/components/nav-bar/index.en.md
src/components/nav-bar/index.zh.md
src/components/nav-bar/nav-bar.tsx

close https://github.com/ant-design/ant-design-mobile/issues/5714

enhance(NavBar): back support ReactNode

---

src/components/picker/picker.less

IOS 10 下 flex 布局高度计算有点问题，做个兜底操作。

fix: ios picker view scroll height not correct

---

gulpfile.js

chore: prevent transform `rgba()` to `#RGBA`

---

gulpfile.js

ref: https://github.com/ant-design/ant-design-mobile/issues/5571
试了一下不支持 `globalThis` 的浏览器(如，IOS 9)
- `globalThis` 报错
- `typeof globalThis` 返回 undefined
然后看下用 vite/webpack 打包出来的产物
- vite
```js
// development
var __read$7 = globalThis && globalThis.__read || ... 
var __spread$2 = globalThis && globalThis.__spread || ... 
```
-  webpack
```js
// development
/******/ 	/* webpack/runtime/global */
/******/ 	(() => {
/******/ 		__webpack_require__.g = (function() {
/******/ 			if (typeof globalThis === 'object') return globalThis;
/******/ 			try {
/******/ 				return this || new Function('return this')();
/******/ 			} catch (e) {
/******/ 				if (typeof window === 'object') return window;
/******/ 			}
/******/ 		})();
/******/ 	})();
```
所以这里将 compatible umd 改成用 webpack 构建
---
另外发现有些三方包的产物是 …

chore: use webpack build compatible umd

---

src/components/popup/popup.tsx
src/utils/dev-log.ts
src/utils/use-lock-scroll.ts

IOS 12 下横向滚动后再垂直滚动会被认为是合理的滚动方向（标准为初次滚动一个方向后就会被锁定，而非可以混合滚动），导致在开始 `touchmove` 没有调用 `preventDefault` 就会出现后期无法阻止滚动导致 Popup 锁不住屏幕滚动的问题。
添加一个 `strict` 模式，使用后直接锁定而不关心方向性。
不确定是否保险，请多关注一下。

fix: popup strict prevent default to fix with IOS12

---

src/components/picker-view/picker-view.less

Wheel 加了 `item-height-measure` 元素后，无障碍模式下的布局位置发生了偏移

fix(Picker): position offset in a11y

---

.github/workflows/check.yml

有个 warning，查了下 [releases](https://github.com/pnpm/action-setup/releases) 已经解决了

chore: update `pnpm/action-setup`

---

src/components/image-viewer/tests/image-viewer.test.tsx

[maxZoom support auto](https://github.com/ant-design/ant-design-mobile/blob/master/src/components/image-viewer/tests/image-viewer.test.tsx#L115) 这个 case mock 了很多模块，导致有些 case 挂了
调整了下顺序，在这个 case 测完后手动 `restoreAllMocks`

test(ImageViewer): fix failed test

---

src/components/image-uploader/preview-item.tsx
src/components/image-uploader/tests/image-uploader.test.tsx

fix(ImageUploader): revokeObjectURL while file change

---

src/components/notice-bar/demos/demo1.tsx
src/components/notice-bar/index.en.md
src/components/notice-bar/index.zh.md
src/components/notice-bar/notice-bar.less
src/components/notice-bar/notice-bar.tsx
src/components/notice-bar/tests/notice-bar.test.tsx

pr 改动想法：
1. 去除文本的`position:absolute`样式和最外层`height`样式，高度自适应；
2. 当`speed`为`0`时，将文本设为可换行；
3. 当文本设置为可换行时，`delay` 属性就没有必要了，应该直接渲染出换行的样子。
#5796

feat(NoticeBar): add `wrap` props

---

.gitignore
pnpm-lock.yaml

Reverts ant-design/ant-design-mobile#5846
没有 lock，compressed-size CI 会挂
> Automatically uses yarn, pnpm or npm ci when lockfiles are present

Revert "chore: update gitignore"

---

package.json
pnpm-lock.yaml
src/tests/testing.tsx

- `@testing-library/react-hooks`  is useless
- `gulp-postcss` peer postcss@"^8.0.0"

chore: remove `@testing-library/react-hooks`

---

src/components/input/index.en.md
src/components/input/index.zh.md
src/components/input/input.tsx
src/components/input/tests/input.test.tsx

input type 为 number 并且配置 min 属性时，输入小数，表单提交会提示 “输入有效值”，配置 step 属性即可解决这个问题

feat(Input): 支持原生 step 属性

---

src/components/footer/footer.tsx

原本的 `import { Divider } from '../divider/divider'` 会缺少 divider 的样式

fix(Footer): adjust `Divider` import path

---

src/components/steps/steps.less

Stpe组件icon的背景色应该去掉才对，如果有个透明底色的图片会直接被默认的白色覆盖

fix(Steps): icon background color should be unnecessary

---

docs/guide/ssr.en.md
docs/guide/ssr.zh.md

transpilePackages is directly exposed to Nextconfig.  see config-shared.d.ts (line:421)

doc: update next config

---

src/utils/reduce-and-restore-motion.ts

According to [doc](https://beta.reactjs.org/reference/react/useSyncExternalStore#caveats), subscribe fn reference should be stable, so just extract it into single fn. 😂

chore: extract motion subscribe into single fn

---

src/components/popover/popover.less
src/components/popover/popover.patch.less

Another question:
in `theme-dark.less` defined  `--adm-color-text: #e6e6e6;`.
in `popover.less` defined 
```css
/* The new colors are defined here */
&&-dark {
--adm-color-text: #ffffff;
color: #ffffff;
}
```
why use white color instead of `#e6e6e6` ?
So is this by design, or is there a deviation?

enhance(Popover): use global css variables to control font color

---

src/components/ellipsis/ellipsis.tsx

修复默认展开时，只有 `收起` 没有 `展开` 按钮的情况
```
<Ellipsis
content={content}
defaultExpanded={true}
collapseText='收起'
/>
```
before:
after:

fix(ellipsis): fix only collapseText without expandText

---

src/components/action-sheet/tests/__snapshots__/action-sheet.test.tsx.snap
src/components/action-sheet/tests/action-sheet.test.tsx
src/components/popup/popup.tsx

当 `percent.to` 回参为 0 时，设置 `Popup` 的 `transform` 为 `none`，以解决该样式导致的定位相对位置变化问题。
参考链接：[MDN position](https://developer.mozilla.org/zh-CN/docs/Web/CSS/position)

fix(Popup): omit transform to fixed nested fixed position

---

src/components/form/form.tsx

Form context disabled props for es6

fix: form context disabled props for es6

---

.nvmrc

Local dev not support node18 right now.
```node
node:internal/crypto/hash:71
this[kHandle] = new _Hash(algorithm, xofLen);
^
Error: error:0308010C:digital envelope routines::unsupported
at new Hash (node:internal/crypto/hash:71:19)
at Object.createHash (node:crypto:133:10)
at module.exports.__webpack_modules__.57442.module.exports (...\ant-design-mobile\node_modules\.pnpm\@umijs+deps@3.5.35\node_modules\@umijs\deps\compiled\webpack\
4\bundle4.js:135907:62)
at NormalModule._initBuildHash (...\ant-design-mobile\node_modules\.pnpm\@umijs+deps@3.5.35\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:109317:16)     
at ...\ant-design-mobile\node_modules\.pnpm\@umijs+deps@3.5.35\node_modules\@umijs\deps\compiled\webpack\4\bundle4.js:109352:10
at …
```

fix: pin dev node version to node16-lts

---

src/components/form/index.tsx

> 在基于antd组件 根据业务加工后传递进props，用到了Rule约束业务组件的props
1. 需要import 到 rc-field-form 可能会又幽灵依赖问题
2. 需要通过Pick来从FormItemProps 来提取出 Rule

feat(form): form export type add Rule & RuleObject & RuleRender

---

src/components/collapse/collapse.tsx

issues #6068 
激活类名为 `adm-collapse-panel-content-active`

feat(Collapse): add active classname when panel is active 

---

src/components/swiper/swiper.tsx
src/components/swiper/tests/__snapshots__/swiper.test.tsx.snap
src/components/swiper/tests/swiper.test.tsx

问题场景：现在代码中是监听 index 来触发 props.onIndexChange?.(index) 执行。当外部注册 onIndexChange 事件，根据最新的 index 设置当前激活的 SwiperItem 样式。面临的渲染时序将是这样的：
react-spring、setIndex -> onIndexChange，在 onIndexChange 回调设置的样式将会比 react-spring 慢一拍，在安卓机低端机上特别明显，有很强的卡顿感；
PR 修改：在执行 react-spring 动画时同时执行 onIndexChange，保证在同一拍重渲染；同时给当前激活的 SwiperItem 增加样式，方便使用者覆盖样式

optimize: swiper onIndexChange 事件 和 react-spring api 同步执行

---

src/components/ellipsis/ellipsis.tsx
src/components/ellipsis/tests/__snapshots__/ellipsis.test.tsx.snap
src/components/ellipsis/tests/ellipsis.test.tsx

#6063
`root` 被`display`为`none` 时，`originStyle` 的 `width` 计算有误，导致 `container` 容器处理完的 文本塞进 `root` 后出现 抖动闪烁

enhance: ellipsis display glint

---

src/components/list/list-item.tsx

`React.MouseEvent`默认泛型为`Element`会导致使用`e.currentTarget.dataset`时ts报错,明确为`HTMLElement`
(或许可以根据onClick和clickable进一步明确为`HTMLDivElement`或`HTMLAnchorElement`?)

enhance(List): ListItem `onClick` type completion

---

src/components/popup/index.en.md
src/components/popup/index.zh.md
src/components/popup/popup.tsx
src/components/popup/tests/popup.test.tsx

feat(Popup): add `closeOnSwipe` prop

---

src/components/notice-bar/notice-bar.less

自从 #5448  版本 noticebar 扩展了关闭按钮的可点击区域后，右侧区域是一个 block 内嵌了一个 extra + 一个 block 的 close 按钮，而右侧区域本身不是 flex 布局的，导致同时设置 extra 和 closeable 时这俩会换行显示

fix(NoticeBar): notice-bar wrap if set extra & closeable together

---

src/components/swiper/swiper.tsx

微调设置顺序，以避免某些场景下 React 强制触发 flush 导致 `getCurrent` 不正确的问题

fix: swiper setCurrent may force affect of getCurrent

---

src/components/calendar/convert.ts
src/components/capsule-tabs/capsule-tabs.tsx
src/components/collapse/collapse.tsx
src/components/dropdown/dropdown.tsx
src/components/jumbo-tabs/jumbo-tabs.tsx
src/components/rate/star.tsx
src/components/safe-area/safe-area.tsx
src/components/side-bar/side-bar.tsx
src/components/skeleton/skeleton.tsx
src/components/tab-bar/tab-bar.tsx
src/components/tabs/tabs.tsx

`isValidElement` 增加泛型类型修复 多处 `push` 的 `ts`提示
`TabBarItemProps` 与 `ComponentProps<typeof TabBarItem>` 最后结果一致  `ComponentProps` 内部用 `infer` 提取了返回值
`ReactElement` 参数可以直接用 `TabBarItemProps `
过程中顺便看到了 import React 的重复，也全局改了一下

style: repair push(child) type  warning

---

src/components/input/input.tsx
src/components/input/tests/input.test.tsx

fix(Input): fix the display issue of numbers starting with 0

---

src/components/radio/index.en.md
src/components/radio/index.zh.md
src/components/radio/radio.tsx
src/components/radio/tests/radio.test.tsx

enhance: Radio add click event

---

src/components/passcode-input/tests/passcode-input.test.tsx

test: fix failed test

---

src/components/checkbox/checkbox.tsx
src/components/checkbox/index.en.md
src/components/checkbox/index.zh.md
src/components/checkbox/tests/checkbox.test.tsx

和 #6195 一样，Checkbox  也有这个问题~  Radio 的已经加了

enhance: Checkbox add click event

---

src/components/date-picker-view/date-picker-view.tsx
src/components/date-picker-view/demos/demo1.tsx
src/components/date-picker-view/tests/date-picker-view.test.tsx
src/components/picker-view/index.en.md
src/components/picker-view/index.zh.md

https://github.com/ant-design/ant-design-mobile/issues/6137#issuecomment-1546591413

feat(DatePickerView): support till now

---

src/components/text-area/text-area.less

fix #6238
这个 absolute 没比较的父级定位，换行计算错误了

fix(TextArea): hidden textarea element is not positioned relative to its parent

---

src/components/capsule-tabs/capsule-tabs.tsx
src/components/date-picker/date-picker-date-utils.ts
src/components/date-picker/date-picker-week-utils.ts
src/components/dropdown/dropdown.tsx
src/components/footer/footer.tsx
src/components/form/form-array.tsx
src/components/image-uploader/image-uploader.tsx
src/components/modal/modal.tsx
src/components/popover/popover.tsx
src/components/popup/popup.tsx
src/components/result/result.tsx
src/components/stepper/stepper.tsx
src/components/tree-select/multiple.tsx

把 if 语法风格统一了一下，只有一行代码的省略了花括号
删了一些时间久的注释属性
简化了一下箭头函数的 return

chore: code style simplify

---

src/components/cascader-view/cascader-view.tsx
src/components/tree-select/tree-select.tsx
src/hooks/useFieldNames.tsx

tree-select 的 FieldNames 处理，复用hook了
hook 返回的顺序调了,因为感觉 `disabled` 这个 key 不是特别通用。。。

refactor: fieldName index change and tree-select use hook

---

src/components/picker-view/wheel.tsx

fix #6213
再修一次。。。 原来的 6216 关了，已经将方案改成滚动得距离加 已经滚动得距离了

enhance: useWheel dir change

---

src/components/action-sheet/action-sheet.tsx
src/components/action-sheet/index.en.md
src/components/action-sheet/index.zh.md
src/components/action-sheet/tests/action-sheet.test.tsx

feat(ActionSheet): support popup styles

---

src/components/text-area/tests/text-area.test.tsx
src/components/text-area/text-area.tsx

fix(TextArea): reset rows when rows exceed autoSize

---

src/components/steps/steps.tsx

比 #6259 好些得写法可以不用 as 了
`const props = child.props` 与顶部的 `const props = mergeProps(defaultProps, p)`  命名感觉有点混淆 ，然后改成 `childProps` 了

chore: type enhance

---

src/components/tree-select/multiple.tsx

refactor: fieldNames replace with hook

---

src/components/form/form-item.tsx

#6277
props传递的 className 透传多次了，这边给它删了直接交给 withNativeProps函数去添加 props 的 className

fix: classname use repeatedly

---

src/components/rate/rate.tsx

chore: add `--inactive-color-half` type

---

src/utils/tests/use-lock-scroll.test.tsx
src/utils/use-lock-scroll.ts

issue #6282
加的判断是这个 preventDefault 的
https://github.com/ant-design/ant-design-mobile/blob/master/src/utils/use-lock-scroll.ts#L68
下面这个 preventDefault 应该不用加吧？跟这个 PR 有关 #5738
https://github.com/ant-design/ant-design-mobile/blob/master/src/utils/use-lock-scroll.ts#L48

enhance: passive and preventDefault coexist repair

---

src/components/input/input.tsx

这个NativeInputProps 里得  `React.InputHTMLAttributes` 是包含 `placeholder`  `readOnly`  `disabled`  的
```ts
type NativeInputProps = React.DetailedHTMLProps<
React.InputHTMLAttributes<HTMLInputElement>,
HTMLInputElement
>
```
不明白为啥不直接pick 出来而是重写一个
而且可选参数会自己加上 undefined 类型 ， disabled?: boolean | undefined 和   disabled?: boolean 是一样的

chore: pick type to InputHTMLAttributes

---

src/components/picker-view/wheel.tsx
src/components/pull-to-refresh/pull-to-refresh.tsx

原来的 false 用 as unknown 强转到 AddEventListenerOptions 类型是错误的
eventOptions 支持的类型为 AddEventListenerOptions  | undefined

chore: eventOptions  type fix

---

src/utils/tests/use-lock-scroll.test.tsx
src/utils/use-lock-scroll.ts

fix: useLockScroll whether the element scroll is in the end #6253

---

src/components/cascader-view/cascader-view.tsx
src/components/selector/demos/demo1.tsx
src/components/selector/demos/options.tsx
src/components/selector/index.en.md
src/components/selector/index.zh.md
src/components/selector/selector.tsx
src/components/selector/tests/selector.test.tsx
src/hooks/index.tsx

feat: selector's options support fieldNames

---

src/components/action-sheet/action-sheet.less
src/components/button/button.less
src/components/error-block/error-block.less
src/components/form/form.less
src/components/image-uploader/image-uploader.less
src/components/notice-bar/notice-bar.less
src/components/number-keyboard/number-keyboard.less
src/components/popover/popover-menu.less
src/components/progress-bar/progress-bar.less
src/components/tag/tag.tsx
src/components/tag/tests/__snapshots__/tag.test.tsx.snap

#6319
部分写死的颜色改为 css var，
没做的部分
- 文档和 DEMO 中的颜色
- 测试用例中的颜色
- SVG 中的颜色
- 纯白色 #FFFFFF (语义怕匹配错误，因此没改)
- *.patch.less 文件中的颜色

enhance: replace missing colors with css variables. fix #6319

---

src/components/cascader-view/tests/__snapshots__/cascader-view.test.tsx.snap
src/components/tabs/demos/demo5.tsx
src/components/tabs/index.en.md
src/components/tabs/index.zh.md
src/components/tabs/tabs.tsx
src/components/tabs/tests/__snapshots__/tabs.test.tsx.snap
src/components/tabs/tests/tabs.test.tsx

feat(Tabs): support RTL mode

---

src/components/ellipsis/ellipsis.tsx
src/components/ellipsis/tests/ellipsis.test.tsx

fix(Ellipsis): the `whiteSpace` style of the calc container should be the same as Ellipsis

---

docs/components/icon/demo-all.tsx

doc(icon): add margin

---

src/components/cascader-view/cascader-view.tsx
src/components/check-list/check-list-item.tsx
src/components/check-list/check-list.tsx
src/components/check-list/context.tsx
src/components/check-list/index.tsx

At the moment, it is allowed to use only a string as a value in the CheckList, but it is also possible to use numbers.

feat(CheckList): allow using number as value

---

pnpm-lock.yaml
src/components/image-viewer/image-viewer.tsx
src/components/image-viewer/slide.tsx
src/components/image-viewer/slides.tsx
src/components/image-viewer/tests/image-viewer.test.tsx

resolve #6310
主要改动就是删除了 dragLockRef 这个拖动锁，然后把 slide 的冒泡删了，不然外层的· drag不触发。
然后加这段代码是最小改动，离开视图回到原始缩放
```tsx
const [inView] = useInViewport(controlRef)
useEffect(() => {
!inView &&
api.start({
matrix: mat.create(),
})
}, [inView])
```

enhance: delete drag lock. add leave view back to zoom

---

src/components/water-mark/tests/water-mark.test.tsx
src/components/water-mark/water-mark.tsx

fix: #6332 
content 设置空值时，background-image: url("");
控制台存在错误提示: 加载404，但不影响使用
```
<WaterMark
content=""
/>
```
content 设置不是空值时，渲染时，也会先渲染background-image: url("");也存在控制台错误提示问题

fix: (WaterMark) content 设置空值时，控制台存在错误提示

---

src/components/result-page/result-page.less

@1587315093 Could u have a look?
-----
<a href="https://stackblitz.com/~/github/kongmoumou/ant-design-mobile/tree/fix-result-style"><img src="https://developer.stackblitz.com/img/review_pr_small.svg" alt="Review PR in StackBlitz Codeflow" align="left" width="103" height="20"></a> _Submitted with [StackBlitz Codeflow](https://stackblitz.com/~/github/kongmoumou/ant-design-mobile/tree/fix-result-style)._

fix(result-page): footer not align to center

---

src/components/center-popup/center-popup.tsx

fix(CenterPopup): set pointer-events none while animating

---

src/components/image-viewer/image-viewer.tsx
src/components/image-viewer/slide.tsx
src/components/image-viewer/slides.tsx

`onTap` 由 image-viewer.tsx 入口的 `props.onClose` 传递进去赋值。
但 `onTap` 的类型为 onTap: () => void 而 `props.onClose` 为 onTap?: () => void 是可选的
为了兼容必传类型的 `onTap` ，image-viewer 传递是 写法是传递了个函数，然后在里面执行 props.onClose?.()，感觉可以修改一下类型和传递源一致

chore: type and code optimize

---

src/components/result-page/result-page.tsx
src/components/result-page/tests/result-page.test.tsx

Detail see ⬇️
* https://github.com/ant-design/ant-design-mobile/pull/6354
* https://github.com/ant-design/ant-design-mobile/pull/6370

fix: result page enhancement

---

src/components/image-viewer/tests/image-viewer.test.tsx

image-viewer的用例会互相影响到，写的时候用了`only`没注意到这个= =，将两个用例合并到一起了。

fix(image-viewer): testcase

---

README.md
docs/components/icon/index.en.md
docs/components/icon/index.zh.md
docs/guide/quick-start.en.md
docs/guide/quick-start.zh.md
docs/guide/ssr.en.md
docs/guide/ssr.zh.md

This adds instructions for the [`bun`](https://github.com/oven-sh/bun) package manager alongside npm/yarn/pnpm.

doc: add installation instructions for bun

---

package.json

fix: license field is missing on npmjs.com #6392

---

src/components/action-sheet/action-sheet.tsx
src/components/auto-center/auto-center.tsx

style: arrow functions optimization

---

src/components/popover/popover-menu.tsx
src/components/popover/popover.tsx

mode 变量可以从defaultProps里设置，不用单独解构出来给默认值

chore: popover's code style optimization

---

src/components/action-sheet/tests/__snapshots__/action-sheet.test.tsx.snap
src/components/popup/popup.tsx

fix(Popup): set pointer-events none while animating

---

src/components/switch/switch.less

resolved: #6418
原因是 两个class 的 margin 数值不一致的问题
修复前的margin： 开状态 0 34px 0 10px。 关状态： 0 8px 0 33px
修复后的margin： 开状态 0 34px 0 8px。 关状态： 0 8px 0 34px

fix: for inconsistent switch width changes

---

src/components/cascader-view/demos/demo1.tsx

chore: cascader-view's demo type fix

---

src/components/cascader-view/cascader-view.tsx
src/components/cascader-view/tests/cascader-view.test.tsx
src/components/cascader-view/use-cascader-value-extend.tsx
src/components/cascader/cascader.tsx

fix: onChange in cascader-view unable to get value

---

src/global/global.less

resolve #6487
修复测量元素会导致浏览器打印多出一个空白页的问题。

fix: resolve where measuring elements would cause the browser to print an extra blank page

---

src/components/tabs/demos/demo1.tsx
src/components/tabs/tabs.tsx

Disable auto scroll to active when content changed. This API name or function still need to be check.
PS: need help with test case.

enhance(Tabs): Add experimental prop `autoScroll`

---

jest.config.js
src/components/action-sheet/tests/__snapshots__/action-sheet.test.tsx.snap
src/components/dialog/tests/dialog.test.tsx
src/components/image-viewer/tests/__snapshots__/image-viewer.test.tsx.snap
src/components/image-viewer/tests/image-viewer.test.tsx
src/components/mask/mask.tsx
src/components/modal/tests/modal.test.tsx
src/components/number-keyboard/number-keyboard.tsx
src/components/number-keyboard/tests/number-keyboard.test.tsx
src/components/virtual-input/tests/virtual-input.test.tsx
src/components/virtual-input/virtual-input.tsx
src/tests/testing.tsx

fix: #6486
1：禁用无障碍模式下，mask背景读取焦点  
2：修复虚拟键盘role为textbox  
3：修复数字键盘收起及删除为中文，更改按钮及数字role类型为button

feat: 优化数字键盘及虚拟输入框无障碍

---

package.json
pnpm-lock.yaml
src/components/picker-view/wheel.tsx

```
lodash/isEqual: Bundle size is 16.4 kB -> 6.4 kB (gzip)
react-fast-compare: Bundle size is 2.34 kB -> 925 B (gzip)
```
数据来源 <https://bundlejs.com/>
数据来源 <https://www.npmjs.com/package/react-fast-compare>
相比 lodash/isEqual, react-fast-compare 在体积和性能上都更有优势。

refactor: replace lodash/isEqual with react-fast-compare

---

package.json
pnpm-lock.yaml
src/components/cascader-view/use-cascader-value-extend.tsx

```
lodash/memoize: Bundle size is 6.58 kB -> 2.67 kB (gzip) 
nano-memoize: Bundle size is 1.12 kB -> 505 B (gzip)
```
数据来源 <https://bundlejs.com/>
```
lodash/memoize:  54,617,110 ops/sec
nano-memoize: 177,773,071 ops/sec
```
数据来源 <https://github.com/anywhichway/nano-memoize#benchmarks>
相比 lodash/memoize, nano-memoize 在体积和性能上都更有优势。

替换 lodash/memoize 为 nano-memoize

---

src/components/error-block/create-error-block.tsx
src/components/error-block/index.ts

Reproduce:
```shell
mkdir test-app
pnpm pnpm dlx create-umi@latest
cd test-app
```
```tsx
// copy to ./src/pages/index.tsx
import { defaultImage } from 'antd-mobile/es/components/error-block/images';
import { createErrorBlock } from 'antd-mobile';
export const CustomErrorBlock = createErrorBlock({
default: defaultImage,
empty: 'https://example.img',
});
export default function HomePage() {
return (
<div>
<CustomErrorBlock
title="test"
/>
</div>
);
}
```
```shell
pnpm build
```
`.adm-error-block` is not found in dist css
but pnpm dev is correct

fix: createErrorBlock will lost the style cause treeshaking

---

src/components/result-page/result-page.less

fix: result page dark theme

---

src/components/config-provider/config-provider.tsx
src/components/config-provider/tests/config-provider.test.tsx
src/index.ts

feat: export useConfig

---

src/components/tabs/index.en.md

Remove duplicate CSS variables in the English documentation of the Tabs component

docs:Remove duplicate CSS variables in the English documentation of the Tabs component

---

src/components/button/button.patch.less

src/components/button/button.patch.less
&-danger {
background-color: #00b578;
border-color: #00b578;
&.@{class-prefix-button}-fill-outline,
&.@{class-prefix-button}-fill-none {
color: #00b578;
}
}
修改为：
&-danger {
background-color: #ff3141;
border-color: #ff3141;
&.@{class-prefix-button}-fill-outline,
&.@{class-prefix-button}-fill-none {
color: #ff3141;
}
}

fix: button patch danger color

---

src/utils/with-stop-propagation.tsx

PropagationEvent 增加 touchstart 事件。
我遇到的业务场景: 
- `SwipeAction` 设置 `closeOnAction={false}`
-  其中某个 action 会拉起 Picker
-  期望 Picker 里面选择项目的时候不要 close 掉 Swiper

feat(utils): add touchstart event to PropagationEvent

---

src/components/button/button.tsx
src/components/result-page/result-page.tsx

函数的返回类型用 `void | Promise<void>` 就够了，再或一个 `unknown` 是不必要的，在某些 eslint 规则下会报错。

fix(Button): onClick type

---

src/components/swiper/index.zh.md
src/components/swiper/swiper.tsx
src/components/swiper/tests/swiper.test.tsx

when I want auto play from right to left or top to bottom, it's useful

feat: add scrollReverse props, autoplay reverse

---

src/locales/zh-CN.test.ts
src/locales/zh-CN.ts

有很多应用只支持 zh-CN，而由于 mergeLocale 的存在，导致 base （英文）也会被打包进去，徒增 3KB 的体积。本项目的维护者几乎都是 zh-CN 语言使用者，zh-CN 语言的完整性是有保证的，因此并不需要 mergeLocale 兜底，因此在 zh-CN 语言中去掉了 mergeLocale。

优化仅 zh-CN 语言应用的打包体积

---

.husky/commit-msg
.husky/pre-commit
package.json
pnpm-lock.yaml

现在用的 commitlint 和 pretty-quick 经常报错导致无法提交，建议改为更加成熟稳定的 lint-staged + 最新版的 commitlint, prettier
1. 使用 lint-staged 替换 pretty-quick，支持 `eslint --fix` 和 `prettier --write`
2. 更新 commitlint
3. 更新 prettier

chore: lint-staged and commitlint update

---

.eslintignore
.gitignore
.stylelintignore
.stylelintrc.js
.vscode/extensions.json
.vscode/settings.json
package.json
pnpm-lock.yaml

1. 启用 stylelint （支持 less）
2. 补全 .eslintignore, .prettierignore, .stylelintignore
3. .vscode/settings.json 纳入 git，方便贡献者保存时自动格式化代码，以符合规约

chore: stylelint, ignores, and vscode settings

---

src/components/input/input.tsx

input 的enterKeyHint 和autoFocus同时使用时，在ios中只能autoFocus，enterKeyHint无效
fix https://github.com/ant-design/ant-design-mobile/issues/6605

fix: input enterKeyHint

---

package.json

在 https://bundlephobia.com/package/antd-mobile 上，bundle 分析会提示 react-dom 没有找到
理论上任何会被 bundle 的依赖都应该在 dependencies 或者 peerDependencies 里。参考 antd 的 peerDependencies 就是有 react-dom 的，所以我在 antd-mobile 里也加上了。这样更加严谨一些，也能让 bundlephobia.com 之类的工具分析得更准确一些。

feat(deps): add react-dom peer deps

---

src/components/collapse/collapse.tsx
src/components/collapse/demos/demo1.tsx
src/utils/use-mutation-effect.tsx

Using MutationObserver to change the order in which height change animations are executed, I think the height animations should be triggered after DOM rendering is complete.
Currently, most modern browsers have implemented the MutationObserver API:
- Chrome: Supported from version 18 onwards
- Firefox: Supported from version 14 onwards
- Safari: Supported from version 6.1 onwards
- Opera: Supported from version 15 onwards
- Edge: Supported from version 79 onwards
- Internet Explorer: Never supported
resolve https://github.com/ant-design/ant-design-mobile/issues/6619

fix: collapse component expands blank issue #6619

---

src/components/card/card.less
src/components/card/card.patch.less
src/components/card/index.en.md
src/components/card/index.zh.md

| 属性 | 说明 | 默认值 | 全局变量 |
| --- | --- | --- | --- |
| --border-radius | 圆角大小 | `8px` | `--adm-card-border-radius` |
| --padding-inline | 水平内边距 | `12px` | `--adm-card-padding-inline` |
| --header-border-width | header 分割线宽度 | `0.5px` | `--adm-card-header-border-width` |
| --header-border-color | header 分割线颜色 | `var(--adm-color-border)` | `--adm-card-header-border-color` |
| --header-padding-block | header 垂直内边距 | `12px` | `--adm-card-header-padding-block` |
| --body-padding-block | body 垂直内边距 | `12px` | `--adm-card-body-padding-block` |

feat(card): css variables for border and padding

---

src/components/number-keyboard/number-keyboard.tsx
src/components/number-keyboard/tests/number-keyboard.test.tsx

IOS 里手指在边缘按下拖动时会导致 `touchend` 事件被吞，加一个兜底。如果发现有新的 `touchstart` 事件出来，那过去的循环清理则直接杀掉。

fix(NumberKeyboard): fix IOS missing the touch event when finger trigger the scale case

---

src/components/nav-bar/nav-bar.tsx
src/components/nav-bar/tests/nav-bar.test.tsx

fix: nav_bar backIcon attribute is compatible with backArrow attribute

---

src/components/calendar-picker-view/calendar-picker-view.tsx
src/components/calendar-picker-view/tests/__snapshots__/calendar-picker-view.test.tsx.snap
src/components/calendar-picker-view/tests/calendar-picker-view.test.tsx
src/components/calendar-picker/demos/demo1.tsx
src/components/config-provider/tests/__snapshots__/config-provider.test.tsx.snap

fix(CalendarPickerView): Fix empty header cell for some month

---

.github/workflows/check.yml
.github/workflows/compressed-size.yml
.github/workflows/doc-site.yml
.github/workflows/preview-build.yml
src/components/date-picker-view/demos/demo1.tsx
src/components/date-picker-view/demos/demo2.tsx
src/components/date-picker/date-picker-quarter-utils.ts
src/components/date-picker/date-picker-utils.ts
src/components/date-picker/demos/demo1.tsx
src/components/date-picker/tests/date-picker.test.tsx
src/components/picker-view/index.en.md
src/components/picker-view/index.zh.md
src/components/picker/index.en.md
src/components/picker/index.zh.md

Add quarter precision to DatePicker and DatePickerView, close #6510

feat(DatePicker): add quarter precision

---

src/components/calendar-picker-view/calendar-picker-view.en.md
src/components/calendar-picker-view/calendar-picker-view.tsx
src/components/calendar-picker-view/calendar-picker-view.zh.md
src/components/calendar-picker-view/tests/calendar-picker-view.test.tsx

CalendarPickerView 的 title 可以通过配置 false 来隐藏

feat(CalendarPickerView): title support boolean value to control whether to hide

---

src/components/card/card.less
src/components/card/card.patch.less
src/components/card/card.tsx
src/components/card/demos/demo1.tsx
src/components/card/index.en.md
src/components/card/index.zh.md
src/components/card/tests/card.test.tsx

- 增加 icon 属性，用于在 Card 标题左侧展示图标。
- 同时给 extra 也包裹一个带 className 的 div 方便控制间距和其他样式。
- 增加了一个 CSS 变量 `--adm-card-header-gap` 控制 icon，header，extra 之间的空隙。
- 单元测试的中文改成英文，让项目更加国际化。

feat(Card): icon prop

---

src/components/config-provider/tests/__snapshots__/config-provider.test.tsx.snap
src/components/image-uploader/image-uploader.tsx
src/components/image-uploader/tests/__snapshots__/image-uploader.test.tsx.snap

修复 ImageUploader 点击的 aria-hidden 报错 #6684

fix: remove aria-hidden

---

src/components/calendar-picker-view/tests/calendar-picker-view.test.tsx
src/components/config-provider/tests/__snapshots__/config-provider.test.tsx.snap
src/locales/kk-KZ.ts

close https://github.com/ant-design/ant-design-mobile/issues/6680

fix: kk-KZ locale

---

src/components/notice-bar/demos/demo1.tsx
src/components/notice-bar/index.en.md
src/components/notice-bar/index.zh.md
src/components/notice-bar/notice-bar.less
src/components/notice-bar/notice-bar.tsx
src/components/notice-bar/tests/__snapshots__/notice-bar.test.tsx.snap

增加 success 配色，shape 和 bordered 属性。

feat(notice-bar): shape and bordered prop

---

docs/components/components/Main/MainSection/index.local.less
docs/components/components/Main/MainSection/index.tsx
docs/components/components/Main/index.local.less
docs/components/components/Main/index.tsx
docs/components/home-page.tsx
package.json
pnpm-lock.yaml

docs: update deps to antd-mobile

---

src/components/tab-bar/demos/demo1.tsx
src/components/tab-bar/index.en.md
src/components/tab-bar/index.zh.md
src/components/tab-bar/tab-bar.tsx
src/components/tab-bar/tests/tab-bar.test.tsx

feat(TabBar): add onClick props to the TabBar.Item

---

src/components/search-bar/demos/demo1.tsx
src/components/search-bar/index.en.md
src/components/search-bar/index.zh.md
src/components/search-bar/search-bar.tsx

feat(SearchBar): support autoFocus

---

src/components/toast/methods.tsx
src/components/toast/tests/toast.test.tsx
src/utils/render-imperatively.tsx

fix(Toast): multiple toasts should show last one

---

.github/workflows/preview-build.yml
.github/workflows/preview-deploy.yml

修复 preview 报错的问题。https://github.com/ant-design/ant-design-mobile/pull/6739#issuecomment-2401357061

chore: Update preview-build.yml

---

src/components/calendar-picker-view/calendar-picker-view.en.md
src/components/calendar-picker-view/calendar-picker-view.tsx
src/components/calendar-picker-view/calendar-picker-view.zh.md
src/components/calendar-picker-view/tests/calendar-picker-view.test.tsx

增加 renderTop 和 renderBottom false 隐藏

feat(CalendarPickerView): add renderTop and renderBottom hide logic

---

docs/components/components/Main/MainSection/index.tsx
docs/components/components/Main/index.tsx

#6772 
使用 dumi link 包裹, 增加可访问性

docs: fix accessibility issues

---

src/components/passcode-input/index.en.md
src/components/passcode-input/index.zh.md
src/components/passcode-input/passcode-input.tsx
src/components/passcode-input/tests/passcode-input.test.tsx

#6736 
添加 inputMode 属性, 支持唤起原生英文键盘

feat(PasscodeInput): add inputMode props

---

src/components/popover/popover.tsx

autoUpdate 在 visible 变化时触发，visible 为 false 关闭 autoUpdate，visible 为 true 开启 autoUpdate。一方面可以优化运行时性能，另一方面可以解决默认 visible = false 时，元素未创建，导致 autoUpdate 不生效的问题。
Fix #6794

fix(Popover): autoUpdate not working when defaultVisible is false

---

src/components/config-provider/index.en.md
src/components/config-provider/index.zh.md

修正文档的参数名, 文档显示为 `icon`, 实际参数 `searchIcon`

docs: config provider searchBar param name

---

src/components/floating-panel/demos/demo4.tsx
src/components/floating-panel/floating-panel.less
src/components/floating-panel/floating-panel.tsx
src/components/floating-panel/index.en.md
src/components/floating-panel/index.zh.md

实现https://github.com/ant-design/ant-design-mobile/issues/6827

feat(FloatingPanel): support position attribute

---

src/components/ellipsis/demos/demo1.tsx
src/components/ellipsis/tests/ellipsis.test.tsx
src/components/ellipsis/useMeasure.tsx

fix #6792
**关于第一个文本省略字数错误的问题**
我分析了一下，其实是setWalkingIndexes设置的值最后被赋值导致
第一次调用正常计算，然后第二次由useResizeEffect触发，先setStatus然后setWalkingIndexes，进入useLayoutEffect计算PREPARE时，此时walkingIndexes的值还是上一次的值，然后进入MEASURE_WALKING，执行了一次diff就等于0，然后renderContent，这时setWalkingIndexes初始化设置的值生效了，因为state是STABLE_ELLIPSIS，然后初始化的值变成渲染了一半的文本，所以文本省略看起来算的有问题，实则被覆盖了。
最后定位发现，使用react-dom render挂载的App, requestAnimationFrame触发回调时状态更新不同步。
现在做法是把setWalkingIndexes放在setStatus(MEASURE_WALKING)前面，这样就不会有这个问题了，而且其实只有MEASURE_WALKING时才需要walkingIndexes的值。
**引申优化问题**
这里其实还有一个重复计算的问题，当fullMeasureRef大于rowMeasureHeight时才会计算，但是这个fullMeasureRef永远都是渲染content所有内容的高度，导致issue中debug截屏看到的一直是59>40。所以即使文本超出被截断了，下一次进入判断的时候也会重新命中，然后计算截断。
之前组件的实现就没有这个问题，因为下一次判断时container的内容就是已经处理过的，然后在取值container.offsetHeight，就会<=maxHeight，从而跳过判断。 …

fix(Ellipsis): Handle some post-update issues
