ant-design/ant-design-mobile

components/activity-indicator/style/index.less
=> fix z-index.

components/toast/demo/basic.tsx, components/toast/index.tsx, components/toast/style/index.tsx, rn-kitchen-sink/index.js
- rn toast 动画；
- fix toast 遮挡 back 问题；
=> Toast hidebar

components/search-bar/style/index.less
=> fix searchbar error

components/list/ListItem.web.tsx
=> fix list error #68

components/grid/style/index.less
=> fix grid icon #76

components/style/mixins.less
=> fix list 1px android #80

components/button/PropsType.tsx, components/list/ListBody.tsx, components/page-result/index.web.tsx, components/stepper/index.web.tsx, components/style/variables.tsx, components/table/index.web.tsx, components/tooltip/index.web.tsx
=> fix assign error #87

components/menu/SubMenu.web.tsx, components/menu/demo/basic.tsx, components/menu/index.tsx, components/menu/index.web.tsx, components/menu/propTypes.tsx, index.js, rn-kitchen-sink/demoList.js, typings/custom.d.ts
=> refactor menu web

components/activity-indicator/ActivityIndicatorPropTypes.tsx, components/activity-indicator/demo/basic.tsx, components/activity-indicator/index.tsx, components/activity-indicator/style/index.tsx
fix rn ActivityIndicator vertical center problem.
=> fix toast vertical centering.

components/checkbox/style/index.less, components/list/ListItem.web.tsx, components/list/demo/basic.md, components/list/demo/basic2.md, components/list/demo/memberdetail.md, components/list/demo/twoline.md, components/list/index.md, components/list/style/index.less, components/radio/style/index.less, components/style/mixins.less, components/style/variables.less, components/switch/style/index.less, site/mobile/template/KitchenSink/Page.less
=> List antui

components/toast/index.web.tsx
清除messageInstance，修复close后调用 .hide 方法报错的问题。
=> onClose时清除messageInstance

components/input-item/index.web.tsx, components/textarea-item/index.web.tsx
fix https://github.com/ant-design/ant-design-mobile/issues/105
=> fix input & textarea's input bug when set maxLength

components/progress/demo/basic.md, components/progress/demo/basic.tsx, components/progress/style/index.less
=> up progress style

components/grid/index.web.tsx, components/grid/style/index.less, components/style/themes/default.less
=> Grid antui

site/theme/static/home.less
:-)
fix page2 button cann't click
=> change page2 image width

components/flex/Flex.tsx, components/grid/demo/basic.tsx, components/grid/index.tsx, components/grid/style/index.tsx, index.js, rn-kitchen-sink/demoList.js
ref: https://github.com/ant-design/ant-design-mobile/issues/22
API 设计与 Web 版一致：
=>  feat: implement rn-grid

components/grid/index.web.tsx, components/grid/style/index.less
=> fix grid line style

components/grid/demo/carousel-border.md, components/grid/demo/custom.md, components/grid/demo/noborder.md, components/grid/index.md, components/grid/index.web.tsx, components/grid/style/index.less
Grid support new props :
* columnNum: custom grid's column number.
* carouselMaxRow: custom carousel grid's max row number.
* createItemElement: support for create custom grid item element.
=> grid support more props

site/bisheng.config.js, site/mobile/template/KitchenSink/index.jsx, site/theme/template/IconSet/CopyableIcon.jsx
Close: https://github.com/ant-design/ant-design-mobile/issues/225
=> site: PC site should not import antd-mobile's style

package.json, scripts/build-less-entry.js
=> Add less entry to dist/antd-mobile.less

components/segmented-control/index.web.tsx, components/style/themes/default.less, components/style/themes/default.tsx, components/swipe-action/demo/basic.md, components/tab-bar/demo/basic.md, components/tag/TagPropsType.tsx, components/tag/demo/basic.md, components/tag/demo/basic.tsx, components/tag/index.md, components/tag/index.tsx, components/tag/index.web.tsx, components/tag/style/index.less, components/tag/style/index.tsx, rn-kitchen-sink/index.js
- Tag 增加 small 属性；
- 修复 gitlab 设计师 review
=> fix: some gitlab issues

components/tab-bar/TabBarPropTypes.tsx, components/tab-bar/demo/basic.md, components/tab-bar/index.md, components/tab-bar/index.web.tsx, components/tab-bar/style/index.less
https://github.com/ant-design/ant-design-mobile/issues/296
=> feat: Tabbar supports hidden prop

components/input-item/index.web.tsx
fix inpunt-item parttern bug #334
=> fix inpunt-item parttern bug #334

components/tag/TagPropsType.tsx, components/tag/demo/basic.md, components/tag/demo/basic.tsx, components/tag/index.md, components/tag/index.tsx, components/tag/index.web.tsx, components/tag/style/index.less, components/tag/style/index.tsx, components/tag/style/index.web.tsx
=> feature: Tag => closable prop

components/wing-blank/style/index.less
=> 修改PrefixCls名称错误的问题

components/checkbox/Checkbox.tsx, components/checkbox/demo/basic.tsx, components/radio/Radio.tsx, components/radio/demo/basic.tsx
make Checkbox & Radio rn components controllable.
=> fix: Checkbox & Radio rn components controllable

components/badge/PropsType.tsx, components/badge/demo/basic.md, components/badge/index.md, components/badge/index.web.tsx, components/badge/style/index.less
=> Add Badge[hot]

components/popup/style/base.less, components/popup/style/index.less
fix webview pulldown cover pop content
=> fix: webview pulldown cover pop content

components/modal/demo/propmt.md, components/modal/index.md, components/modal/prompt.tsx
- prompt 支持 defaultValue， #497
- fix autofocus 键盘隐藏后偶尔报错
=> feature: modal prompt defaultvalue

components/search-bar/PropsType.tsx, components/search-bar/index.md, components/search-bar/index.tsx
- rn SearchBar 支持更多官方 TextInput 属性 #483 
- 将 styles 做为 prop，方便定制样式
=> support react native TextInput props for rn searchbar, #483

components/input-item/index.tsx, components/search-bar/index.tsx, components/textarea-item/PropsType.tsx, components/textarea-item/index.tsx
- InputItem, InputItem rn 版本支持更多 TextInput 属性
=> support rn TextInput props for InputItem, TextareaItem

components/action-sheet/index.md, components/button/index.md, components/checkbox/index.md, components/input-item/index.md, components/list/index.md, components/modal/index.md, components/nav-bar/index.md, components/notice-bar/index.md, components/picker/index.md, components/popover/index.md, components/radio/index.md, components/refresh-control/index.md, components/result/index.md, components/search-bar/index.md, components/steps/index.md, components/switch/index.md, components/tab-bar/index.md, components/textarea-item/index.md, components/toast/index.md, site/mobile/template/KitchenSink/Demo.jsx, site/mobile/template/KitchenSink/index.jsx
=> adapt to design com, gitlab issue 61

components/notice-bar/demo/basic.md, components/notice-bar/index.web.tsx, components/notice-bar/marquee.tsx
=> featrue: support marquee for NoticeBar, close #540

components/notice-bar/demo/basic.md, components/notice-bar/index.md, components/notice-bar/index.web.tsx, components/notice-bar/marquee.tsx
增加 marquee style 设置，方便留内边距，使得走马灯 刚开始走时 显得不突兀，效果更好
=> improve notice-bar marquee

README.md, README.zh-CN.md
=> add CDNJS version badge in README

site/bisheng.common.config.js, site/bisheng.kitchen.config.js, site/bisheng.site.config.js
=> chore: 抽取bisheng webpack的配置

components/toast/ToastContainer.tsx, components/toast/demo/basic.md, components/toast/demo/basic.tsx, components/toast/index.md, components/toast/index.tsx, components/toast/index.web.tsx, components/toast/style/index.less, components/toast/style/index.tsx
=> add mask prop for toast, close #715

components/textarea-item/index.web.tsx
=> fix(TextareaItem): inputCount should be 0 when content is empty

components/modal/Modal.web.tsx, components/modal/style/index.less, components/style/themes/default.less, components/switch/index.web.tsx, components/switch/style/index.less
- 来自 design 需求，modal & switch android web 版本
=> Switch & Modal style for android web

components/input-item/index.web.tsx, components/search-bar/index.web.tsx, components/textarea-item/index.web.tsx
=> add-scrollIntoViewIfNeeded-support

components/input-item/index.web.tsx, components/search-bar/index.web.tsx, components/textarea-item/index.web.tsx
=> fix tsx error for activeELement

components/input-item/style/index.less
=> fix input disabled style in iOS

components/textarea-item/style/index.less
=> fix disabled style for textareaItem in iOS

components/card/CardBody.tsx, components/card/CardBody.web.tsx, components/card/CardFooter.tsx, components/card/CardFooter.web.tsx, components/card/CardHeader.tsx, components/card/CardHeader.web.tsx, components/card/index.tsx, components/card/index.web.tsx
lint 报错，需要升级 antd-tools， https://github.com/ant-design/ant-design-mobile/issues/748
=> add restProps for card, close #737

components/tabs/demo/mutlitabs.md, components/tabs/index.web.tsx, components/tabs/style/index.less
=> feat(tabs): viewport only show the relative 5 tabs

components/checkbox/Checkbox.tsx
=> fix(Checkbox): fix RN checkbox uncontrolled logic. close #784

components/button/index.web.tsx, components/list/ListItem.web.tsx, components/list/PropsType.tsx, components/list/demo/basic.md, components/list/index.md, components/popover/Item.web.tsx, components/segmented-control/index.web.tsx
=> fix(button): bind event on touchable container, not inner component

components/input-item/style/index.less, components/swipe-action/demo/basic.md, components/textarea-item/style/index.less
=> fix border for textarea-item

components/textarea-item/style/index.less
=> adjust textarea style

components/picker/PropsType.tsx, components/picker/index.md
fix Picker ts props error
add whitespace
=> Picker缺少disabled声明

components/_util/getLocale.tsx, components/date-picker/index.tsx, components/date-picker/index.web.tsx, components/date-picker/locale/en_US.tsx, components/date-picker/locale/zh_CN.tsx, components/date-picker/utils.tsx, components/index.web.tsx, components/locale-provider/demo/basic.md, components/locale-provider/en_US.tsx, components/locale-provider/index.md, components/locale-provider/index.tsx, components/pagination/index.web.tsx, components/pagination/locale/en_US.tsx, components/pagination/locale/zh_CN.tsx, index.js
=> feat: add LocaelProvider, now support Pagination, DatePicker. close #500

components/checkbox/demo/basic.md
=> rewrite CheckBox demos to es6 component

components/carousel/demo/basic.md
=> rewrite Carousel demos to es6 component

components/button/demo/basic.md
=> rewrite Button demos to es6 component

components/accordion/demo/accordion.md, components/accordion/demo/basic.md
rewrite Accordion demos to es6 component
#824
=> rewrite Accordion demos to es6 component

components/activity-indicator/demo/basic.md
rewrite ActivityIndicator demos to es6 component
#824
=> rewrite ActivityIndicator demos to es6 component

components/action-sheet/demo/basic.md, components/action-sheet/demo/basic.tsx
rewrite ActionSheet demos to es6 component
#824
=> rewrite ActionSheet demos to es6 component

components/accordion/index.tsx, components/action-sheet/AndroidContainer.tsx, components/badge/demo/basic.md, components/button/demo/complex.md, components/date-picker/demo/basic.md, components/drawer/demo/basic.md, components/drawer/demo/dock.md, components/flex/demo/basic.md, components/flex/demo/basic.tsx, components/grid/demo/basic.md, components/image-picker/demo/basic.md, components/input-item/demo/basic.md, components/list-view/demo/basic-body.md, components/list-view/demo/basic-row.tsx, components/list-view/demo/basic-sticky.md, components/list-view/demo/basic.tsx, components/list-view/demo/idxed-sticky.md, components/list-view/demo/idxed.md, components/list/demo/basic.md, components/list/demo/form.md
=> refactor: use class syntax, remove mixin

components/icon/index.md, svg.config.js
=> docs: update icon doc for windows. 

components/date-picker/PropsType.tsx, components/date-picker/index.md
=> fix DatePicker tsx err

components/white-space/demo/basic.md
=> update white-space demo2es6

components/button/PropsType.tsx, components/button/demo/basic.tsx, components/button/index.tsx, components/button/style/index.tsx
- 原来的写法，没办法做单个 button 样式的自定义
- disabled 直接写在 touchable 上；
=> refactor: rn button, for custom single component style, #ref 698

components/date-picker/index.tsx, components/locale-provider/demo/basic.tsx, components/locale-provider/index.md, components/locale-provider/index.tsx, components/pagination/index.tsx, rn-kitchen-sink/demoList.js
RN 国际化，方案和 web 一致，补全 demo，修正引用错误
=> feature: support rn locale, as same as web

components/list/ListItem.tsx, components/list/index.md, components/list/index.tsx, components/list/style/index.tsx
- 整理 rn list 样式，支持自定义 list 样式；
- 去除 rn 没有用到的 error 属性；
=> refactor rn list style, ref #560

components/date-picker/locale/ru_RU.tsx, components/locale-provider/ru_RU.tsx, components/pagination/locale/ru_RU.tsx
=> Russian locale

components/modal/Modal.tsx, components/modal/Modal.web.tsx, components/modal/OperationContainer.tsx, components/modal/PropsType.tsx, components/modal/demo/basic.tsx, components/modal/demo/operation.md, components/modal/index.tsx, components/modal/index.web.tsx, components/modal/operation.tsx, components/modal/operation.web.tsx, components/modal/style/Dialog.less, components/modal/style/index.tsx
=> Modal.operation

components/tag/demo/basic.md, components/tag/demo/basic.tsx, components/tag/index.en-US.md, components/tag/index.zh-CN.md
=> Translation for Tag

components/tabs/index.web.tsx
=> Tabs miss onTabClick property

components/steps/demo/basic.md, components/steps/demo/basic.tsx, components/steps/demo/horizontal.md, components/steps/index.en-US.md, components/steps/index.zh-CN.md
=> Translation for steps

components/drawer/demo/basic.md, components/drawer/demo/dock.md, components/drawer/index.en-US.md, components/drawer/index.zh-CN.md
=> Translate Drawer

.jest.json
=> chore: fix rn coverage config

components/image-picker/index.web.tsx
=> fix(ImagePicker): image orientation

components/search-bar/index.tsx
close #957.
@silentcloud RN动画一般怎么做，也用css动画？这里还没加动画
=> fix(RN): SearchBar auto show cancel button. 

components/menu/demo/basic.md, components/menu/index.en-US.md
=> Translate Menu doc

components/badge/index.en-US.md, components/badge/index.zh-CN.md
ref #329
---
PS: There is no uploader.
=> Translate badge

components/menu/__tests__/__snapshots__/index.test.web.js.snap, components/menu/__tests__/index.test.web.js
=> Add Menu tests

components/modal/__tests__/__snapshots__/demo.test.web.js.snap, components/modal/alert.web.tsx, components/modal/demo/alert.md, components/modal/index.en-US.md, components/modal/index.zh-CN.md, components/modal/operation.web.tsx, components/modal/prompt.web.tsx
=> feat(Modal): add close api

components/badge/demo/basic.md
=> Add translation of Badge demos

components/steps/StepsItem.tsx, components/steps/__tests__/__snapshots__/demo.test.js.snap, components/steps/demo/basic.tsx
=> fix(RN): steps title & desc accept ReactNative Component

components/list/ListItem.web.tsx, components/list/PropsType.tsx, components/list/__tests__/__snapshots__/demo.test.web.js.snap, components/list/demo/basic.md, components/list/index.en-US.md, components/list/index.zh-CN.md, components/modal/Modal.web.tsx, components/modal/PropsType.tsx, components/modal/__tests__/__snapshots__/demo.test.web.js.snap, components/modal/demo/basic.md, components/modal/index.en-US.md, components/modal/index.zh-CN.md, components/switch/PropsType.tsx, components/switch/__tests__/__snapshots__/demo.test.web.js.snap, components/switch/demo/basic.md, components/switch/index.en-US.md, components/switch/index.web.tsx, components/switch/index.zh-CN.md
=> add styleMode api

components/tabs/PropsType.tsx, components/tabs/index.web.tsx
* static member `TabPane`
* properties `pageSize`, `speed`, `tabBarhammerOptions`
#667 
=> fix tabs tsx

site/desktop/src/en-US.js, site/desktop/src/index.js, site/desktop/src/template/Layout/Header.jsx, site/desktop/src/zh-CN.js
=> add design link, fix #986

components/search-bar/PropsType.tsx
=> fix seach bar tsx

components/modal/Modal.web.tsx
move navigator variable outside of render
fix #1079
=> fix ssr modal navigator

components/image-picker/__tests__/__snapshots__/demo.test.web.js.snap, components/image-picker/index.web.tsx, components/image-picker/style/index.less
https://github.com/ant-design/ant-design-mobile/pull/1078
https://github.com/ant-design/ant-design-mobile/pull/1111
=> refactor(ImagePicker): remove clientWidth to support ssr

components/progress/PropsType.tsx, components/progress/index.web.tsx
=> add progress className prop

components/input-item/__tests__/__snapshots__/demo.test.web.js.snap, components/input-item/index.web.tsx
=> fix #1073 && autoFocus

components/carousel/__tests__/__snapshots__/demo.test.js.snap, components/carousel/demo/basic.md, components/carousel/demo/basic.tsx, components/carousel/index.en-US.md, components/carousel/index.zh-CN.md
demo 里那段中文我去掉了，有对应 issue 链接就可以了，里面有对应解决方案；
=> carousel translation, ref #329

components/refresh-control/index.web.tsx
This pr make RefreshControl support SSR.
=> check window before get dpr

components/input-item/PropsType.tsx
=> input item placeholder prop is optional

components/card/CardBody.tsx, components/card/CardBody.web.tsx, components/card/CardFooter.tsx, components/card/CardFooter.web.tsx, components/card/CardHeader.tsx, components/card/CardHeader.web.tsx, components/card/PropsType.tsx, components/card/index.tsx, components/card/index.web.tsx
change styles prop optional
fix #1221 
=> move card types into a single file

components/grid/__tests__/__snapshots__/demo.test.web.js.snap, components/grid/demo/basic.md, components/grid/index.en-US.md
=> translate grid

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, package.json
=> release 1.1.1

components/carousel/PropsType.tsx, components/carousel/__tests__/__snapshots__/demo.test.js.snap, components/carousel/index.en-US.md, components/carousel/index.tsx, components/carousel/index.zh-CN.md, components/grid/__tests__/__snapshots__/demo.test.js.snap
ref #1146
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1268)
=> Split carousel pagination

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1271)
=> feat: bump 1.1.2

components/popup/demo/basic.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1281)
=> fix typo in popup demo

components/list/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1294)
=> fix bug renderFooter

components/checkbox/CheckboxItem.tsx, components/checkbox/PropsType.tsx, components/checkbox/__tests__/__snapshots__/demo.test.js.snap, components/list/PropsType.tsx
`line`这个字段没有用到
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1295)
=> Remove checkbox redundant props

components/pagination/__tests__/__snapshots__/demo.test.web.js.snap, components/pagination/demo/basic.md, components/pagination/index.en-US.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1291)
=> pagination translation, ref #329

components/menu/SubMenu.web.tsx, components/menu/index.web.tsx
本身编译没有问题，webpack设置好了
typescript 那边没有相关配置
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1296)
=> make tsx happy

components/input-item/__tests__/__snapshots__/demo.test.web.js.snap, components/input-item/demo/basic.md, components/input-item/index.en-US.md, components/input-item/index.zh-CN.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1297)
=> input-item translation, ref #329

components/modal/Modal.web.tsx
because rc-dialog won't render until visible
this pr close #1305 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1307)
=> defer check platform until visible is true

components/input-item/__tests__/__snapshots__/demo.test.web.js.snap, components/input-item/demo/basic.md, components/input-item/index.en-US.md, components/textarea-item/__tests__/__snapshots__/demo.test.web.js.snap, components/textarea-item/demo/basic.md, components/textarea-item/index.en-US.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1314)
=> textarea-item translation, ref #329

components/flex/Flex.tsx, components/flex/Flex.web.tsx, components/flex/FlexItem.tsx, components/flex/FlexItem.web.tsx, components/flex/PropsType.tsx
#1212
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1325)
=> refactor Flex tsx

components/pagination/index.tsx, components/pagination/index.web.tsx
* `inline` only web
* `../button` -> `../button/index.web` make tsx happy
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1326)
=> fix Pagination bug

components/tabs/Tabs.tsx
=> fix(Tabs): rn swipeable

components/popover/style/index.less
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1372)
=> optimize popover style

components/input-item/Input.tsx, components/input-item/Input.web.tsx, components/input-item/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1381)
=> split textinput, close #1379

.stylelintrc, components/drawer/PropsType.tsx, components/drawer/demo/basic.tsx, components/drawer/index.en-US.md, components/drawer/index.tsx, components/drawer/index.zh-CN.md, package.json, rn-kitchen-sink/components/Home.js, rn-kitchen-sink/components/RnIndex.js, rn-kitchen-sink/components/WebIndex.js, rn-kitchen-sink/index.js
- 重构 drawer demo
- 替换为 react-navigation
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1384)
=> refactor demo app with react-navigation, ref #1332

docs/react/use-with-create-react-app.en-US.md, docs/react/use-with-create-react-app.zh-CN.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1395)
=> add doc for create-react(-native)-app, ref #1362

components/grid/__tests__/__snapshots__/demo.test.web.js.snap, components/grid/index.web.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1398)
=> fix(Grid): carousel mode should fill blank item too.

site/desktop/src/en-US.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1404)
=> Grammar and spelling fixes :)

components/carousel/PropsType.tsx, components/carousel/__tests__/__snapshots__/demo.test.js.snap, components/carousel/index.en-US.md, components/carousel/index.tsx, components/carousel/index.web.tsx, components/carousel/index.zh-CN.md, components/carousel/style/index.tsx, components/grid/__tests__/__snapshots__/demo.test.js.snap
- 增加  `dotStyle` & `dotActiveStyle` 属性
- 移除 rn-carousel pagination 依赖，减少大小 （表现，api 使用都没变）
可以发小版本，给 tiny 用
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1425)
=> enhance carousel, add dotStyle & dotActiveStyle, remove rn pagination

components/range/PropsType.tsx, components/slider/PropsType.tsx
更新 API 时，应该同时更新:
* TypeScript definition
* API docs
* demo
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1439)
=> fix: fix TS definition for Slider

components/switch/__tests__/__snapshots__/demo.test.js.snap, components/switch/__tests__/__snapshots__/demo.test.web.js.snap, components/switch/demo/basic.md, components/switch/demo/basic.tsx, components/switch/index.en-US.md, components/switch/index.zh-CN.md, components/toast/__tests__/__snapshots__/demo.test.js.snap, components/toast/__tests__/__snapshots__/demo.test.web.js.snap, components/toast/demo/basic.md, components/toast/demo/basic.tsx, components/toast/index.en-US.md
ref #329 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1436)
=> Translate Switch & Toast

components/flex/type.tsx, components/list/type.tsx
fix item tsx
#1376
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1454)
=> fix item tsx

components/progress/demo/basic.md, components/progress/index.en-US.md, components/progress/index.zh-CN.md
#329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1459)
=> English doc of progress

components/input-item/CustomInput.web.tsx, components/input-item/style/CustomKeyboard.less
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1463)
=> Fix money input

components/result/demo/basic.md, components/result/index.en-US.md, components/result/index.zh-CN.md
#329
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1461)
=> Translate Result documentation

components/slider/__tests__/__snapshots__/demo.test.web.js.snap, components/slider/demo/basic.md, components/slider/index.en-US.md, components/slider/index.zh-CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1485)
=> slider translation, ref #329

components/input-item/CustomInput.web.tsx, components/input-item/CustomKeyboard.web.tsx, components/input-item/PropsType.tsx, components/input-item/__tests__/__snapshots__/demo.test.web.js.snap, components/input-item/demo/money.md, components/input-item/index.en-US.md, components/input-item/index.web.tsx, components/input-item/index.zh-CN.md, components/input-item/locale/en_US.tsx, components/input-item/locale/ru_RU.tsx, components/input-item/locale/zh_CN.tsx, components/locale-provider/__tests__/__snapshots__/demo.test.web.js.snap, components/locale-provider/demo/basic.md, components/locale-provider/en_US.tsx, components/locale-provider/index.tsx, components/locale-provider/ru_RU.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1476)
=> fix #1475 support custom keyboard confirm label

components/modal/Modal.tsx, components/modal/Modal.web.tsx, components/modal/PropsType.tsx, components/modal/index.web.tsx, components/modal/prompt.web.tsx
alert/prompt/operation
RN暂时没动，函数签名有区别，并且我完全没接触过RN。
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1443)
=> [TS] Modal static method type definitions for web

components/segmented-control/__tests__/__snapshots__/demo.test.web.js.snap, components/segmented-control/index.web.tsx
ref #1304 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1374)
=> fix SegmentedControl for compat preact

components/image-picker/index.web.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1487)
=>  fix  ImagePicker for compat preact fix #1486

package.json
ref https://github.com/benjycui/omit.js
ref https://github.com/ant-design/ant-design-mobile/commit/586184ea873849c47f1c8bd7f152c5949a107e1b
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1506)
=> refactor: upgrade omit.js, which removed object-assign deps.

components/tag/__tests__/__snapshots__/index.test.js.snap, components/tag/__tests__/__snapshots__/index.test.web.js.snap, components/tag/__tests__/index.test.js, components/tag/__tests__/index.test.web.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1516)
=> add test for tag, ref #1274

components/carousel/__tests__/__snapshots__/index.test.js.snap, components/carousel/__tests__/__snapshots__/index.test.web.js.snap, components/carousel/__tests__/index.test.js, components/carousel/__tests__/index.test.web.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1522)
=> add test for carousel, ref #1274

components/flex/index.en-US.md, components/flex/index.zh-CN.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1535)
=> fix-flex #1532

components/segmented-control/index.en-US.md, components/segmented-control/index.zh-CN.md
Use cannot find this util read our source code.
`e.nativeEvent` strange name...
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1561)
=> add doc for SegmentedControl onChange event

components/list/__tests__/__snapshots__/demo.test.web.js.snap, components/list/demo/basic.md, components/list/demo/form.md, components/list/index.en-US.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1525)
=> list transilation, ref #329

components/tabs/__tests__/__snapshots__/demo.test.web.js.snap, components/tabs/demo/basic.md, components/tabs/demo/mutlitabs.md, components/tabs/demo/noanim.md, components/tabs/index.en-US.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1527)
=> tabs translation, ref #329

docs/react/use-with-create-react-app.en-US.md, docs/react/use-with-create-react-app.zh-CN.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1611)
=> docs: create-react-app doc use diff

components/tabs/__tests__/__snapshots__/demo.test.web.js.snap, components/tabs/demo/basic.md, components/tabs/style/index.less
#1536  https://github.com/ant-design/ant-design-mobile/pull/1568 https://github.com/ant-design/ant-design-mobile/pull/1601
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1604)
=> Tabs support badge

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/action-sheet/AndroidContainer.native.tsx, components/action-sheet/demo/basic.native.tsx, components/action-sheet/index.en-US.md, components/action-sheet/index.native.tsx, components/action-sheet/index.zh-CN.md
close #1577 #1110
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1634)
=> refactor: rn ActionSheet.showShareActionSheetWithOptions

components/checkbox/PropsType.tsx
#1649 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1652)
=> doc(Checkbox): fix checkbox interface

components/notice-bar/Marquee.native.tsx, components/notice-bar/Marquee.tsx, components/notice-bar/PropsType.tsx, components/notice-bar/__tests__/__snapshots__/demo.test.native.js.snap, components/notice-bar/__tests__/__snapshots__/index.test.native.js.snap, components/notice-bar/demo/basic.native.tsx, components/notice-bar/index.en-US.md, components/notice-bar/index.native.tsx, components/notice-bar/index.zh-CN.md, components/notice-bar/style/index.native.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1644)
=> feat: support marquee for rn-notice-bar, ref #1302

components/textarea-item/index.web.tsx
close #1663 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1670)
=> Fix emoji count

components/style/mixins.less
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1682)
=> add hairline mixin

components/accordion/demo/accordion.md, components/accordion/demo/basic.md, components/accordion/style/index.less, components/action-sheet/style/index.less, components/grid/style/index.less, components/input-item/style/index.less, components/menu/style/index.less, components/picker/style/index.less, components/result/style/index.less, components/style/mixins.less, components/textarea-item/style/index.less
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1710)
=> refactor: rewrite all border

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/button/PropsType.tsx, components/button/index.en-US.md, components/button/index.tsx, components/button/index.zh-CN.md, components/button/style/index.less, components/style/themes/default.less, components/style/themes/default.native.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1718)
=> Button remove across，rewrite border with hairline mixin

development.en-US.md, development.zh-CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1735)
=> fix: links

components/style/themes/default.native.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1737)
=> fix: Wiki link in default.native.tsx

components/notice-bar/PropsType.tsx, components/notice-bar/index.native.tsx, components/notice-bar/index.tsx
#1779
fix #1779
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1781)
=> refactor(NoticeBar): type definitions #1779

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/carousel/index.native.tsx, components/input-item/CustomInput.tsx, components/input-item/Input.native.tsx, components/input-item/Input.tsx, components/input-item/index.tsx, components/list-view/Indexed.tsx, components/list-view/index.tsx, components/notice-bar/Marquee.tsx, components/popover/demo/basic.native.tsx, components/popover/index.native.tsx, components/progress/index.tsx, components/search-bar/index.native.tsx, components/search-bar/index.tsx, components/stepper/index.tsx, components/steps/index.tsx, components/textarea-item/index.tsx, docs/react/upgrade-notes.en-US.md, docs/react/upgrade-notes.zh-CN.md, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1776)
=> refactor: use ref func to replace ref string, close #1354

components/input-item/CustomInput.tsx, components/input-item/Input.tsx, components/input-item/__tests__/__snapshots__/demo.test.js.snap, components/input-item/demo/basic.md, components/input-item/demo/money.md, components/input-item/index.en-US.md, components/input-item/index.tsx, components/input-item/index.zh-CN.md
close #1775 close #1243 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1789)
=> feat(InputItem): remove focused, autoFocus. add focus method. clear not blur

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/input-item/index.en-US.md, components/input-item/index.native.tsx, components/input-item/index.zh-CN.md, components/textarea-item/demo/basic.md, components/textarea-item/index.en-US.md, components/textarea-item/index.tsx, components/textarea-item/index.zh-CN.md
简化大量代码，使用也更简便。
close #1514
ref https://github.com/ant-design/ant-design-mobile/pull/1789
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1790)
=> feat(TextareaItem): remove focused, autoFocus. Add focus().

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/grid/PropsType.tsx, components/grid/__tests__/__snapshots__/demo.test.js.snap, components/grid/demo/basic.md, components/grid/index.en-US.md, components/grid/index.tsx, components/grid/index.zh-CN.md, components/grid/style/index.less, components/icon/__tests__/__snapshots__/demo.test.js.snap
- Grid default change to height fixed. 
- Add square api to compatible with 1.x square mode.
close #1352
- - -
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1803)
=> feat(Grid): add `squre=false` to support auto height

components/calendar/locale/pt_BR.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1844)
=> add locale pt_BR on component calendar

components/notice-bar/Marquee.native.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1846)
=> fix(marquee): style prop should be TextStyle

components/drawer/PropsType.tsx, components/drawer/index.native.tsx, components/drawer/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1836)
=> refactor(drawer): type definitions

components/input-item/CustomInput.tsx, components/input-item/PropsType.tsx, components/input-item/demo/money.md, components/input-item/index.en-US.md, components/input-item/index.tsx, components/input-item/index.zh-CN.md, components/input-item/style/custom-keyboard.less
close #1755 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1850)
=> feat(InputItem): money keyboard support align left

components/list/index.native.tsx
Should import from Native file.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1864)
=> fix(List.Item): wrong imports

docs/react/introduce.zh-CN.md
pr 审核中，[请查收](https://github.com/ant-design/ant-design-mobile/pull/1881/commits/c83faeadd17e94e41a200b15172ce85c591c391c)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1882)
=> Add doc about how customize theme with webpack

docs/react/introduce.en-US.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1890)
=> Change link about how customize theme with webpack

docs/react/theme-config.en-US.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1887)
=> theme config en version

components/input-item/CustomInput.tsx, components/input-item/__tests__/demo.test.js, components/locale-provider/__tests__/demo.test.js, package.json, site/kitchen/src/template/KitchenSink/Demo.jsx, tests/setup.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1916)
=> fix: input-item react@16 compatible, ref #1876

components/date-picker/index.native.tsx, components/date-picker/index.tsx, components/date-picker/locale/en_US.tsx, components/date-picker/locale/ru_RU.tsx, components/date-picker/locale/zh_CN.tsx, components/locale-provider/__tests__/__snapshots__/demo.test.js.snap, components/locale-provider/__tests__/__snapshots__/demo.test.native.js.snap, components/locale-provider/demo/basic.md, components/locale-provider/en_US.tsx, components/picker/AbstractPicker.tsx, components/picker/__tests__/__snapshots__/demo.test.js.snap, components/picker/locale/en_US.tsx, components/picker/locale/zh_CN.tsx, components/search-bar/__tests__/__snapshots__/demo.test.native.js.snap, components/search-bar/__tests__/__snapshots__/index.test.native.js.snap, components/search-bar/index.native.tsx, components/search-bar/index.tsx, components/search-bar/locale/en_US.tsx, components/search-bar/locale/zh_CN.tsx, components/tab-bar/__tests__/__snapshots__/demo.test.native.js.snap, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1923)
=> feat: enhancement for locale, close #1833

components/steps/__tests__/__snapshots__/demo.test.js.snap, components/steps/style/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1933)
=> 修复Steps组件连接线无法自适应高度问题

components/input-item/index.web.tsx, components/search-bar/index.web.tsx, components/textarea-item/index.web.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1956)
=> fix input-item textarea-item search-bar bug #1955

components/date-picker/PropsType.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1957)
=> chore(DatePicker): add missing props

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/input-item/index.en-US.md, components/search-bar/__tests__/__snapshots__/demo.test.js.snap, components/search-bar/demo/basic.md, components/search-bar/index.en-US.md, components/search-bar/index.tsx, components/search-bar/index.zh-CN.md, components/swipe-action/__tests__/__snapshots__/demo.test.js.snap
https://github.com/ant-design/ant-design-mobile/issues/1243
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/1963)
=> feat(SearchBar): replace autoFocus, focused with instance.focus()

.github/CONTRIBUTING.md
The space cause the link not rendered correctly.
Just typo fix.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2080)
=> remove extra space

components/input-item/CustomInput.tsx, components/input-item/Portal.tsx
#2065
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2074)
=> fix: multiple keyboard dom in react@16

components/textarea-item/demo/basic.md, components/textarea-item/index.en-US.md, components/textarea-item/index.tsx, components/textarea-item/index.zh-CN.md
close #2131
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2133)
=> fix: textareaitem clear when uncontrolled

components/image-picker/PropsType.tsx, components/image-picker/__tests__/__snapshots__/demo.test.js.snap, components/image-picker/demo/basic.md, components/image-picker/index.en-US.md, components/image-picker/index.tsx, components/image-picker/index.zh-CN.md
close #2017
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2134)
=> feat(ImagePicker): support multiple

components/list/style/index.less
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2145)
=> fix: remove nouse style

components/textarea-item/index.en-US.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2240)
=> Update TextareaItem docs: autoHeight description and others

components/input-item/CustomInput.tsx, components/tabs/__tests__/__snapshots__/dome.test.native.js.snap
Fix https://github.com/ant-design/ant-design-mobile/issues/2207
Fix https://github.com/ant-design/ant-design-mobile/issues/2175
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2220)
=> fix(InputItem): money keyboard throw error when page restore

components/search-bar/index.tsx, components/textarea-item/index.tsx
https://github.com/ant-design/ant-design-mobile/issues/2104
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2289)
=> fix: remove scrollIntoViewIfNeedeed

components/textarea-item/style/index.native.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2260)
=> fix marginLeft

components/modal/index.en-US.md, components/modal/index.zh-CN.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2314)
=> fixed few typo errors in document, "Wen" should be "web"

docs/react/introduce.en-US.md, docs/react/introduce.zh-CN.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2328)
=> Add notes about working with react-native

components/modal/AlertContainer.native.tsx
close  
#2089 
https://github.com/ant-design/ant-design-mobile/pull/2094
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2347)
=> fix: modal.alert content align=center

.jest.js, components/grid/__tests__/__snapshots__/demo.test.js.snap, package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2337)
=> fix: Fix all failed test

README.zh-CN.md
ref #2386 #2384 #1944 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2390)
=> docs(readme): add cn mirror link

components/card/PropsType.tsx, components/date-picker/PropsType.tsx, components/modal/AlertContainer.native.tsx, components/modal/PromptContainer.native.tsx, components/modal/PropsType.tsx, components/modal/alert.native.tsx, components/modal/alert.tsx, components/modal/prompt.native.tsx, components/modal/prompt.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2401)
=> fix: type definitions #2398

package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2509)
=> fix: upgrade rmc-feedback to 2.x

components/icon/index.en-US.md, components/list/demo/form.md
close: #2522
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2523)
=> docs: fix typo

components/tab-bar/__tests__/__snapshots__/demo.test.js.snap, components/tab-bar/demo/listview-tabbar.md, site/bisheng.common.config.js
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2527)
=> demo: add use of listview component nested with tabbar, close #2455

package.json
See [fix PR](https://github.com/react-component/collapse/pull/86)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2530)
=> fix(Accordion): make aria-expanded prop valid in preact, close #2491

components/modal/style/Dialog.less
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2500)
=> fix: fix Modal issue with animated Tabs in the x5 kernel browser 

components/menu/style/index.less, components/style/themes/default.less
add theme var: @menu-multi-select-btns-height
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2424)
=> add theme var: @menu-multi-select-btns-height

components/button/index.native.tsx, components/input-item/Input.native.tsx, components/input-item/index.en-US.md, components/input-item/index.native.tsx, components/input-item/index.zh-CN.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2408)
=> feat: add focus method #2381

components/date-picker-view/locale/ru_RU.tsx, components/date-picker-view/locale/sv_SE.tsx, package.json
add locale for date-picker-view
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2555)
=> feat(date-picker-view): add locale for date-picker-view

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, package.json
bump 2.1.10
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2570)
=> bump 2.1.10

components/input-item/index.tsx
Ref https://reactjs.org/warnings/unknown-prop.html
Fixed: #2565
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2577)
=> Fix(InputItem): remove  the unknown-prop warning

components/pull-to-refresh/__tests__/__snapshots__/demo.test.js.snap, components/pull-to-refresh/demo/basic.md, components/pull-to-refresh/index.en-US.md, components/pull-to-refresh/index.zh-CN.md
update damping prop api
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2594)
=> demo(pull-to-refresh): update damping prop api, close #2542

components/tab-bar/demo/listview-tabbar.md, components/tab-bar/index.en-US.md, components/tab-bar/index.tsx, components/tab-bar/index.zh-CN.md
add prerenderingSiblingsNumber
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2607)
=> Feat/add prerenderingSiblingsNumber

components/_util/exenv.tsx, components/input-item/CustomInput.tsx, components/input-item/CustomKeyboard.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2623)
=> feat: add ssr support

components/_util/types.tsx, components/badge/index.tsx, components/button/index.tsx, components/card/CardHeader.tsx, components/carousel/index.tsx, components/checkbox/CheckboxItem.tsx, components/flex/Flex.tsx, components/grid/index.tsx, components/input-item/CustomKeyboard.tsx, components/input-item/index.tsx, components/list-view/handleProps.tsx, components/list/ListItem.tsx, components/list/index.tsx, components/modal/Modal.tsx, components/nav-bar/index.tsx, components/notice-bar/index.tsx, components/picker/AbstractPicker.tsx, components/popover/Item.tsx, components/radio/RadioItem.tsx, components/switch/index.tsx, components/textarea-item/index.tsx, package.json
fix tsd error in rc-gesture, rc-swipeout
- https://github.com/react-component/gesture/commit/89e761b7d2def09e37a91bca4f14547cf2e441ba
- https://github.com/react-component/swipeout/commit/fd1e7b59003a244c7b9cf8b6a036b57f9d428a27
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2638)
=> feat: upgrad to ts@2.9, antd-tools@5

components/picker/style/index.less, components/toast/style/index.less
Ref: https://github.com/ant-design/ant-design-mobile/issues/2625
Ref: https://github.com/ant-design/ant-design-mobile/issues/2596
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2653)
=> Fix(Picker): add translateZ on wrap and mask

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, package.json
publish/2.2.1
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2676)
=> bump 2.2.1

components/locale-provider/sv_SE.tsx
close: https://github.com/ant-design/ant-design-mobile/issues/2678
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2692)
=> fix: case-sensitive

components/flex/style/index.less
close: https://github.com/ant-design/ant-design-mobile/issues/2683
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2711)
=> Fix: Flex margin when direction=column

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2716)
=> chore:add 2.2.2 changelog

components/tab-bar/__tests__/__snapshots__/demo.test.js.snap, components/tabs/__tests__/__snapshots__/demo.test.js.snap
update tabs & tab-bar snap-shot
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2717)
=> feat:update snapshot

components/picker/PropsType.tsx, components/picker/index.en-US.md, components/picker/index.zh-CN.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2720)
=> PickData label support ReactNode

components/picker/AbstractPicker.tsx, components/picker/PropsType.tsx, components/picker/__tests__/__snapshots__/demo.test.js.snap, components/picker/demo/basic.md, components/picker/index.en-US.md, components/picker/index.tsx, components/picker/index.zh-CN.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2767)
=> Picker: update format & add custom label demo

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2769)
=> bump 2.2.3

components/picker/style/index.less, site/kitchen/src/static/template.html
Fixes #2795 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2810)
=> Fix: Popup should be compatible with bottom safe area

.circleci/config.yml, .npmrc, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2684)
=> feat: add circleci to publish and deploy

components/picker-view/PickerView.tsx, components/picker-view/__tests__/__snapshots__/demo.test.js.snap, components/picker-view/__tests__/index.test.js, components/picker-view/demo/basic.md
Fixes #2775 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2815)
=> Fix PickerView that accept one-dimensional array as data property

site/desktop/src/template/Layout/Footer.jsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/2889)
=> docs(showcase): add link to ng-zorro-mobile in footer

components/input-item/index.en-US.md, components/input-item/index.zh-CN.md
close issue #2966
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3014)
=> doc(InputItem): add more description

components/grid/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3015)
=> Fix(Grid): Fix activeStyle type (#2996)

components/input-item/__tests__/index.test.js, components/input-item/index.tsx
close #3026 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3027)
=> Fix(InputItem): onChange bug (close #3026)

components/drawer/style/index.less
fix https://github.com/ant-design/ant-design-mobile/issues/3052
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3063)
=> style(module: drawer): fix drawer z-index

site/desktop/src/template/Layout/index.jsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3079)
=> feat: site add BackToTop

components/toast/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3067)
=> toast传入element报ts错误

components/button/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3051)
=> fix Button icon type

site/desktop/src/template/Layout/index.jsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3080)
=> Site Update

components/input-item/index.tsx
close #3037
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3045)
=> Fix(InputItem): controled input behavior #3037

components/image-picker/PropsType.tsx, components/image-picker/index.en-US.md, components/image-picker/index.tsx, components/image-picker/index.zh-CN.md
image-picker添加了对capture属性的支持,移动设备可以指定通过相机拍照上传图片
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3114)
=> image-picker添加了对capture属性的支持,移动设备可以指定通过相机拍照上传图片

components/tab-bar/index.tsx
https://github.com/ant-design/ant-design-mobile/issues/3112
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3113)
=> fix: #3112

components/input-item/index.en-US.md, components/input-item/index.zh-CN.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3099)
=> Doc(InputItem): add note

components/image-picker/index.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3134)
=> fix: image-picker error

docs/react/use-with-create-react-app.en-US.md, docs/react/use-with-create-react-app.zh-CN.md
Fixes  #3094
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3132)
=> 更新文档：使用 customize-cra 来实现按需加载 antd-mobile

site/desktop/src/zh-CN.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3187)
=> typo for 扫描演示 -》 扫码演示

components/tabs/style/index.less
close #3119
close #3140
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3188)
=> fix: fix height error on chrome 73 or later

components/list/PropsType.tsx
Update TypeScript definition for the component.
Reference the issue #3182
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3183)
=> fix typescript support

components/_util/closest.tsx, package.json
https://github.com/ant-design/ant-design-mobile/issues/3005
https://github.com/react-component/m-picker/pull/108
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3181)
=> fix: ts 2.9.x types path error

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3190)
=> bump: 2.2.12

components/date-picker/PropsType.tsx, components/flex/PropsType.tsx, components/list/PropsType.tsx, components/locale-provider/locale-provider.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3194)
=> fix: List types and remove unnecessary chirldren props define

components/list-view/index.en-US.md, components/list-view/index.zh-CN.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3253)
=> fix: fix listview doc

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, package.json
Changlog of 2.2.14
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3256)
=> doc: update changelog of version/2.2.14

components/image-picker/index.tsx
close #3302
* [ x ] Make sure that you follow antd's [code convention](https://github.com/ant-design/ant-design/wiki/Code-convention-for-antd).
* [ x  Run `npm run lint` and fix those errors before submitting in order to keep consistent code style.
* [ x ] Rebase before creating a PR to keep commit history clear.
* [ x ] Add some descriptions and refer relative issues for you PR.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3311)
=> fix:修复图片路径存在空格时不显示的问题

components/notice-bar/Marquee.tsx, components/notice-bar/PropsType.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3261)
change type of icon in NoticeBarPropsType
=> fix: icon in NoticeBarPropsType could be null

components/toast/index.tsx, package.json
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3211)
=> Fix(Toast): add onclose type null  (#3163)

components/tab-bar/index.tsx
#3258
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3270)
=> 修复了Tab组件中children不能包含null的问题, 使得可以方便的隐藏特定tab

CHANGELOG.en-US.md, CHANGELOG.zh-CN.md, components/image-picker/__tests__/__snapshots__/demo.test.js.snap, package.json
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3333)
=> chore:  changelog  

components/input-item/CustomInput.tsx, package.json
RT
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3365)
=> fix: 修复数字键盘的focus弹出问题

components/toast/index.tsx
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3382)
=> fix: 修复连续调用Toast.loading('loading')后只能关闭最后一个Toast实例(#2930)(#3073)

components/input-item/index.en-US.md, components/input-item/index.zh-CN.md
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3406)
=> doc: InputItem 文档更新

components/input-item/__tests__/index.test.js
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3428)
=> chore:fix test case for input-item

components/drawer/PropsType.tsx
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3496)
=> fix(drawer): missing enableDragHandle on type definitions

components/icon/index.tsx, components/pull-to-refresh/__tests__/__snapshots__/demo.test.js.snap, components/switch/style/index.less
remove fix shadow for right-down
centre the switch
->
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3606)
=> Fix Switch style error

components/input-item/CustomInput.tsx, components/input-item/CustomKeyboard.tsx
Reverts ant-design/ant-design-mobile#3401
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3613)
=> Revert "InputItem在customInput组件事件click替换为touchend"

.gitignore, README.md, config/config.ts, package.json
预览： https://ant-design-mobile.vercel.app/
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3708)
=> feat: mobile theme website

components/style/index.less
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ant-design/ant-design-mobile/3713)
=> feat: add single body background variable

src/components/infinite-scroll/demos/content.tsx, src/components/infinite-scroll/index.md, src/components/infinite-scroll/index.tsx
=> Feat custom infinite scroll content

src/components/button/demos/index.tsx, src/components/button/index.less, src/components/popover/index.less, src/components/tabs/index.tsx
=> fix: Button & Popover.Menu 样式

src/components/badge/tests/badge.test.tsx
=> test: badge

src/components/card/tests/card.test.tsx
=> test: card

src/components/cascader/tests/cascader.test.tsx
=> test: cascader

src/components/space/tests/space.test.tsx
=> test: space

src/components/checkbox/tests/checkbox.test.tsx
=> test: checkbox

src/components/checkbox/index.tsx, src/components/radio/index.tsx
=> Fix radio and checkbox value is 0

src/components/collapse/tests/collapse.test.tsx
=> test: add collapse test

package.json, yarn.lock
在线预览地址： https://dist-bvfqtro9v-xiaohuoni.vercel.app/all-components
=> feat: add all-components display

src/components/switch/demos/index.tsx, src/components/switch/index.md, src/components/switch/switch.less, src/components/switch/switch.tsx
=> feat: Switch with content

src/components/empty/demos/index.tsx, src/components/empty/empty.less, src/components/empty/empty.tsx, src/components/empty/index.md
=> feat: Empty 支持自定义图片

src/components/index-bar/demos/demo2.tsx, src/components/index-bar/index-bar.tsx, src/components/index-bar/index.md, src/components/index-bar/index.ts
#3963 
特性：为 IndexBar 组件添加 ref，实现命令式调用，滚动到指定锚点
=> feat: IndexBar ref

src/components/checkbox/checkbox.less, src/components/checkbox/checkbox.tsx, src/components/checkbox/demos/index.tsx, src/components/checkbox/index.md
#3896 
特性：为 Checkbox 组件添加自定义 icon
=> feat: Checkbox custom icon

src/components/result/demos/index.tsx, src/components/result/index.md, src/components/result/result.tsx
=> feat: Result icon

src/components/slider/demos/index.less, src/components/slider/demos/index.tsx, src/components/slider/index.md, src/components/slider/slider.less, src/components/slider/slider.tsx, src/components/switch/demos/index.less, src/components/switch/demos/index.tsx, src/components/switch/index.md, src/components/switch/switch.less, src/components/switch/switch.tsx
Slider 和 Switch 使用 CSS 变量，可以跟随主题色变换。同时更新&加入一些自定义样式的 demo。
=> fix: Slider & Switch use CSS variables

src/components/space/demos/index.tsx, src/components/space/index.md, src/components/space/space.less, src/components/space/space.tsx
#3971  add `justify` prop to Space
=> feat(Space): add justify prop

src/components/selector/demos/demo1.tsx, src/components/selector/demos/index.less, src/components/selector/index.md, src/components/selector/selector.less, src/components/selector/selector.tsx
#3982
Selector 暴露 `--checked-color` CSS 变量。
=> feat: selector add css variable

src/components/checkbox/checkbox.tsx
=> enhance: Checkbox usage warning when using with Checkbox.Group

src/components/picker/demos/index.tsx, src/components/picker/index.md, src/components/picker/picker.less, src/components/picker/picker.tsx
#3991 support Picker `title` prop
=> feat: Picker add `title` prop

src/components/search/search.tsx
#3996
特性：为 Search 组件添加 cancelText 属性
=> feat: add cancelText prop to Search

src/components/nav-bar/demos/index.tsx, src/components/nav-bar/nav-bar.tsx, src/components/stepper/stepper.tsx
update these two components' icons to antd-monile-icons
=> enhance: Stepper and Navbar icons use antd-mobile-icons

src/components/button/tests/button.test.tsx
移除 Button 组件中重复的测试：`renders with disabled`
=> chore: remove Button duplicate test

package.json, src/components/button/demos/index.tsx, src/components/check-list/check-list-item.tsx, src/components/checkbox/checkbox.less, src/components/checkbox/checkbox.tsx, src/components/checkbox/demos/index.tsx, src/components/image/image.less, src/components/image/image.tsx, src/components/input/input.less, src/components/input/input.tsx, src/components/radio/demos/index.tsx, src/components/radio/radio.less, src/components/radio/radio.tsx, src/components/rate/demos/index.tsx, src/components/rate/rate.tsx, src/components/result/demos/index.tsx, src/components/result/result.less, src/components/result/result.tsx, src/components/search/search.tsx, src/components/switch/demos/index.tsx, yarn.lock
=> Use antd-mobile-icons

src/components/badge/demos/index.tsx, src/components/card/demos/index.tsx, src/components/card/tests/card.test.tsx, src/components/collapse/collapse.tsx, src/components/dialog/demos/index.tsx, src/components/empty/demos/index.tsx, src/components/image-uploader/image-uploader.tsx, src/components/list/list-item.tsx
=> Enhance use antd mobile icons

src/components/swiper/index.md
=> doc: update Swiper doc

src/components/button/index.md, src/components/input/index.md, src/components/search/index.md
=> Doc update css variable

src/components/action-sheet/tests/action-sheet.test.tsx, src/components/dialog/index.md, src/components/dialog/show.tsx, src/components/popup/popup.tsx
=> doc: update Dialog doc

src/components/toast/toast.less
修复了 5.0.0-beta.11 版本的 toast 定位异常
=> fix: Toast position error

src/components/pull-to-refresh/pull-to-refresh.tsx
=> enhance(PullToRefresh): add class to children wrap for cumstom styling

src/components/image-uploader/image-uploader.tsx, src/components/image-uploader/index.md
=> feat: ImageUploader add `onDelete` prop

src/components/form/demos/demo2.tsx, src/components/form/form.tsx, src/components/form/index.tsx
#4033
Form 支持 ref，class component 可以通过 ref 获取/操作数据域
=> enhance: Form ref

src/components/stepper/demos/index.tsx, src/components/stepper/index.md, src/components/stepper/stepper.tsx
=> feat: Stepper add `onFocus` & `onBlur` prop

src/components/collapse/collapse.tsx, src/components/collapse/demos/index.tsx
=> feat: add dynamic content demo for Collapse

.github/workflows/gh-pages.yml, src/components/swiper/demos/demo1.tsx, src/components/swiper/index.md, src/components/swiper/swiper.less, src/components/swiper/swiper.tsx
=> feat: Swiper supports centered display item

src/components/search/index.md, src/components/search/search.tsx, src/components/stepper/index.md, src/components/stepper/stepper.tsx
Stepper and Search `onFocus` & `onBlur` export event
=> Enhance focus export event

src/components/tab-bar/demos/index.tsx, src/components/tab-bar/index.md, src/components/tab-bar/tab-bar.tsx
=> enhance: Tabbar.Item icon

src/components/date-picker/date-picker.tsx, src/components/picker/demos/date-picker-demo.tsx, src/components/picker/index.md
=> feat: DatePicker add `title` prop

src/components/page-indicator/demos/demo1.tsx, src/components/page-indicator/index.md, src/components/page-indicator/page-indicator.less, src/components/page-indicator/page-indicator.tsx
=> feat: change PageIndicator CSS variable

src/components/space/space.tsx
if isBugFix :
elif isNewFeature :
=> refactor:(space) use mergeProps replace withDefaultProps

src/components/action-sheet/action-sheet.tsx, src/components/badge/badge.tsx, src/components/checkbox/group.tsx, src/components/date-picker/date-picker.tsx, src/components/ellipsis/ellipsis.tsx, src/components/error-block/error-block.tsx, src/components/grid/grid.tsx, src/components/image-viewer/image-viewer.tsx, src/components/infinite-scroll/infinite-scroll.tsx, src/components/nav-bar/nav-bar.tsx, src/components/progress-bar/progress-bar.tsx, src/components/progress-circle/progress-circle.tsx, src/components/pull-to-refresh/pull-to-refresh.tsx, src/components/radio/group.tsx, src/components/rate/rate.tsx, src/components/slider/slider.tsx, src/components/stepper/stepper.tsx, src/components/steps/steps.tsx, src/components/tree-select/multiple.tsx, src/components/tree-select/tree-select.tsx, src/utils/with-default-props.tsx
if isBugFix :
elif isNewFeature :
=> refactor: replace `withDefaultProps` with `mergeProps`

src/components/error-block/index.en.md, src/components/error-block/index.zh.md
=> doc: (ErrorBlock) `status` prop type

src/components/image/image.tsx, src/components/image/lazy-detector.tsx
if isBugFix :
elif isNewFeature :
=> enhance: (Image) improve the performance with `lazy`

src/components/search/demos/demo1.tsx, src/components/search/index.en.md, src/components/search/index.zh.md, src/components/search/search.tsx
=> feat: (Search) customize the display of the cancel button

src/components/form/context.tsx, src/components/form/form-item.tsx
=> enhance: (Form) normal item collects sub noStyle items errors

src/components/tabs/demos/index.tsx, src/components/tabs/tabs.less, src/components/tabs/tabs.tsx
=> feat: (Tabs) add a mask layer to the left and right

src/components/image-uploader/image-uploader.tsx
=> fix: (ImageUploader) miscalculation of files length

src/components/image/demos/demo2.tsx, src/components/image/image.tsx, src/components/image/index.en.md, src/components/image/index.zh.md
=> fix: (Image) changing src doesn't work after entering the failed state

src/components/picker/index.zh.md
Help user to locate the components which hide below.
=> doc: (Picker) add anchor link

src/components/search/index.en.md, src/components/search/index.zh.md, src/components/search/search.tsx
Whether to clear the input after the cancel button is clicked.
#4353
=> feat: (Search) add clearOnCancel prop

src/components/checkbox/checkbox.less, src/components/checkbox/checkbox.tsx, src/components/checkbox/demos/index.tsx
=> fix: (Checkbox) disabled unchecked icon style

src/components/popover/index.en.md
Fix an error in the English document
=> doc:English version of Popover doc

src/components/button/button.less, src/components/button/button.tsx, src/components/button/demos/demo1.tsx, src/components/button/demos/demo2.tsx, src/components/button/index.en.md, src/components/button/index.zh.md
=> feat: Button组件新增API shape

src/components/date-picker-view/date-picker-view.tsx, src/components/date-picker-view/demos/index.tsx, src/components/date-picker/date-picker-utils.ts, src/components/date-picker/date-picker.tsx, src/components/date-picker/demos/index.tsx, src/components/picker-view/index.en.md, src/components/picker-view/index.zh.md, src/components/picker-view/picker-view.tsx, src/components/picker/index.en.md, src/components/picker/index.zh.md
Add a prop to custom rendering the label shown on the column in `DatePicker` and `DatePickerView`
=> feat: (DatePicker) add `renderLabel` prop

src/components/dialog/demos/index.tsx, src/components/dialog/dialog-action-button.tsx, src/components/dialog/dialog.tsx
=> enhance: (Dialog) prevent action button click when animating

src/components/date-picker/date-picker-utils.ts
=> fix: (DatePicker) precision of second not working

src/components/picker-view/column.tsx, src/components/picker-view/picker-view.tsx, src/components/picker/picker.tsx
=> refactor: (Picker & CascadePicker) prevent expectedly calling `onChange`

src/components/dialog/dialog.less, src/components/dialog/dialog.tsx, src/components/mask/mask.tsx
=> fix: (Dialog) prevent action button click when closing 

src/components/search-bar/search-bar.tsx
=> fix: (SearchBar) set keyboard enterKeyHint to "search"

src/components/index-bar/context.tsx, src/components/index-bar/demos/demo3.tsx, src/components/index-bar/index-bar.tsx, src/components/index-bar/index.en.md, src/components/index-bar/index.zh.md, src/components/index-bar/panel.tsx
修复：https://github.com/ant-design/ant-design-mobile/issues/4439
=> fix: (IndexBar) fix wrong order after rerender

src/components/tag/demos/index.tsx, src/components/tag/index.en.md, src/components/tag/index.zh.md, src/components/tag/tag.less, src/components/tag/tag.tsx
=> feat: (Tag) add css variables

src/components/tabs/index.en.md, src/components/tabs/index.zh.md, src/components/tabs/tabs.less, src/components/tabs/tabs.tsx
=> feat: (Tabs) add `--content-padding`

src/components/list/index.en.md, src/components/list/index.zh.md
更新下 List 的 CSS 变量文档，之前漏了 `--align-item`
另外优化了一下结构
=> doc: (List) update doc of css variables

src/components/check-list/check-list-item.tsx, src/components/check-list/check-list.tsx, src/components/check-list/index.en.md, src/components/check-list/index.zh.md
=> fix: (CheckList) update css variables

src/components/number-keyboard/number-keyboard.tsx
=> feat: (NumberKeybord) backspace key suports continuous-typing

src/components/dialog/dialog.tsx, src/components/mask/mask.tsx, src/components/popup/popup.tsx
=> fix: (Mask & Dialog & Popup) 解决这些组件动画过程中途被卸载时，会警告报错的问题

src/components/side-bar/demos/index.tsx
=> chore: add side-bar usage

src/components/virtual-input/demos/demo1.tsx, src/components/virtual-input/virtual-input.less, src/components/virtual-input/virtual-input.tsx
=> feat: (VirtualInput) support clearable & fix problem about auto scrolling

src/components/action-sheet/action-sheet.tsx, src/components/action-sheet/index.en.md, src/components/action-sheet/index.zh.md
=> feat: (ActionSheet) Action 的 text 和 description 属性支持 ReactNode

src/components/form/form.tsx, src/components/form/index.en.md, src/components/form/index.zh.md
=> feat: (Form) support the mode property

src/components/cascader-view/cascader-view.less
=> fix: (Cascader) unable to scroll when list height exceeds

src/components/dropdown/demos/demo1.tsx, src/components/dropdown/dropdown.less, src/components/dropdown/dropdown.tsx, src/components/dropdown/index.en.md, src/components/dropdown/index.zh.md, src/components/dropdown/item.tsx
close #4515 
1. 默认情况下，使用 icon 替换了 ::after
2. 增加了 arrow 属性，实现自定义 arrow
=> feat: (Dropdown) add arrow prop

src/components/date-picker-view/date-picker-view.tsx, src/components/date-picker-view/demos/demo1.tsx, src/components/date-picker-view/demos/demo2.tsx, src/components/date-picker-view/index.ts, src/components/date-picker/date-picker-date-utils.ts, src/components/date-picker/date-picker-utils.ts, src/components/date-picker/date-picker-week-utils.ts, src/components/date-picker/date-picker.tsx, src/components/date-picker/index.ts, src/components/picker-view/index.en.md, src/components/picker-view/index.zh.md, src/components/picker/index.en.md, src/components/picker/index.zh.md
在 DatePickerView 中加入了 debug demo
性能上感觉还过得去，没有 filter 的时候性能和之前一样，有 filter 之后会在每次滑动时对所有 filter 上注册了的 columns 进行一次判断，和其他方案相比应该是性能最优的
Closes #4502
=> feat: (DatePicker) add `filter` prop

src/components/collapse/collapse.tsx, src/components/collapse/demos/demo1.tsx, src/components/collapse/index.en.md, src/components/collapse/index.zh.md
=> feat: (Collapse) add arrow prop

src/components/collapse/collapse.tsx, src/components/collapse/demos/demo1.tsx, src/components/collapse/index.en.md, src/components/collapse/index.zh.md
=> feat: (Collapse) add arrow render-prop

src/components/number-keyboard/demos/demo1.tsx, src/components/number-keyboard/number-keyboard.less
=> fix:修复带确认键盘符合按钮样式问题

src/components/toast/index.en.md, src/components/toast/index.ts, src/components/toast/index.zh.md, src/components/toast/methods.tsx
目前没有使用 ConfigProvider，感觉不是很有必要，看了一下 antd 也没有走，如果感觉有必要的话可以再加上～
=> feat: (Toast) add config method

src/components/progress-bar/progress-bar.less
=> fix: progress-bar style

src/components/progress-bar/demos/demo1.tsx, src/components/progress-bar/index.en.md, src/components/progress-bar/index.zh.md, src/components/progress-bar/progress-bar.less, src/components/progress-bar/progress-bar.tsx
=> feat: (ProgressBar) add `--track-color`

src/components/radio/index.en.md, src/components/selector/index.en.md
=> doc: correct misspelled words

src/components/tab-bar/demos/demo1.tsx, src/components/tab-bar/index.en.md, src/components/tab-bar/index.zh.md, src/components/tab-bar/tab-bar.less, src/components/tab-bar/tab-bar.tsx
feat: (TabBar) support safe area
=> feat: (TabBar) support safe area

src/components/stepper/demos/demo1.tsx, src/components/stepper/index.en.md, src/components/stepper/index.zh.md, src/components/stepper/stepper.tsx
close [4590](https://github.com/ant-design/ant-design-mobile/issues/4590)
=> feat: (Stepper) add inputReadOnly props

src/components/image-uploader/image-uploader.tsx
=> fix: (ImageUploader) Fix `onChange` to support the `extra` parameter

src/components/checkbox/checkbox.less, src/components/radio/radio.less
=> fix: (Radio & Checkbox) support text wrapping

src/components/index-bar/index-bar.less
=> fix: IndexBar 序列侧边栏显示不完整

src/components/side-bar/side-bar.tsx
=> fix: (SideBar) fix `SideBarItem` title type

src/components/pull-to-refresh/index.en.md, src/components/pull-to-refresh/index.zh.md, src/components/pull-to-refresh/pull-to-refresh.tsx
feature: pull-to-refresh add disabled property #4601
=> feature: pull-to-refresh add disabled property

src/components/tabs/index.en.md, src/components/tabs/index.zh.md, src/components/tabs/tabs.less, src/components/tabs/tabs.tsx
=> feat: (Tabs) add `--active-line-height` and `--active-line-border-radius`

src/components/image-uploader/image-uploader.tsx, src/components/image-uploader/index.en.md, src/components/image-uploader/index.zh.md
=> feat: (ImageUploader) add preview prop

src/components/popover/popover.less, src/components/popover/popover.tsx
=> fix: Popover 气泡弹出框的箭头遮挡内容的问题 

src/components/toast/toast.less, src/components/toast/toast.tsx
close #4637
我手里的IOS 15测试没问题，还需要测下其他机型
=> fix: (Toast) fix max-width

src/components/image-viewer/slides.tsx
=> fix: (MultiImageViewer) `onIndexChange` does not work

src/components/search-bar/demos/demo1.tsx, src/components/search-bar/index.en.md, src/components/search-bar/index.zh.md, src/components/search-bar/search-bar.less, src/components/search-bar/search-bar.tsx
=> feat: (SearchBar) add `--height` and `--padding-left` css variables

src/components/list/index.en.md, src/components/list/index.zh.md, src/components/list/list.less, src/components/list/list.tsx
=> feat: (List) add some CSS variables

src/components/avatar/avatar.tsx
=> fix: (Avatar) add nativeProps  `--border-radius`

src/components/error-block/error-block.tsx, src/components/list/list.tsx, src/components/notice-bar/notice-bar.tsx
这些 css 变量，在文档中有，`NativeProps` 中漏掉了
=> fix: some CSS variables

src/components/popup/index.en.md, src/components/popup/index.zh.md
更新 popup 遗漏的属性 `mask` `afterShow`
=> doc: update popup doc

docs/guide/hd.en.md, docs/guide/hd.zh.md
https://github.com/ant-design/ant-design-mobile/issues/4748#issuecomment-1023829785
=> doc: 在高清方案文档里添加global样式的替换

src/components/radio/radio.tsx
className 和 style 公共方法 withNativeProps 里已经包含，应该不需要单独设置 props
=> refactor: (Radio) remove props className & style

src/components/empty/empty.less
=> fix: (Empty) fix image className

src/components/radio/tests/radio.test.tsx
=> test: radio

src/components/checkbox/tests/checkbox.test.tsx
=> test: (Checkbox) group checkbox tests with `describe`

src/components/input/input.less
fix [#4785](https://github.com/ant-design/ant-design-mobile/issues/4785)
=> enhance: (Input) add `min-height` style

src/components/form/demos/demo1.tsx, src/components/form/form-item.less, src/components/form/form-item.tsx
<hr>
BTW，垂直布局下 `Popover` 弹出的方向需要改么
=> feat: (Form.Item) add help popover and icon

package.json, yarn.lock
=> chore: remove @types/classnames

src/components/floating-panel/index.en.md, src/components/floating-panel/index.zh.md
[#4813](https://github.com/ant-design/ant-design-mobile/issues/4813)
=> doc: (FloatingPanel) add CSS Variables

src/components/slider/slider.less
=> fix: (Slider) alignment of ticks

src/components/form/demos/demo1.tsx, src/components/form/form.tsx, src/locales/base.ts, src/locales/zh-CN.ts
refer: https://github.com/ant-design/ant-design/blob/2d484bbe474dc2058af8267cab0c9818292bafb5/components/locale/zh_CN.tsx#L82-L128
fix: #4544
=> feat: (Form) support for form components to use locales

src/components/date-picker/tests/date-picker.test.tsx
1. 原本的 DatePicker 跑 test 有个 err，加了一个 waitFor
2.  test case
=> test: (DatePicker) add some tests

src/components/text-area/index.en.md, src/components/text-area/index.zh.md, src/components/text-area/text-area.less, src/components/text-area/text-area.tsx
add `--text-align`,  `--count-text-align` CSS variable
=> feat: (TextArea) add `--text-align`,  `--count-text-align` CSS variable

src/components/form/tests/__snapshots__/form.test.tsx.snap, src/components/form/tests/form.test.tsx
=> test: (Form) add some tests

src/components/check-list/check-list-item.tsx
=> enhance: (CheckList) add active className

src/components/cascader-view/cascader-view.tsx, src/components/cascader-view/use-cascader-value-extend.tsx, src/components/cascader/index.en.md, src/components/cascader/index.zh.md
=> feat: (CascaderView & Cascader) add  `isLeaf` to extend data in onChange event

src/components/tab-bar/index.en.md, src/components/tab-bar/index.zh.md, src/components/tab-bar/tab-bar.tsx
=> feat: (TabBar.Item) `title` supports render function

src/components/floating-bubble/floating-bubble.less, src/components/floating-bubble/floating-bubble.tsx, src/components/floating-bubble/index.en.md, src/components/floating-bubble/index.zh.md
=> feat: (FloatingBubble) add --background  CSS variable

fileTransformer.js, jest.config.js, src/components/dot-loading/dot-loading.tsx, src/components/dot-loading/tests/dot-loading.test.tsx, src/components/error-block/error-block.tsx, src/components/error-block/tests/__snapshots__/error-block.test.tsx.snap, src/components/error-block/tests/error-block.test.tsx, src/components/mask/tests/mask.test.tsx, src/components/switch/tests/switch.test.tsx, src/components/tag/tests/__snapshots__/tag.test.tsx.snap, src/components/tag/tests/tag.test.tsx
1、目前测 svg 的时候会报错，按照官网加了个 transform
https://jestjs.io/docs/code-transformation#transforming-images-to-their-path
2、`dot-loading` 里 svg 的 id 会重复 
3、`ErrorBlock` 里 image 缺少 alt 过不了 a11y
4、加了一些 tests
=> test: add some tests

src/components/action-sheet/action-sheet.tsx, src/components/action-sheet/index.en.md, src/components/action-sheet/index.zh.md
=> feat: (ActionSheet) add `popupClassName` and `popupStyle`

src/components/action-sheet/action-sheet.tsx, src/components/action-sheet/demos/demo1.tsx, src/components/action-sheet/index.ts, src/components/dialog/demos/demo2.tsx, src/components/dialog/index.ts, src/components/dialog/show.tsx, src/components/image-uploader/image-uploader.tsx, src/components/image-viewer/index.ts, src/components/image-viewer/methods.tsx, src/components/modal/demos/demo3.tsx, src/components/modal/index.ts, src/components/modal/show.tsx, src/utils/render-imperatively.tsx
#4909 的后续
@xiaoyao96 @miracles1919
=> refactor: refactor the show methods of some components with renderImperatively util and rename some irregular handler types

package.json, src/components/list/demos/demo4.tsx, src/components/list/index.en.md, src/components/list/index.zh.md, yarn.lock
=> doc: (List) add virtualized List example

src/components/cascade-picker-view/demos/demo1.tsx, src/components/cascade-picker-view/demos/options-data.tsx, src/components/cascade-picker-view/tests/cascade-picker-view.test.tsx, src/components/picker-view/tests/picker-view.test.tsx, src/tests/gesture/utils.ts
1. 记录个坑，用 jest 测试的时候，发现触发不了 label 的点击事件，详情见这个 [issue](https://github.com/pmndrs/use-gesture/issues/418) 
2. 测试 drag 手势参考了官方的 [drag.test.tsx](https://github.com/pmndrs/use-gesture/blob/main/test/drag.test.tsx)
=> test: (PickerView & CascadePickerView) add some tests

src/components/form/demos/demo-array.tsx
Form.Array的demo中，先添加2个联系人，再全部删除，然后在添加一个，此时，应显示「联系人1」，而demo中显示为「联系人3」
=> doc: (Form.Array) update demo

docs/components/home-page.tsx
=> docs: modify footerGroups title in home-page

.dumi/plugin-gallery/gallery.tsx, .dumi/plugin-gallery/index.ts
目前 gallery 页面访问某个组件的时候，页面刷新就会回到首页
这里优化了一下，例如访问 Button 就会变成 gallery/button
=> doc: update gallery

src/components/config-provider/demos/demo1.tsx, src/components/dialog/confirm.tsx, src/components/modal/confirm.tsx, src/components/pull-to-refresh/pull-to-refresh.tsx, src/locales/base.ts, src/locales/zh-CN.ts, src/locales/zh-HK.ts, src/locales/zh-TW.ts
1. 弹窗、对话框、下拉刷新支持多语言；
2. 支持中文(香港繁体)、中文(台湾繁体)
=> feat: add locale support for Modal Dialog and PullToRefresh and add zh-HK zh-TW locales

src/components/input/index.en.md, src/components/input/index.zh.md, src/components/input/input.tsx, src/components/text-area/index.en.md, src/components/text-area/index.zh.md, src/components/text-area/text-area.tsx
=> feat: (Input & TextArea) add `autoFocus` prop

docs/guide/faq.en.md, docs/guide/faq.zh.md
=> docs: add docs

src/components/picker-view/index.en.md, src/components/picker-view/index.zh.md, src/components/picker-view/picker-view.tsx, src/components/picker-view/wheel.tsx, src/components/picker/index.en.md, src/components/picker/index.zh.md, src/components/picker/picker-utils.ts, src/components/picker/picker.tsx, src/components/picker/tests/picker.test.tsx
=> feat: (Picker & PickerView & CascadePicker & CascadePickerView) add renderLabel property for user-defined render label

src/components/form/context.tsx, src/components/form/demos/demo1.tsx, src/components/form/form-item.tsx, src/components/form/form.tsx
=> fix: (Form) form name not work

src/components/ellipsis/ellipsis.tsx, src/components/ellipsis/index.en.md, src/components/ellipsis/index.zh.md
=> feat: (Ellipsis) add `onContentClick` prop

package.json
close #5000
这次仔细扫了一遍文档，应该没有遗漏了
=> fix: update exports fields for vite

docs/components/home-page.less
=> doc: fix home page

src/components/form/form-item.tsx
=> enhance: (Form) make `validateTrigger` default to `trigger`

gulpfile.js
https://stackblitz.com/edit/react-ejlxwi?file=index.js
参考 antd 配置的结果 https://cdn.jsdelivr.net/npm/antd@4.19.3/dist/antd.js
=> fix: 修复 stackblitz 无法使用

package.json
=> fix: remove exports field

src/components/form/form-item.tsx, src/utils/tests/undefined-fallback.test.ts, src/utils/undefined-fallback.ts
=> fix: (Form) change the default value of validateTrigger

src/components/image-uploader/image-uploader.tsx, src/components/image-uploader/index.en.md, src/components/image-uploader/index.zh.md, src/components/image-uploader/preview-item.tsx
=> feat: (ImageUploader) add `imageFit` prop

src/components/picker-view/picker-view.tsx, src/components/picker-view/wheel.tsx, src/components/picker/index.en.md, src/components/picker/index.zh.md
=> feat: (Picker) PickerColumnItem add `key` prop

docs/guide/i18n.en.md, docs/guide/i18n.zh.md
=> doc: update i18n docs

src/components/stepper/tests/stepper.test.tsx
=> test: add test cases for Stepper

src/components/config-provider/tests/__snapshots__/config-provider.test.tsx.snap, src/locales/zh-HK.ts, src/locales/zh-TW.ts
=> enhance: supplement zh-HK and zh-TW

src/components/infinite-scroll/infinite-scroll.tsx, src/components/pull-to-refresh/pull-to-refresh.tsx, src/locales/base.ts, src/locales/es-ES.ts, src/locales/ko-KR.ts, src/locales/zh-CN.ts, src/locales/zh-HK.ts, src/locales/zh-TW.ts
1. support i18n in infiniteScroll
2.  change loading text in pullToRefresh
=> feat: support i18n in infiniteScroll and change loading text in pullToRefresh

src/components/calendar/calendar.tsx
=> fix: (Calendar) add first date of month when use jumpTo

src/components/input/index.en.md, src/components/input/index.zh.md, src/components/input/input.tsx, src/components/side-bar/demos/demo4.tsx, src/components/text-area/index.en.md, src/components/text-area/index.zh.md, src/components/text-area/text-area.tsx
=> feat: (Input & TextArea) add onClick prop

src/components/form/form-item.tsx, src/components/form/tests/form.test.tsx
=> feat: (Form) add className for error item

src/components/button/button.tsx, src/components/button/index.en.md, src/components/button/index.zh.md, src/components/button/tests/button.test.tsx
=> feat: (Button) add `loadingIcon` prop

src/components/index-bar/panel.tsx
=> enhance: (IndexBar.Panel) add `children` prop

.dumi/plugin-gallery/gallery.less, .dumi/plugin-gallery/gallery.tsx
=> doc: gallery add searchbar

src/components/floating-panel/demos/demo2.tsx, src/components/floating-panel/index.en.md, src/components/floating-panel/index.zh.md
#4755 
不知道这个效果行不行 ~
颜色从这里取的 [uigradients.com/](http://uigradients.com/)
=> doc: (FloatingPanel) add demo

src/components/button/button.tsx, src/components/button/demos/demo2.tsx, src/components/button/index.en.md, src/components/button/index.zh.md
=> feat: (Button) loading add auto mode

src/components/button/tests/button.test.tsx, src/components/dialog/dialog-action-button.tsx, src/components/modal/modal-action-button.tsx
test: (Button) add auto loading test
refactor: (Modal, Dialog) action loading state
=> refactor: (Button) add auto loading test & Modal and Dialog use button loading='auto'

src/components/floating-panel/demos/demo3.less, src/components/floating-panel/demos/demo3.tsx
=> doc: (FloatingPanel) update demo3

src/components/cascade-picker/cascade-picker-utils.ts, src/components/cascade-picker/demos/demo1.tsx, src/components/cascade-picker/use-cascade-picker-options.tsx
=> fix: (CascadePicker) same value children is overwritten

src/components/picker/index.en.md, src/components/picker/index.zh.md, src/components/picker/picker.tsx
=> feat: (Picker) add popupClassName & popupStyle props

src/components/calendar/calendar.en.md, src/components/calendar/calendar.tsx, src/components/calendar/calendar.zh.md, src/components/calendar/demos/demo1.tsx
=> feat: (Calendar) support custom navigation label

src/components/image-uploader/image-uploader.tsx
=> fix: (ImageUploader) fix the same file doesn't trigger beforeUpload

src/components/list/list.less
=> enhance: (List) adjust line-height

src/components/picker/index.en.md, src/components/picker/index.zh.md, src/components/picker/picker.tsx
=> feat: (Picker) add forceRender & destroyOnClose props

src/utils/render.ts
这段来自 [rc-util](https://github.com/react-component/util/blob/master/src/React/render.ts)
=> fix: createRoot warning

src/components/tabs/index.en.md, src/components/tabs/index.zh.md, src/components/tabs/tabs.less, src/components/tabs/tabs.tsx
#5183 
同时新增了 `--active-title-color`
=> feat: (Tabs) add --active-title-color &  --active-line-color CSS variables

package.json, yarn.lock
fix: https://github.com/ant-design/ant-design-mobile/issues/5066
related issue: https://github.com/pmndrs/use-gesture/issues/485
=> fix: 升级 @use-gesture/react 版本，修复滑动中断的问题

src/components/infinite-scroll/demos/demo2.tsx, src/components/infinite-scroll/index.en.md, src/components/infinite-scroll/index.zh.md
=> doc(InfiniteScroll): add infinite virtualized list

src/components/infinite-scroll/demos/demo2.tsx
修复 InfiniteScroll virtualizedList demo，实现虚拟滚动
=> doc(InfiniteScroll): fix virtualizedList demo error

src/locales/fr-FR.ts
Create fr-FR file.
This file is a French translation file.
=> feat: add fr-FR locale

src/components/dialog/dialog.tsx, src/components/modal/modal.tsx
Modal and Dialog add destoryOnClose
=> feat(Modal & Dialog): add `destroyOnClose` and `forceRender` props

docs/guide/ssr.en.md
antd-mobile.css doesnt exist in folder
=> doc: update ssr.en.md

docs/guide/ssr.en.md, docs/guide/ssr.zh.md
=> doc: add usage in remix projects

src/components/image-uploader/index.zh.md
=> doc(ImageUploader): update API table

src/components/input/input.tsx
=> fix(Input): may can't enter values when click the clear button in ios

src/components/cascader-view/use-cascader-value-extend.tsx
=> fix(Cascader): fix `isLeaf` may get wrong value

src/components/cascader-view/cascader-view.tsx, src/components/cascader-view/index.en.md, src/components/cascader-view/index.zh.md, src/components/cascader-view/tests/cascader-view.test.tsx, src/components/cascader/cascader.tsx, src/components/cascader/index.en.md, src/components/cascader/index.zh.md, src/components/cascader/tests/cascader.test.tsx, src/components/mask/mask.tsx
=> feat(CascaderView & Cascader): add onTabsChange prop

src/components/action-sheet/tests/action-sheet.test.tsx, src/components/avatar/tests/avatar.test.tsx, src/components/button/tests/button.test.tsx, src/components/calendar/tests/calendar.test.tsx, src/components/capsule-tabs/tests/capsule-tabs.test.tsx, src/components/cascade-picker-view/tests/cascade-picker-view.test.tsx, src/components/cascader-view/tests/cascader-view.test.tsx, src/components/cascader/tests/cascader.test.tsx, src/components/check-list/tests/check-list.test.tsx, src/components/config-provider/tests/config-provider.test.tsx, src/components/dialog/tests/dialog.test.tsx, src/components/ellipsis/tests/ellipsis.test.tsx, src/components/error-block/tests/error-block.test.tsx, src/components/floating-panel/tests/floating-panel.test.tsx, src/components/image-uploader/tests/image-uploader.test.tsx, src/components/index-bar/tests/index-bar.test.tsx, src/components/infinite-scroll/tests/infinite-scroll.test.tsx, src/components/input/tests/input.test.tsx, src/components/jumbo-tabs/tests/jumbo-tabs.test.tsx, src/components/mask/tests/mask.test.tsx, src/components/modal/tests/modal.test.tsx, src/components/notice-bar/tests/notice-bar.test.tsx, src/components/picker-view/tests/picker-view.test.tsx, src/components/side-bar/tests/side-bar.test.tsx, src/components/switch/tests/switch.test.tsx, src/components/tab-bar/tests/tab-bar.test.tsx, src/components/tabs/tests/tabs.test.tsx, src/components/tag/tests/tag.test.tsx
1、删除了些无效的await。
2、input增加了一些测试用例
3、把一些不必要的sleep定时器调整了下。
=> test(Input): add some tests

src/components/list/list.less
=> fix(List): fix `extra` content can not break lines

tsconfig.json
已使用与项目相同的 typescript 版本
打开项目会有报错
在 `tsconfig.json` 中加入
```typescript
"compilerOptions": {
"outDir": "./",
}
```
可解决报错.
=> chore(tsconfig): update tsconfig rule

src/components/text-area/index.en.md, src/components/text-area/index.zh.md, src/components/text-area/tests/textarea.test.tsx, src/components/text-area/text-area.tsx
=> feat(textArea): support nativeElement ref & update docs

src/components/infinite-scroll/tests/infinite-scroll.test.tsx
用 advanceTimersByTime 调整了下 test
=> test(InfiniteScroll): adjust some tests

src/tests/excludeWarning.ts
增加测试时警告消息的过滤
`fantd-mobile: Global] Seens Like the you will encounter a style messed prob Lem. Please check the browser environment to make sure it supports CSS va
riables.`
=> test: add exclude warning

src/components/stepper/tests/stepper.test.tsx
=> test: fix `stepper.test.tsx` test warnings

src/components/date-picker/tests/date-picker.test.tsx
add  imperative call and precision week test
=> test(DatePicker): add some test

src/components/date-picker-view/demos/demo2.tsx, src/components/date-picker/date-picker-date-utils.ts, src/components/date-picker/date-picker-week-utils.ts
=> fix(DatePicker & DatePickerView): fix year filter not working

src/components/checkbox/native-input.tsx, src/components/radio/radio.tsx, src/components/radio/tests/radio.test.tsx
=> fix(Radio): onChange should be call once when the selected item is clicked multiple times

src/components/input/demos/demo1.less, src/components/input/demos/demo1.tsx, src/components/input/input.less
close https://github.com/ant-design/ant-design-mobile/issues/5339
=> doc(Input): add input password visible demo

src/components/input/demos/demo2.less, src/components/input/demos/demo2.tsx
=> doc(Input): add password input demo with `Form.Item`

src/components/tabs/demos/demo2.less, src/components/tabs/demos/demo2.tsx
=> doc(Tabs): add custom header demo

src/components/list/index.en.md, src/components/list/index.ts, src/components/list/index.zh.md, src/components/list/list.tsx, src/components/list/tests/__snapshots__/list.test.tsx.snap, src/components/list/tests/list.test.tsx
close https://github.com/ant-design/ant-design-mobile/issues/5368
=> feat(List): list support nativeElement ref

src/components/checkbox/demos/demo3.tsx
=> doc(CheckBox): fix demo3

src/components/image/image.tsx, src/components/image/index.en.md, src/components/image/index.zh.md, src/components/image/test/image.test.tsx
=> feat(Image): add `onContainerClick` prop

src/components/calendar/calendar.tsx, src/components/image-uploader/tests/image-uploader.test.tsx, src/components/infinite-scroll/tests/infinite-scroll.test.tsx, src/components/tree-select/tests/tree-select.test.tsx
=> test: adjust test to fix warning

src/components/floating-panel/floating-panel.less
=> fix(FloatingPanel): fix `--border-radius` applying to the wrong element

.dumi/theme/components/Navbar.tsx, config/navs.ts
=> doc: adding domestic mirror navigation

src/components/number-keyboard/demos/demo1.tsx, src/components/number-keyboard/demos/demo2.tsx, src/components/number-keyboard/index.en.md, src/components/number-keyboard/index.zh.md, src/components/number-keyboard/number-keyboard.tsx, src/components/number-keyboard/tests/number-keyboard.test.tsx
=> feat(NumberKeyboard): support multiple customKeys

src/components/action-sheet/tests/__snapshots__/action-sheet.test.tsx.snap, src/components/button/button.tsx, src/components/button/tests/button.test.tsx, src/components/image-viewer/tests/__snapshots__/image-viewer.test.tsx.snap
close #5442 
参考： https://github.com/facebook/react/issues/11538#issuecomment-390386520
=> fix(Button): fix React's bug when the browser translation function is enabled

src/components/image-viewer/slide.tsx, src/components/image-viewer/tests/__snapshots__/image-viewer.test.tsx.snap, src/utils/matrix.ts
=> fix(ImageViewer): scale origin is inaccurate when pinching

src/components/search-bar/search-bar.tsx
=> fix(SearchBar): prevent getting duplicated value on enter press with some IMEs

src/components/result/index.en.md, src/components/result/index.zh.md, src/components/result/result.tsx
#5473
- 删掉了文档中 `description` 的默认值
- `status` 新增默认值 `info`
=> enhance(Result): add default value for `status` prop

src/components/form/context.tsx, src/components/form/demos/demo5.tsx, src/components/form/form-item.tsx, src/components/form/index.en.md, src/components/form/index.zh.md
https://github.com/ant-design/ant-design-mobile/issues/5479
针对这条 issue 提的 feature 哈，中英文档已补充好，demo 也补充好了
=> feat(Form): add new `requiredMarkStyle` option `none`

src/components/rate/rate.less, src/components/rate/rate.tsx
#5469
这次通过`onTouchStart`和`onTouchMove`实现= =。
=> feat(Rate): support slide gesture

src/utils/use-resize-effect.tsx
https://github.com/ant-design/ant-design-mobile/issues/5459
=> fix(useResizeEffect): avoid `ResizeObserver loop limit exceeded` error

src/components/swipe-action/swipe-action.tsx
=> refactor(SwipeAction): adjust the implementation

src/components/swiper/swiper.tsx
=> fix(Swiper): add swiper count dependency when autoplay

src/components/swiper/tests/swiper.test.tsx
=> test(Swiper): add autoplay test when the length of item changes

package.json, pnpm-lock.yaml
ref: https://github.com/alibaba/hooks/issues/1791
=> chore: upgrade ahooks to 3.7.0

docs/components/home-page.tsx
add english translation to footergroup const by applying trans()
function. moved the const into export default() to be able to apply the
function.
=> doc: add i18n for footer

src/components/page-indicator/index.en.md, src/components/page-indicator/index.zh.md, src/components/page-indicator/page-indicator.less
=> style(PageIndicator): adjust default `--dot-color`

src/components/index-bar/index-bar.less
修改选中的气泡距离索引条的间距，由 58px 修改为 64px
=> style(IndexBar): adjust bubble distance

src/components/tab-bar/demos/demo1.tsx, src/components/tab-bar/demos/demo2.tsx, src/components/tab-bar/tab-bar.less
=> style(TabBar): adjust text color and font size

src/components/selector/index.en.md, src/components/selector/index.zh.md, src/components/selector/selector.less, src/components/selector/selector.tsx
related issue:https://github.com/ant-design/ant-design-mobile/issues/5549
=> feat(Selector): add `gap` prop and gap related CSS variables

src/components/search-bar/index.en.md, src/components/search-bar/index.zh.md
[related issue](https://github.com/ant-design/ant-design-mobile/issues/5545)
=> doc(SearchBar): add FAQ about Search Button text

src/components/floating-panel/floating-panel.tsx, src/components/floating-panel/tests/floating-panel.test.tsx
=> fix(FloatingPanel): fix rendering gaps caused by decimal point

src/components/image-viewer/image-viewer.tsx
=> fix(ImageViewer): should reset the transform when viewer is reshowed

src/components/ellipsis/ellipsis.tsx, src/components/ellipsis/index.en.md, src/components/ellipsis/index.zh.md, src/components/ellipsis/tests/ellipsis.test.tsx
=> fix(Ellipsis): fix error when using with display flex and add doc about `word-break`

.github/workflows/check.yml, gulpfile.js
bundle
```diff
antd-mobile.cjs.js
+ antd-mobile.cjs.development.js
antd-mobile.compatible.umd.js
+ antd-mobile.compatible.umd.development.js
antd-mobile.es.js
+ antd-mobile.es.development.js
```
=> chore: add dev and prod bundle

src/components/action-sheet/action-sheet.less, src/components/action-sheet/action-sheet.tsx, src/components/action-sheet/demos/demo1.tsx, src/components/action-sheet/index.en.md, src/components/action-sheet/index.zh.md
=> feat(ActionSheet): add new property `bold` to type `Action` and adjust some styles

src/components/dialog/dialog-action-button.tsx, src/components/dialog/index.en.md, src/components/dialog/index.zh.md
dialog Action text 支持ReactNode，为测试人员提供元素定位方便做自动化测试，也为按钮更灵活配置
=> enhance(Dialog): Action text support ReactNode

src/components/toast/toast.less
=> style(Toast): adjust some styles

src/components/action-sheet/demos/demo1.tsx
=> doc(ActionSheet): adjust text delete to save

src/components/page-indicator/demos/demo1.tsx, src/components/page-indicator/page-indicator.less
add dot color when white color
=> style(PageIndicator): adjust dot color in white mode

.github/workflows/check.yml, .github/workflows/doc-site.yml
=> chore: upgrade ubuntu

src/components/infinite-scroll/index.en.md, src/components/infinite-scroll/index.zh.md
close #5590 
添加 `InfiniteScroll` 组件使用时，常遇到的问题 FAQ 说明
=> doc(InfiniteScroll): add usage notes document

src/components/image-viewer/slides.tsx
=> enhance(ImageViewer): use index as the key

src/components/avatar/avatar.tsx
=> fix(Avatar): adjust `Image` import path to prevent issue in HD mode

src/components/config-provider/tests/config-provider.test.tsx, src/components/image-uploader/image-uploader.tsx, src/components/image-uploader/preview-item.tsx, src/components/image-uploader/tests/image-uploader.test.tsx
=> enhance(ImageUploader): optimize image preview memory

src/components/form/form-item.less, src/components/form/form.less, src/components/form/form.tsx, src/components/form/index.en.md, src/components/form/index.zh.md
#5579  Form新增CSS变量--prefix-width控制Form.Item perfix的宽度
=> feat(Form): add CSS variable `--prefix-width` of Form.Item label width

src/components/popover/popover.tsx, src/components/popover/tests/popover.test.tsx
=> fix: Popover should close when screen move

package.json, pnpm-lock.yaml
发现有 ts 报错，restart ts server 之后还是这样
去查了下了 [use-gesture/releases](https://github.com/pmndrs/use-gesture/releases)，发现有 ts break change
=> chore: upgrade `@use-gesture/react`

src/components/slider/slider.tsx, src/components/slider/tests/slider.test.tsx
=> fix(Slider): value should be formatted when step is a decimal

.dumi/theme/builtins/preview-default/Previewer.tsx, .dumi/theme/builtins/preview-default/use-code-sandbox.tsx, package.json, pnpm-lock.yaml
dumi 里的 alias 会丢失，这边简单做个兜底来让官网支持 codesandbox。
=> doc: support codesandbox open

src/components/passcode-input/passcode-input.less
=> fix: dot in huawei not circle

src/components/slider/slider.tsx, src/components/slider/tests/slider.test.tsx
=> fix(Slider): points should contain max

docs/guide/quick-start.en.md, docs/guide/quick-start.zh.md
=> doc: update ding group img

src/components/slider/thumb.tsx
=> fix(Slider): adjust popover import path

src/index.ts
support users to customize components based on ant-design-mobile.
=> enhance: export all component types

src/components/image-uploader/image-uploader.tsx, src/components/image-uploader/tests/image-uploader.test.tsx
=> fix(ImageUploader): remove failed task when showFailed is false

src/components/image-uploader/tests/image-uploader.test.tsx
使用 `jest.useFakeTimers()`，提高 test 效率，不然一个 upload 要 3 s...
=> test(ImageUploader): adjust with faker timer

src/components/tabs/index.en.md, src/components/tabs/index.zh.md
=> doc(Tabs): update FAQ

gulpfile.js, package.json, pnpm-lock.yaml
vite 发了个新版本，build 会清理文件夹导致复制的文件被删除。调整一下顺序将 patch 文件后置填入。
PS：需要搞个 diff check
=> chore: fix script build

docs/components/components/Footer/index.local.less, docs/components/globalMobile.less, docs/components/globalPC.less, docs/components/home-page.tsx, src/components/calendar/calendar.en.md, src/locales/ja-JP.ts
=> style: prettier format

src/components/stepper/stepper.tsx
Adjust Stepper function order for feature prepare
=> refactor: order for feature prepare

.prettierrc.js, src/components/stepper/demos/demo1.tsx, src/components/stepper/index.en.md, src/components/stepper/index.zh.md, src/components/stepper/stepper.tsx, src/components/stepper/tests/stepper.test.tsx
=> feat: stepper support `formatter` & `parser`

src/components/stepper/index.en.md, src/components/stepper/index.zh.md
=> doc(Stepper): update

src/components/cascader-view/index.en.md, src/components/cascader-view/index.zh.md
=> doc(CascaderView): fix Props placeholder

docs/guide/ssr.en.md, docs/guide/ssr.zh.md
=> doc: add next 13 guide

src/components/image-uploader/image-uploader.tsx, src/components/image-uploader/tests/image-uploader.test.tsx
fix #5833
原因 https://github.com/ant-design/ant-design-mobile/issues/5833#issuecomment-1334867453 说的很清楚了
不过这个 case 测试用例不太好加 - -
=> fix(ImageUploader): upload failure due to duplicate tasks and value

docs/guide/css-variables.en.md, docs/guide/css-variables.zh.md, src/components/cascader/cascader.patch.less, src/global/css-vars-patch.less
=> chore: patch for Cascader height

src/components/selector/index.en.md, src/components/selector/index.zh.md
=> doc: note for ios9

src/components/search-bar/demos/demo1.tsx
#5913 
多个 Toast 问题，改成 console.log
=> doc(SearchBar): update demo

src/components/swiper/index.en.md, src/components/swiper/index.zh.md, src/components/swiper/swiper.tsx, src/components/swiper/tests/swiper.test.tsx, src/utils/with-func-props.ts
=> feat(Swiper):add swiper stopPropagation

src/components/popup/popup.tsx, src/locales/base.ts, src/locales/zh-CN.ts, src/locales/zh-HK.ts, src/locales/zh-TW.ts
=> enhance(Popup): imporve a11y

src/components/side-bar/index.en.md, src/components/side-bar/index.zh.md
=> doc(SideBar): update side-bar default --width

src/components/ellipsis/demos/demo1.tsx, src/components/ellipsis/ellipsis.tsx, src/components/ellipsis/tests/ellipsis.test.tsx
=> feat(Ellipsis): support default expand

src/components/text-area/text-area.tsx
=> fix(TextArea): adjust the height to the prev height

package.json, pnpm-lock.yaml
=> chore: lock react spring version

package.json, pnpm-lock.yaml
=> chore: update `react-is`

src/components/water-mark/index.en.md, src/components/water-mark/index.zh.md
=> doc: water mark default fontSize 14

src/components/infinite-scroll/demos/demo3.less, src/components/infinite-scroll/demos/demo4.tsx
=> doc(InfiniteScroll): optimize demo code

src/components/button/button.less, src/global/theme-default.less
=> refactor: button use new design token

src/components/capsule-tabs/capsule-tabs.less
=> refactor(capsule-tabs): update with new token

src/components/index-bar/index-bar.less
其中 IndexBar bg 应该是用错了，调整了一下。
| -- | -- |
=> refactor: index-bar use new design token

src/components/jumbo-tabs/jumbo-tabs.less
=> refactor(JumboTabs): button use new design token 

src/components/pull-to-refresh/pull-to-refresh.tsx, src/components/pull-to-refresh/tests/pull-to-refresh.test.tsx
=> fix(PullToRefresh): cannot back to pulling status after complete in reduceMotion mode

src/components/text-area/tests/text-area.test.tsx, src/components/text-area/text-area.less, src/components/text-area/text-area.tsx
=> fix(TextArea): fix the height not adapting when setting `autoSize`

src/components/side-bar/side-bar.less
=> refactor: sidebar use new design token

src/components/notice-bar/notice-bar.less
=> refactor: notice bar use new design token

src/components/action-sheet/action-sheet.tsx, src/components/number-keyboard/number-keyboard.tsx, src/components/selector/selector.tsx, src/components/tabs/tabs.tsx, src/components/virtual-input/virtual-input.tsx, umd.html
[chore: 增加actionSheet、number-keyborad、selector、tabs和virtual-input组件的无障碍提示](https://github.com/ant-design/ant-design-mobile/commit/8ec0b27f0ede00f95b2240bbaed4c86e423db210)
=> chore: 增加actionSheet、number-keyborad、selector、tabs和virtual-input组件的无障碍提示

src/components/avatar/avatar.tsx, src/components/avatar/index.en.md, src/components/avatar/index.zh.md
component Avatar missing `onLoad` event
=> feat(Avatar): add `onLoad`

src/components/dropdown/dropdown.tsx, src/components/dropdown/index.en.md, src/components/dropdown/index.zh.md, src/components/dropdown/tests/dropdown.test.tsx
为 `Dropdown` 组件弹窗，增加 `getContainer` 配置
=> feat(Dropdown): add getContainer for Dropdown

src/components/search-bar/index.en.md, src/components/search-bar/index.zh.md, src/components/search-bar/search-bar.tsx
=> feat(SearchBar): support `onCompositionStart` `onCompositionEnd`

docs/components/components/Footer/index.tsx
chore: 🤖 fix help link ant-design-mini => ant-design-mobile
=> chore: 🤖 fix help link ant-design-mini => ant-design-mobile

src/components/text-area/tests/text-area.test.tsx, src/components/text-area/text-area.tsx
=> fix(TextArea): set `rows` to hidden textarea

package.json, pnpm-lock.yaml, src/components/ellipsis/ellipsis.tsx, src/components/text-area/tests/text-area.test.tsx, src/components/text-area/text-area.tsx
For example, input value like 
```
🏴󠁧󠁢󠁥󠁮󠁧󠁿🏴󠁵󠁳󠁷󠁡󠁿🏴🏴󠁵󠁳󠁴󠁸󠁿
```
=> fix: replace `runes` with `runes2` & fix text-area maxLength edge cases

src/components/cascade-picker-view/tests/cascade-picker-view.test.tsx, src/components/date-picker/date-picker-date-utils.ts, src/components/date-picker/date-picker-utils.ts, src/components/date-picker/date-picker-week-utils.ts, src/components/picker-view/picker-view.tsx, src/components/picker-view/tests/picker-view.test.tsx, src/components/search-bar/index.en.md, src/components/search-bar/index.zh.md, src/components/search-bar/search-bar.tsx
=> feat(picker): 扩展PickerColumnItem参数value类型,支持number

src/components/form/form-subscribe.tsx, src/components/form/tests/form.test.tsx
=> fix(Form): opt form Form.Subscribe do not call useless rerender

src/components/avatar/tests/avatar.test.tsx, src/components/image-uploader/tests/__snapshots__/image-uploader.test.tsx.snap, src/components/image/image.tsx
=> fix(Image): onload not triggered in nextjs

src/components/notice-bar/index.en.md, src/components/notice-bar/index.zh.md, src/components/notice-bar/notice-bar.tsx, src/components/notice-bar/tests/notice-bar.test.tsx
=> feat(notice-bar): add click event

README.md
Update Qcode of DingTalk group in README.md
=> Update Qcode of DingTalk group in README.md

docs/guide/css-variables.en.md, docs/guide/css-variables.zh.md
=> docs: update the description of the css-variables.zh/en.md

src/components/pull-to-refresh/pull-to-refresh.tsx
=> fix(PullToRefresh): fix shaking when in high resolution screen

src/components/swiper/demos/demo1.tsx, src/components/swiper/swiper.tsx
=> fix(swiper): repair onIndexChange trigger #6143

src/utils/reduce-and-restore-motion.ts
Close #5974
ref: https://react.dev/reference/react/useSyncExternalStore#adding-support-for-server-rendering
=> fix: `useSyncExternalStore` causes error on ssr

src/components/button/button.tsx, src/components/image/image.tsx, src/components/input/input.tsx
=> feat: Button Image Input add id

src/components/cascader-view/cascader-view.tsx, src/components/cascader-view/demos/demo1.tsx, src/components/cascader-view/index.en.md, src/components/cascader-view/index.zh.md, src/components/cascader-view/tests/cascader-view.test.tsx
#6189 
豆酱大佬看看@zombieJ ，可以的话 #6189 就 closel 了
=> feat(CascaderView ): add loading

src/components/cascader-view/cascader-view.tsx
=> refactor(CascaderView): if lese simplify

src/components/form/form-subscribe.tsx
[demo](https://codesandbox.io/s/crazy-marco-tt6zp4?file=/src/demo-subscribe.tsx)
被 useMemo 包裹的 props.children 没办法响应外部数据变化
=> fix(Form): add props.children to memo deps

package.json, pnpm-lock.yaml
ref:
https://github.com/floating-ui/floating-ui/releases
=> chore: upgrade `@floating-ui/dom`

src/components/action-sheet/index.en.md, src/components/action-sheet/index.zh.md, src/components/capsule-tabs/index.en.md, src/components/capsule-tabs/index.zh.md, src/components/cascader/index.en.md, src/components/cascader/index.zh.md, src/components/collapse/index.en.md, src/components/collapse/index.zh.md, src/components/dialog/index.en.md, src/components/dialog/index.zh.md, src/components/dropdown/index.en.md, src/components/dropdown/index.zh.md, src/components/jumbo-tabs/index.en.md, src/components/jumbo-tabs/index.zh.md, src/components/mask/index.en.md, src/components/mask/index.zh.md, src/components/modal/index.en.md, src/components/modal/index.zh.md, src/components/number-keyboard/index.en.md, src/components/number-keyboard/index.zh.md, src/components/picker/index.en.md, src/components/picker/index.zh.md, src/components/popup/index.en.md, src/components/popup/index.zh.md, src/components/tabs/index.en.md, src/components/tabs/index.zh.md
=> doc: Simplified description of destroyOnClose

src/components/cascade-picker-view/tests/cascade-picker-view.test.tsx
=> test: fix failed test

src/components/steps/steps.tsx
=> chore: prompt when repairing step cloneElement

src/components/collapse/collapse.tsx
=> refactor: to simplify the judge

src/components/picker-view/demos/demo1.tsx
=> chore: repair type warning

src/components/toast/toast.less
=> enhance(toast): compatible with rtl mode

src/utils/tests/use-lock-scroll.test.tsx
https://github.com/ant-design/ant-design-mobile/pull/6284#issuecomment-1667328825
=> test(useLockScroll): update test

src/components/floating-panel/floating-panel.tsx
=> fix: repir passive and preventDefault in components

src/components/error-block/create-error-block.tsx, src/components/error-block/tests/error-block.test.tsx
=> fix: error-block Normal display 0

.dumi/plugin-gallery/gallery.less, docs/components/components/Main/index.local.less, src/global/global.less
#6343 
修复黑夜模式下没有设置最外层容器背景色的问题 & 黑夜模式下官网主页部分文字看不清的问题
=> fix: page background in dark theme

src/components/toast/demos/demo1.tsx, src/components/toast/toast.less
=> fix(toast): toast content textAlign

pnpm-lock.yaml, src/components/image-viewer/image-viewer.tsx, src/components/image-viewer/slide.tsx, src/components/image-viewer/slides.tsx, src/components/image-viewer/tests/image-viewer.test.tsx
Reverts ant-design/ant-design-mobile#6317
=> Revert "enhance: delete drag lock. add leave view back to zoom"

docs/components/components/Main/MainSection/index.tsx
=> doc: update slogan

src/global/global.less
=> enhance: move background color from body to html to enable developer override

src/global/global.less, src/global/theme-dark.less, src/global/theme-default.less
仅设置暗色主题背景 token，亮色主题不做操作以避免覆盖影响。
=> enhance: reset html bg color with transparent

package.json, pnpm-lock.yaml
update @use-gesture/react package version to 10.3.0
This version fixes the issue https://github.com/pmndrs/use-gesture/issues/626
=> feat: update @use-gesture/react

src/components/badge/badge.tsx, src/components/button/button.tsx
=> style: className optimization

src/components/image-viewer/demos/demo1.tsx, src/components/image-viewer/image-viewer.tsx, src/components/image-viewer/index.en.md, src/components/image-viewer/index.zh.md
=> feat: add Semantic structure class

docs/guide/what-is-experimental.en.md
I made a few translation and grammar corrections in this document
=> grammar and translation fixes in what-is-experimental.en.md

src/components/picker-view/tests/picker-view.test.tsx, src/components/picker-view/wheel.tsx
=> feat: pick-view add active class

src/components/number-keyboard/number-keyboard.tsx
=> fix: title in renderHeader code fix

src/components/number-keyboard/index.en.md, src/components/number-keyboard/index.zh.md
=> docs: number-keyboard add tips

commitlint.config.js
=> chore: doc commitlint to docs

src/components/dropdown/dropdown.tsx, src/components/dropdown/index.en.md, src/components/dropdown/index.zh.md, src/components/dropdown/tests/dropdown.test.tsx
=> fix(Dropdown.Item): trigger the click event of "Dropdown. Item"  (#6480)

.gitignore, gulpfile.js, package.json, pnpm-lock.yaml
CI 一直在挂，看起来是 vite 打包并行写导致的覆盖问题。升级一下 vite 版本试试。
=> chore: bump vite

package.json, pnpm-lock.yaml, src/components/stepper/stepper.tsx, src/components/swiper/demos/demo8.less, src/components/swiper/demos/demo8.tsx, src/components/swiper/index.en.md, src/components/swiper/index.zh.md, src/components/swiper/swiper.less, src/components/swiper/swiper.tsx, src/components/swiper/tests/__snapshots__/swiper.test.tsx.snap, src/components/swiper/tests/swiper.test.tsx
Will release a minor version
Preview: https://antd-mobile-preview-pr-6504.surge.sh/~demos/swiper-demo8
=> feat(Swiper): support virtual scroll

src/components/checkbox/native-input.tsx, src/components/radio/radio.less, src/components/radio/radio.tsx
=> fix: 修复Radio组件隐藏所有input的问题

package.json, pnpm-lock.yaml, src/components/form/form.tsx
之前的 PR 有一个 commit 有问题先撤了，剩下这个 commit 应该没问题，CI 也跑过了。
=> refactor: replace lodash/merge with deepmerge

src/components/selector/index.zh.md
=> docs: Update index.zh.md

src/components/calendar-picker/demos/demo1.tsx
=> docs: revert demo

src/components/list/demos/demo1.tsx
增加 ListItem 的 arrowIcon 的 demo 示例
=> docs(ListItem): add arrowIcon demo

src/components/calendar-picker-view/tests/calendar-picker-view.test.tsx
=> test: unified class name variable

src/components/tabs/tabs.tsx
=> fix: rtl mode change not has init animate

package.json, pnpm-lock.yaml
升级 rc-field-form 更新一些已修复的问题
fix #6687
=> chore: upgrade rc-field-form dependencies ~1.27.4 to ^1.34.2

src/components/calendar-picker-view/calendar-picker-view.en.md, src/components/calendar-picker-view/calendar-picker-view.zh.md
React.ReactNode 包括 false, 不需要在声明一次
=> docs(CalenderPickerView): update title type doc

src/components/input/input.tsx
Feat - #6717 (updated)
Added the default HTML attribute event at tag i.e. as asked.
=> Added onpaste event/feature in <input/> tag

.github/workflows/check.yml
https://github.com/ant-design/ant-design/issues/50387
=> test: fix codecov action

.gitignore
=> chore: add bun.lockb to ignore

src/components/ellipsis/ellipsis.less
=> fix(Ellipsis): fix english not break

src/components/date-picker/date-picker-week-utils.ts, src/components/date-picker/tests/date-picker.test.tsx
=> fix(DatePicker): week select with year edge week not working as expect

src/components/swipe-action/index.en.md, src/components/swipe-action/index.zh.md, src/components/swipe-action/swipe-action.tsx, src/components/swipe-action/tests/swipe-action.test.tsx
=> feat(SwipeAction): support onClose action

src/components/image-viewer/index.en.md, src/components/image-viewer/index.zh.md
=> docs: update imageRender prop since version

src/components/config-provider/tests/__snapshots__/config-provider.test.tsx.snap, src/locales/ru-RU.ts
=> feat(Locale): update russian locale

src/components/space/space.less, src/components/space/space.patch.less
=> fix(Space): 水平排列时右侧多余留白问题

README.md, docs/guide/quick-start.en.md, docs/guide/quick-start.zh.md
=> docs: 修改过期的钉钉群二维码

src/components/button/button.tsx, src/components/button/index.en.md, src/components/button/index.zh.md
希望能在 Button 组件中使用 form 属性来指定特定的表单 id。
=> feat: add form attribute for Button component

src/demos/demo-block/index.tsx
纯 AI 代码，无人工成分
控制台报错：
cursor 对话：
=> fix: 修正 defaultProps warning

src/components/image-viewer/tests/image-viewer.test.tsx
master 最新的提交 ci 怎么坏了
commit：https://github.com/ant-design/ant-design-mobile/commit/e8243d2268faa9e829c6f53c41d577c67ba5397d
log：https://github.com/ant-design/ant-design-mobile/actions/runs/14920287275/job/41914226243
=> chore: fix ci

src/components/date-picker-view/date-picker-view.tsx, src/components/date-picker-view/useRenderLabel.ts, src/components/date-picker/date-picker-date-utils.ts, src/components/date-picker/date-picker-quarter-utils.ts, src/components/date-picker/date-picker-week-utils.ts, src/components/date-picker/tests/date-picker.test.tsx, src/components/picker/index.en.md, src/components/picker/index.zh.md
=> feature(DatePicker): renderLabel add selected parameter

docs/guide/v5-for-19.en.md, docs/guide/v5-for-19.zh.md, src/components/picker/index.en.md, src/components/picker/index.zh.md
#6880 supplemental version description
=> docs: picker info parameter add version doc
